-- =============================================================================
-- DRISHTI graph-analysis objects (Phase 6)
-- Target: PostgreSQL 15+ / Supabase
-- Depends on: police_fir_schema.sql, police_fir_intelligence.sql,
--             police_fir_extensions.sql, services/ml/sql/001_readonly_role.sql
-- =============================================================================
--
-- Materialization target for the hidden-association detector (doc 04 §6). The
-- nightly batch computes candidate pairs and UPSERTs them here so the UI pages
-- an instantly-ready ranked feed and never recomputes on read.
--
-- RLS left DISABLED (consistent with the rest of the schema; re-enabled Phase 14).
-- =============================================================================

BEGIN;

CREATE TABLE IF NOT EXISTS "drishti_hidden_associations" (
    "AssociationID"        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "EntityA"              BIGINT NOT NULL REFERENCES "EntityGraph" ("EntityID") ON DELETE CASCADE,
    "EntityB"              BIGINT NOT NULL REFERENCES "EntityGraph" ("EntityID") ON DELETE CASCADE,
    "IndependentLinks"     INTEGER NOT NULL CHECK ("IndependentLinks" >= 2),
    "LinkKinds"            TEXT[]  NOT NULL,          -- e.g. {phone,vehicle,location}
    "SharedIntermediaries" BIGINT[] NOT NULL,         -- EntityIDs of shared nodes (proof)
    "ProofRecordIds"       TEXT[]  NOT NULL,          -- typed refs, e.g. EntityGraph:20001
    "Score"                NUMERIC(8,5) NOT NULL DEFAULT 0,
    "SharedCaseCount"      INTEGER NOT NULL DEFAULT 0, -- must be 0 to qualify (no common FIR)
    "ModelVersionID"       INTEGER REFERENCES "ModelVersion" ("ModelVersionID"),
    "DetectedAt"           TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT "chk_hidden_pair_order" CHECK ("EntityA" < "EntityB"),
    CONSTRAINT "uq_hidden_pair" UNIQUE ("EntityA", "EntityB")
);
COMMENT ON TABLE "drishti_hidden_associations" IS
    'Materialized hidden-association candidates: entity pairs sharing >=2 distinct indirect link kinds with ZERO common FIRs (doc 04 §6). Refreshed by the nightly graph batch.';

CREATE INDEX IF NOT EXISTS "idx_hidden_entity_a"  ON "drishti_hidden_associations" ("EntityA");
CREATE INDEX IF NOT EXISTS "idx_hidden_entity_b"  ON "drishti_hidden_associations" ("EntityB");
CREATE INDEX IF NOT EXISTS "idx_hidden_score"     ON "drishti_hidden_associations" ("Score" DESC);
CREATE INDEX IF NOT EXISTS "idx_hidden_links"     ON "drishti_hidden_associations" ("IndependentLinks" DESC);
CREATE INDEX IF NOT EXISTS "gin_hidden_linkkinds" ON "drishti_hidden_associations" USING GIN ("LinkKinds");

ALTER TABLE "drishti_hidden_associations" DISABLE ROW LEVEL SECURITY;

-- The read-only role reads the feed (it may not have been auto-granted if the
-- default-privileges owner differs; grant explicitly to be safe).
DO $$
BEGIN
    IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'drishti_readonly') THEN
        GRANT SELECT ON "drishti_hidden_associations" TO drishti_readonly;
    END IF;
END$$;

COMMIT;
