-- =============================================================================
-- DRISHTI case evidence store (Phase 15c — Cases destination)
-- Target: PostgreSQL 15+ / Supabase
-- Depends on: police_fir_schema.sql, services/ml/sql/001_readonly_role.sql
-- =============================================================================
--
-- The base schema has no evidence/attachment/note table, but the Case file's
-- Evidence sub-page needs a real, typed place for the "+ Add evidence" action
-- (doc 01 §4.2 / §6 — "act where you look"). This is that typed table. Writes
-- are IO-gated in the API (app/cases/permissions.py); reads go through the
-- read-only role. PII-adjacent, so treat as sensitive (RLS re-enabled Phase 14).
--
-- Idempotent: safe to run repeatedly.
-- =============================================================================

BEGIN;

CREATE TABLE IF NOT EXISTS "CaseEvidence" (
    "EvidenceID"    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "CaseMasterID"  INTEGER NOT NULL REFERENCES "CaseMaster" ("CaseMasterID") ON DELETE CASCADE,
    "EvidenceType"  VARCHAR NOT NULL DEFAULT 'note',   -- note | seizure | attachment | statement | exhibit
    "Title"         VARCHAR NOT NULL,
    "Description"   TEXT,
    "Reference"     VARCHAR,                            -- external ref / seizure no / file locator
    "CreatedByRole" VARCHAR,                            -- role that added it (until auth; Phase 14 -> user_id)
    "CreatedAt"     TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT "chk_caseevidence_type" CHECK (
        "EvidenceType" IN ('note','seizure','attachment','statement','exhibit')
    )
);
COMMENT ON TABLE "CaseEvidence" IS
    'Case evidence / seizures / notes added inline from the Case file Evidence sub-page (Phase 15c). Writes are IO-gated in the API.';

CREATE INDEX IF NOT EXISTS "idx_caseevidence_case"
    ON "CaseEvidence" ("CaseMasterID", "CreatedAt" DESC);

ALTER TABLE "CaseEvidence" DISABLE ROW LEVEL SECURITY;

-- The read-only role must be able to read the evidence feed.
DO $$
BEGIN
    IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'drishti_readonly') THEN
        GRANT SELECT ON "CaseEvidence" TO drishti_readonly;
    END IF;
END$$;

COMMIT;
