-- =============================================================================
-- DRISHTI migration 006 — ingestion staging + digital-evidence platform
-- Target: PostgreSQL 15+ / Supabase (live PG 17.6)
-- Depends on: police_fir_schema.sql, police_fir_intelligence.sql,
--             police_fir_extensions.sql, services/ml/sql/005_security_rls_audit.sql
-- =============================================================================
--
-- Adds the source/ingestion staging layer and the logical digital-evidence
-- model the audit found missing (CaseEvidence was empty). HACKATHON SCOPE:
-- structured/manual metadata ONLY. No OCR/extraction tables here (deferred).
-- File bytes never live in PostgreSQL — EvidenceObject stores the manifest
-- (storage key, SHA-256, size). Fixtures are marked pending cloud upload.
--
-- RLS stays DISABLED + NO FORCE (hackathon). No RLS policies. Additive +
-- idempotent: safe to run repeatedly.
-- =============================================================================

BEGIN;

-- =============================================================================
-- 1. SOURCE SYSTEMS + INGESTION STAGING (Group 2)
-- =============================================================================

CREATE TABLE IF NOT EXISTS "SourceSystem" (
    "SourceSystemID" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "Code"           VARCHAR NOT NULL UNIQUE,     -- e.g. FIR_FORM, CSV_IMPORT, CCTNS_SYN
    "Name"           VARCHAR NOT NULL,
    "Kind"           VARCHAR NOT NULL DEFAULT 'manual_form',
    "Description"    TEXT,
    "IsSynthetic"    BOOLEAN NOT NULL DEFAULT TRUE,
    "CreatedAt"      TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT "chk_sourcesystem_kind" CHECK ("Kind" IN
        ('manual_form','csv_import','json_import','external_reference','digital_export','court_document'))
);
COMMENT ON TABLE "SourceSystem" IS 'Logical source systems/methods that feed cases and evidence (all synthetic in hackathon).';

CREATE TABLE IF NOT EXISTS "SourceRecord" (
    "SourceRecordID" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "SourceSystemID" INTEGER NOT NULL REFERENCES "SourceSystem" ("SourceSystemID"),
    "ExternalRef"    VARCHAR,                       -- synthetic external key
    "RecordKind"     VARCHAR NOT NULL DEFAULT 'case',
    "Payload"        JSONB NOT NULL DEFAULT '{}'::jsonb,   -- raw structured submission (staging)
    "ContentHash"    VARCHAR,                       -- dedupe key (sha256 of payload)
    "Version"        INTEGER NOT NULL DEFAULT 1,
    "SupersededBySourceRecordID" BIGINT REFERENCES "SourceRecord" ("SourceRecordID"),
    "Status"         VARCHAR NOT NULL DEFAULT 'received',  -- received|staged|committed|rejected|retracted|duplicate|stale
    "IsSynthetic"    BOOLEAN NOT NULL DEFAULT TRUE,
    "ReceivedAt"     TIMESTAMPTZ NOT NULL DEFAULT now(),
    "CreatedAt"      TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT "chk_sourcerecord_status" CHECK ("Status" IN
        ('received','staged','committed','rejected','retracted','duplicate','stale'))
);
COMMENT ON TABLE "SourceRecord" IS 'Provenance: every canonical row/evidence item traces to a versioned source record. Supports supersession/retraction.';

CREATE TABLE IF NOT EXISTS "IngestionJob" (
    "IngestionJobID" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "SourceSystemID" INTEGER REFERENCES "SourceSystem" ("SourceSystemID"),
    "JobKind"        VARCHAR NOT NULL DEFAULT 'form_submit',
    "IdempotencyKey" VARCHAR UNIQUE,               -- safe retry / partial-import de-dup
    "Status"         VARCHAR NOT NULL DEFAULT 'pending',  -- pending|dry_run|running|committed|failed|partial
    "DryRun"         BOOLEAN NOT NULL DEFAULT FALSE,
    "Totals"         JSONB NOT NULL DEFAULT '{}'::jsonb,  -- accepted/rejected/duplicate counts
    "StartedAt"      TIMESTAMPTZ NOT NULL DEFAULT now(),
    "FinishedAt"     TIMESTAMPTZ,
    CONSTRAINT "chk_ingestionjob_status" CHECK ("Status" IN
        ('pending','dry_run','running','committed','failed','partial'))
);
COMMENT ON TABLE "IngestionJob" IS 'Idempotent ingestion/import jobs with dry-run + partial-import + retry semantics.';

CREATE TABLE IF NOT EXISTS "IngestionRecord" (
    "IngestionRecordID" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "IngestionJobID"    BIGINT NOT NULL REFERENCES "IngestionJob" ("IngestionJobID") ON DELETE CASCADE,
    "SourceRecordID"    BIGINT REFERENCES "SourceRecord" ("SourceRecordID"),
    "RowNumber"         INTEGER,
    "StagingPayload"    JSONB NOT NULL DEFAULT '{}'::jsonb,
    "Status"            VARCHAR NOT NULL DEFAULT 'staged',  -- staged|committed|rejected|duplicate
    "RejectReason"      TEXT,
    "CreatedAt"         TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT "chk_ingestionrecord_status" CHECK ("Status" IN
        ('staged','committed','rejected','duplicate'))
);
COMMENT ON TABLE "IngestionRecord" IS 'Per-row staging outcome for an ingestion job. Invalid/rejected rows stay here, never in canonical tables.';

-- =============================================================================
-- 2. DIGITAL EVIDENCE (Group 5) — logical items + storage manifest objects
-- =============================================================================

CREATE TABLE IF NOT EXISTS "EvidenceItem" (
    "EvidenceItemID"  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "CaseMasterID"    INTEGER REFERENCES "CaseMaster" ("CaseMasterID"),  -- primary case (also EvidenceCaseLink)
    "SourceSystemID"  INTEGER REFERENCES "SourceSystem" ("SourceSystemID"),
    "SourceRecordID"  BIGINT REFERENCES "SourceRecord" ("SourceRecordID"),
    "EvidenceType"    VARCHAR NOT NULL DEFAULT 'document',
    "Category"        VARCHAR,
    "Title"           VARCHAR NOT NULL,
    "Description"     TEXT,
    "SyntheticReference" VARCHAR,                    -- unmistakably synthetic ref no
    "Language"        VARCHAR DEFAULT 'en',
    "Tags"            TEXT[] NOT NULL DEFAULT '{}',
    "UploaderActor"   VARCHAR,                        -- demo actor (display/audit only)
    "Confidentiality" VARCHAR NOT NULL DEFAULT 'demo_normal',
    "State"           VARCHAR NOT NULL DEFAULT 'draft',  -- draft|uploading|available|failed|archived
    "ManualMetadata"  JSONB NOT NULL DEFAULT '{}'::jsonb, -- title/type/source/date/desc/tags entered by hand
    "CapturedAt"      TIMESTAMPTZ,
    "ReceivedAt"      TIMESTAMPTZ,
    "UploadedAt"      TIMESTAMPTZ,
    "IsSynthetic"     BOOLEAN NOT NULL DEFAULT TRUE,
    "CreatedAt"       TIMESTAMPTZ NOT NULL DEFAULT now(),
    "UpdatedAt"       TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT "chk_evidenceitem_type" CHECK ("EvidenceType" IN
        ('document','statement','image','video','audio','physical_exhibit',
         'property_item','forensic_report','digital_export','financial_dataset',
         'court_document','external_reference')),
    CONSTRAINT "chk_evidenceitem_state" CHECK ("State" IN
        ('draft','uploading','available','failed','archived'))
);
COMMENT ON TABLE "EvidenceItem" IS 'Logical digital-evidence item with MANUALLY entered metadata. No OCR/extraction in hackathon; file contents are never auto-parsed.';

CREATE TABLE IF NOT EXISTS "EvidenceObject" (
    "EvidenceObjectID" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "EvidenceItemID"   BIGINT NOT NULL REFERENCES "EvidenceItem" ("EvidenceItemID") ON DELETE CASCADE,
    "StorageKey"       VARCHAR,                       -- s3://bucket/prefix/... (no object yet in P1)
    "StorageStatus"    VARCHAR NOT NULL DEFAULT 'fixture_pending_cloud_upload',
    "FileName"         VARCHAR,
    "MimeType"         VARCHAR,
    "SizeBytes"        BIGINT CHECK ("SizeBytes" IS NULL OR "SizeBytes" >= 0),
    "Sha256"           VARCHAR NOT NULL,             -- REAL sha256 of the fixture file
    "VersionNo"        INTEGER NOT NULL DEFAULT 1,
    "IsCurrent"        BOOLEAN NOT NULL DEFAULT TRUE,
    "ManualProvenance" JSONB NOT NULL DEFAULT '{}'::jsonb,
    "CreatedAt"        TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT "chk_evidenceobject_storage" CHECK ("StorageStatus" IN
        ('fixture_pending_cloud_upload','available','quarantined','missing','failed'))
);
COMMENT ON TABLE "EvidenceObject" IS 'Storage manifest for an evidence file version: storage key + REAL sha256 + size. File bytes live in S3 (Phase 5), never in PostgreSQL.';

CREATE TABLE IF NOT EXISTS "EvidenceVersion" (
    "EvidenceVersionID" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "EvidenceItemID"    BIGINT NOT NULL REFERENCES "EvidenceItem" ("EvidenceItemID") ON DELETE CASCADE,
    "VersionNo"         INTEGER NOT NULL,
    "EvidenceObjectID"  BIGINT REFERENCES "EvidenceObject" ("EvidenceObjectID"),
    "ChangeReason"      TEXT,
    "CreatedByActor"    VARCHAR,
    "CreatedAt"         TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT "uq_evidenceversion" UNIQUE ("EvidenceItemID", "VersionNo")
);
COMMENT ON TABLE "EvidenceVersion" IS 'Append-only version history for an evidence item (metadata correction / file replacement).';

CREATE TABLE IF NOT EXISTS "EvidenceCaseLink" (
    "EvidenceCaseLinkID" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "EvidenceItemID"     BIGINT NOT NULL REFERENCES "EvidenceItem" ("EvidenceItemID") ON DELETE CASCADE,
    "CaseMasterID"       INTEGER NOT NULL REFERENCES "CaseMaster" ("CaseMasterID"),
    "LinkType"           VARCHAR NOT NULL DEFAULT 'evidence',
    "CreatedByActor"     VARCHAR,
    "CreatedAt"          TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT "uq_evidencecaselink" UNIQUE ("EvidenceItemID", "CaseMasterID")
);
COMMENT ON TABLE "EvidenceCaseLink" IS 'Many-to-many evidence<->case links (an item can evidence multiple cases).';

CREATE TABLE IF NOT EXISTS "EvidenceActivityEvent" (
    "EvidenceActivityEventID" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "EvidenceItemID" BIGINT NOT NULL REFERENCES "EvidenceItem" ("EvidenceItemID") ON DELETE CASCADE,
    "EventType"      VARCHAR NOT NULL,      -- created|metadata_updated|version_added|linked|unlinked|archived|access_attempt|download
    "Actor"          VARCHAR,
    "Detail"         JSONB NOT NULL DEFAULT '{}'::jsonb,
    "CreatedAt"      TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT "chk_evidenceactivity_type" CHECK ("EventType" IN
        ('created','metadata_updated','version_added','linked','unlinked',
         'archived','access_attempt','download','custody_transfer'))
);
COMMENT ON TABLE "EvidenceActivityEvent" IS 'Append-only evidence custody/activity audit trail. Never overwrites history.';

-- =============================================================================
-- 3. DATA-QUALITY ISSUES (Group 2) — deliberate/observed problems in staging
-- =============================================================================
CREATE TABLE IF NOT EXISTS "DataQualityIssue" (
    "DataQualityIssueID" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "IssueType"      VARCHAR NOT NULL,     -- missing_required|invalid_format|duplicate_source|conflicting_dates|invalid_jurisdiction|...
    "Severity"       VARCHAR NOT NULL DEFAULT 'warning',   -- info|warning|error|blocker
    "SourceRecordID" BIGINT REFERENCES "SourceRecord" ("SourceRecordID"),
    "IngestionJobID" BIGINT REFERENCES "IngestionJob" ("IngestionJobID"),
    "CaseMasterID"   INTEGER REFERENCES "CaseMaster" ("CaseMasterID"),
    "EvidenceItemID" BIGINT REFERENCES "EvidenceItem" ("EvidenceItemID"),
    "Detail"         JSONB NOT NULL DEFAULT '{}'::jsonb,
    "Status"         VARCHAR NOT NULL DEFAULT 'open',      -- open|resolved|quarantined|accepted
    "ResolvedByActor" VARCHAR,
    "CreatedAt"      TIMESTAMPTZ NOT NULL DEFAULT now(),
    "ResolvedAt"     TIMESTAMPTZ,
    CONSTRAINT "chk_dqi_severity" CHECK ("Severity" IN ('info','warning','error','blocker')),
    CONSTRAINT "chk_dqi_status"   CHECK ("Status" IN ('open','resolved','quarantined','accepted'))
);
COMMENT ON TABLE "DataQualityIssue" IS 'Staging/quarantine record of data-quality problems; keeps invalid input out of canonical tables.';

-- =============================================================================
-- 4. INDEXES
-- =============================================================================
CREATE INDEX IF NOT EXISTS "idx_sourcerecord_system"     ON "SourceRecord" ("SourceSystemID");
CREATE INDEX IF NOT EXISTS "idx_sourcerecord_hash"       ON "SourceRecord" ("ContentHash");
CREATE INDEX IF NOT EXISTS "idx_sourcerecord_status"     ON "SourceRecord" ("Status");
CREATE INDEX IF NOT EXISTS "idx_ingestionjob_system"     ON "IngestionJob" ("SourceSystemID");
CREATE INDEX IF NOT EXISTS "idx_ingestionrecord_job"     ON "IngestionRecord" ("IngestionJobID");
CREATE INDEX IF NOT EXISTS "idx_ingestionrecord_source"  ON "IngestionRecord" ("SourceRecordID");
CREATE INDEX IF NOT EXISTS "idx_evidenceitem_case"       ON "EvidenceItem" ("CaseMasterID");
CREATE INDEX IF NOT EXISTS "idx_evidenceitem_source"     ON "EvidenceItem" ("SourceRecordID");
CREATE INDEX IF NOT EXISTS "idx_evidenceitem_type"       ON "EvidenceItem" ("EvidenceType");
CREATE INDEX IF NOT EXISTS "idx_evidenceitem_state"      ON "EvidenceItem" ("State");
CREATE INDEX IF NOT EXISTS "idx_evidenceobject_item"     ON "EvidenceObject" ("EvidenceItemID");
CREATE INDEX IF NOT EXISTS "idx_evidenceobject_hash"     ON "EvidenceObject" ("Sha256");
CREATE INDEX IF NOT EXISTS "idx_evidenceversion_item"    ON "EvidenceVersion" ("EvidenceItemID");
CREATE INDEX IF NOT EXISTS "idx_evidencecaselink_case"   ON "EvidenceCaseLink" ("CaseMasterID");
CREATE INDEX IF NOT EXISTS "idx_evidenceactivity_item"   ON "EvidenceActivityEvent" ("EvidenceItemID");
CREATE INDEX IF NOT EXISTS "idx_dqi_source"              ON "DataQualityIssue" ("SourceRecordID");
CREATE INDEX IF NOT EXISTS "idx_dqi_case"                ON "DataQualityIssue" ("CaseMasterID");
CREATE INDEX IF NOT EXISTS "idx_dqi_status"              ON "DataQualityIssue" ("Status");

CREATE INDEX IF NOT EXISTS "gin_sourcerecord_payload"    ON "SourceRecord" USING GIN ("Payload");
CREATE INDEX IF NOT EXISTS "gin_evidenceitem_meta"       ON "EvidenceItem" USING GIN ("ManualMetadata");
CREATE INDEX IF NOT EXISTS "gin_evidenceitem_tags"       ON "EvidenceItem" USING GIN ("Tags");
CREATE INDEX IF NOT EXISTS "gin_dqi_detail"              ON "DataQualityIssue" USING GIN ("Detail");

-- =============================================================================
-- 5. TRIGGERS (updated_at maintenance — reuse shared fn_set_updated_at())
-- =============================================================================
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_trigger WHERE tgname = 'trg_evidenceitem_updated') THEN
        CREATE TRIGGER "trg_evidenceitem_updated" BEFORE UPDATE ON "EvidenceItem"
            FOR EACH ROW EXECUTE FUNCTION fn_set_updated_at();
    END IF;
END$$;

-- =============================================================================
-- 6. Grants + RLS disabled/NO FORCE + global verification (hackathon).
-- =============================================================================
DO $$
DECLARE t TEXT;
BEGIN
    IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'drishti_readonly') THEN
        FOREACH t IN ARRAY ARRAY[
            'SourceSystem','SourceRecord','IngestionJob','IngestionRecord',
            'EvidenceItem','EvidenceObject','EvidenceVersion','EvidenceCaseLink',
            'EvidenceActivityEvent','DataQualityIssue'
        ] LOOP
            EXECUTE format('GRANT SELECT ON %I TO drishti_readonly', t);
        END LOOP;
    END IF;
END$$;

SELECT fn_disable_rls_all_app();
SELECT fn_assert_rls_disabled();

COMMIT;

-- =============================================================================
-- End of migration 006.
-- =============================================================================
