-- =============================================================================
-- DRISHTI migration 007 — canonical identity, case workflow, statements,
--                          property/seizure, digital, and court/outcome domains
-- Target: PostgreSQL 15+ / Supabase (live PG 17.6)
-- Depends on: 005_security_rls_audit.sql, 006_ingestion_evidence.sql
-- =============================================================================
--
-- This is the heart of the identity redesign the audit demanded. It replaces
-- A1/A2/name-based identity with a STABLE CanonicalPersonID reused across cases,
-- a CasePartyRole row per appearance, category-specific append-only CaseEvents,
-- and canonical incident coordinates in CaseVersion (so the spatial-containment
-- gate validates canonical geometry, not the legacy CaseMaster lat/long).
--
-- Legacy tables are preserved. Backward-compatible CanonicalPersonID /
-- CanonicalEntityID / SourceRecordID columns are ADDED (never dropped) so the
-- generator and future readers can migrate off name-joins incrementally.
--
-- RLS stays DISABLED + NO FORCE (hackathon). No RLS policies. Additive +
-- idempotent: safe to run repeatedly.
-- =============================================================================

BEGIN;

-- =============================================================================
-- 1. CANONICAL IDENTITY (Group 3)
-- =============================================================================

CREATE TABLE IF NOT EXISTS "CanonicalPerson" (
    "CanonicalPersonID" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "PublicRef"         VARCHAR NOT NULL UNIQUE,     -- e.g. SYN-PERSON-000123 (unmistakably synthetic)
    "DisplayLabel"      VARCHAR,                       -- a LABEL/attribute, never an identity key
    "IsUnknown"         BOOLEAN NOT NULL DEFAULT FALSE,-- unidentified party; no invented identity
    "PrimaryGenderID"   INTEGER,                       -- 1/2/3/NULL (unknown/undisclosed allowed)
    "ApproxBirthYear"   INTEGER,
    "IsJuvenile"        BOOLEAN NOT NULL DEFAULT FALSE,-- protected attribute; excluded from feature schemas
    "ResolutionStatus"  VARCHAR NOT NULL DEFAULT 'canonical', -- canonical|candidate|merged
    "MergedIntoCanonicalPersonID" BIGINT REFERENCES "CanonicalPerson" ("CanonicalPersonID"),
    "Attributes"        JSONB NOT NULL DEFAULT '{}'::jsonb,
    "IsSynthetic"       BOOLEAN NOT NULL DEFAULT TRUE,
    "CreatedAt"         TIMESTAMPTZ NOT NULL DEFAULT now(),
    "UpdatedAt"         TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT "chk_canonperson_resolution"
        CHECK ("ResolutionStatus" IN ('canonical','candidate','merged'))
);
COMMENT ON TABLE "CanonicalPerson" IS 'Stable synthetic person identity reused across cases. Replaces A1/A2/name matching. Names are attributes/aliases, never keys.';

CREATE TABLE IF NOT EXISTS "CanonicalOrganisation" (
    "CanonicalOrganisationID" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "PublicRef"   VARCHAR NOT NULL UNIQUE,             -- SYN-ORG-000045
    "Name"        VARCHAR NOT NULL,
    "OrgType"     VARCHAR,                              -- gang|company|association|unknown
    "Attributes"  JSONB NOT NULL DEFAULT '{}'::jsonb,
    "IsSynthetic" BOOLEAN NOT NULL DEFAULT TRUE,
    "CreatedAt"   TIMESTAMPTZ NOT NULL DEFAULT now()
);
COMMENT ON TABLE "CanonicalOrganisation" IS 'Stable synthetic organisation identity (gangs/companies) reused across cases.';

CREATE TABLE IF NOT EXISTS "CanonicalEntity" (
    "CanonicalEntityID"       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "EntityKind"              VARCHAR NOT NULL,        -- person|organisation|phone|vehicle|account|device|location
    "CanonicalPersonID"       BIGINT REFERENCES "CanonicalPerson" ("CanonicalPersonID"),
    "CanonicalOrganisationID" BIGINT REFERENCES "CanonicalOrganisation" ("CanonicalOrganisationID"),
    "PublicRef"   VARCHAR NOT NULL UNIQUE,             -- SYN-ENT-000777
    "Label"       VARCHAR,
    "Attributes"  JSONB NOT NULL DEFAULT '{}'::jsonb,
    "IsSynthetic" BOOLEAN NOT NULL DEFAULT TRUE,
    "CreatedAt"   TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT "chk_canonentity_kind" CHECK ("EntityKind" IN
        ('person','organisation','phone','vehicle','account','device','location'))
);
COMMENT ON TABLE "CanonicalEntity" IS 'Unified graph-entity node. EntityGraph links here through CanonicalEntityID (true FK), never through names/array indexes.';

CREATE TABLE IF NOT EXISTS "PersonAlias" (
    "PersonAliasID"     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "CanonicalPersonID" BIGINT NOT NULL REFERENCES "CanonicalPerson" ("CanonicalPersonID") ON DELETE CASCADE,
    "AliasName"         VARCHAR NOT NULL,
    "AliasType"         VARCHAR NOT NULL DEFAULT 'alias',  -- alias|aka|nickname|maiden|misspelling
    "SourceRecordID"    BIGINT REFERENCES "SourceRecord" ("SourceRecordID"),
    "IsSynthetic"       BOOLEAN NOT NULL DEFAULT TRUE,
    "CreatedAt"         TIMESTAMPTZ NOT NULL DEFAULT now()
);
COMMENT ON TABLE "PersonAlias" IS 'Alternate names for a canonical person (same-person/alias scenarios). Names are attributes, never identity keys.';

CREATE TABLE IF NOT EXISTS "PersonIdentifier" (
    "PersonIdentifierID" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "CanonicalPersonID"  BIGINT NOT NULL REFERENCES "CanonicalPerson" ("CanonicalPersonID") ON DELETE CASCADE,
    "IdentifierType"     VARCHAR NOT NULL,     -- synthetic_govt_id|synthetic_pan|synthetic_voter (all clearly fake)
    "IdentifierValue"    VARCHAR NOT NULL,     -- unmistakably synthetic token
    "Sensitivity"        VARCHAR NOT NULL DEFAULT 'restricted',
    "SourceRecordID"     BIGINT REFERENCES "SourceRecord" ("SourceRecordID"),
    "IsSynthetic"        BOOLEAN NOT NULL DEFAULT TRUE,
    "CreatedAt"          TIMESTAMPTZ NOT NULL DEFAULT now()
);
COMMENT ON TABLE "PersonIdentifier" IS 'Synthetic person identifiers (never real IDs). Sensitivity-classified; excluded from model feature schemas by default.';

CREATE TABLE IF NOT EXISTS "PersonContact" (
    "PersonContactID"   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "CanonicalPersonID" BIGINT NOT NULL REFERENCES "CanonicalPerson" ("CanonicalPersonID") ON DELETE CASCADE,
    "ContactType"       VARCHAR NOT NULL DEFAULT 'phone',  -- phone|email
    "ContactValue"      VARCHAR NOT NULL,                    -- synthetic phone/email
    "Sensitivity"       VARCHAR NOT NULL DEFAULT 'restricted',
    "SourceRecordID"    BIGINT REFERENCES "SourceRecord" ("SourceRecordID"),
    "IsSynthetic"       BOOLEAN NOT NULL DEFAULT TRUE,
    "CreatedAt"         TIMESTAMPTZ NOT NULL DEFAULT now()
);
COMMENT ON TABLE "PersonContact" IS 'Synthetic contact points for a canonical person. Phone strings are attributes here, never identity keys.';

CREATE TABLE IF NOT EXISTS "PersonAddress" (
    "PersonAddressID"   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "CanonicalPersonID" BIGINT NOT NULL REFERENCES "CanonicalPerson" ("CanonicalPersonID") ON DELETE CASCADE,
    "DistrictID"        INTEGER REFERENCES "District" ("DistrictID"),
    "AddressText"       VARCHAR,
    "geom"              geometry(Point, 4326),
    "Sensitivity"       VARCHAR NOT NULL DEFAULT 'restricted',
    "SourceRecordID"    BIGINT REFERENCES "SourceRecord" ("SourceRecordID"),
    "IsSynthetic"       BOOLEAN NOT NULL DEFAULT TRUE,
    "CreatedAt"         TIMESTAMPTZ NOT NULL DEFAULT now()
);
COMMENT ON TABLE "PersonAddress" IS 'Synthetic addresses for a canonical person (district-scoped, on real KA land).';

CREATE TABLE IF NOT EXISTS "EntityResolutionCandidate" (
    "EntityResolutionCandidateID" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "CanonicalPersonA" BIGINT NOT NULL REFERENCES "CanonicalPerson" ("CanonicalPersonID"),
    "CanonicalPersonB" BIGINT NOT NULL REFERENCES "CanonicalPerson" ("CanonicalPersonID"),
    "Method"           VARCHAR NOT NULL DEFAULT 'deterministic',  -- deterministic|fuzzy
    "Score"            NUMERIC(6,5) CHECK ("Score" IS NULL OR "Score" BETWEEN 0 AND 1),
    "MatchFeatures"    JSONB NOT NULL DEFAULT '{}'::jsonb,
    "Status"           VARCHAR NOT NULL DEFAULT 'pending',  -- pending|accepted|rejected|new
    "ReviewedByActor"  VARCHAR,
    "ReviewedAt"       TIMESTAMPTZ,
    "CreatedAt"        TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT "chk_erc_order" CHECK ("CanonicalPersonA" <> "CanonicalPersonB"),
    CONSTRAINT "chk_erc_status" CHECK ("Status" IN ('pending','accepted','rejected','new'))
);
COMMENT ON TABLE "EntityResolutionCandidate" IS 'Proposed person matches for human review. NEVER auto-merged. Same-name/different-person stays separate unless reviewed.';

CREATE TABLE IF NOT EXISTS "EntityMergeHistory" (
    "EntityMergeHistoryID" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "Action"          VARCHAR NOT NULL DEFAULT 'merge',   -- merge|split
    "WinnerCanonicalPersonID" BIGINT REFERENCES "CanonicalPerson" ("CanonicalPersonID"),
    "LoserCanonicalPersonID"  BIGINT REFERENCES "CanonicalPerson" ("CanonicalPersonID"),
    "Reason"      TEXT,
    "Actor"       VARCHAR,
    "BeforeState" JSONB NOT NULL DEFAULT '{}'::jsonb,
    "AfterState"  JSONB NOT NULL DEFAULT '{}'::jsonb,
    "CreatedAt"   TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT "chk_emh_action" CHECK ("Action" IN ('merge','split'))
);
COMMENT ON TABLE "EntityMergeHistory" IS 'Reversible merge/split decisions with reviewer + before/after state for audit.';

-- =============================================================================
-- 2. CASE-PARTY ROLES (Group 3) — one row per appearance/role
-- =============================================================================
CREATE TABLE IF NOT EXISTS "CasePartyRole" (
    "CasePartyRoleID" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "CaseMasterID"    INTEGER NOT NULL REFERENCES "CaseMaster" ("CaseMasterID"),
    "CanonicalPersonID" BIGINT REFERENCES "CanonicalPerson" ("CanonicalPersonID"),
    "CanonicalOrganisationID" BIGINT REFERENCES "CanonicalOrganisation" ("CanonicalOrganisationID"),
    "RoleType"        VARCHAR NOT NULL,   -- accused|victim|complainant|witness|informant|guardian|organisation|unknown
    "IsUnknownParty"  BOOLEAN NOT NULL DEFAULT FALSE,
    "LegacyRefTable"  VARCHAR,             -- Accused|Victim|ComplainantDetails (back-compat)
    "LegacyRefID"     INTEGER,             -- the legacy row's PK
    "PartyLabel"      VARCHAR,             -- display name snapshot
    "SequenceNo"      INTEGER,             -- A1/A2 ordering preserved as an attribute, not identity
    "Provenance"      JSONB NOT NULL DEFAULT '{}'::jsonb,
    "CreatedAt"       TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT "chk_casepartyrole_type" CHECK ("RoleType" IN
        ('accused','victim','complainant','witness','informant','guardian','organisation','unknown')),
    CONSTRAINT "chk_casepartyrole_ref" CHECK (
        "CanonicalPersonID" IS NOT NULL
        OR "CanonicalOrganisationID" IS NOT NULL
        OR "IsUnknownParty" = TRUE
    )
);
COMMENT ON TABLE "CasePartyRole" IS 'Links a canonical person/organisation (or an explicit unknown party) to a case with a role. The identity backbone replacing name joins.';

-- =============================================================================
-- 3. CASE SOURCE / VERSION / EVENT + WORKFLOW METADATA (Group 4)
-- =============================================================================
CREATE TABLE IF NOT EXISTS "CaseSource" (
    "CaseSourceID"   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "CaseMasterID"   INTEGER NOT NULL REFERENCES "CaseMaster" ("CaseMasterID"),
    "SourceSystemID" INTEGER REFERENCES "SourceSystem" ("SourceSystemID"),
    "SourceRecordID" BIGINT REFERENCES "SourceRecord" ("SourceRecordID"),
    "ExternalRef"    VARCHAR,
    "IngestionMethod" VARCHAR,
    "CreatedAt"      TIMESTAMPTZ NOT NULL DEFAULT now()
);
COMMENT ON TABLE "CaseSource" IS 'Provenance of a case: which source system/record it originated from.';

CREATE TABLE IF NOT EXISTS "CaseVersion" (
    "CaseVersionID"    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "CaseMasterID"     INTEGER NOT NULL REFERENCES "CaseMaster" ("CaseMasterID"),
    "VersionNo"        INTEGER NOT NULL DEFAULT 1,
    "CaseCategoryCode" VARCHAR NOT NULL,        -- FIR|UDR|Zero FIR|PAR|NCR|Missing Person
    "StatusCode"       VARCHAR NOT NULL,        -- derived from events / validated
    "IsCurrent"        BOOLEAN NOT NULL DEFAULT TRUE,
    "IncidentLatitude"  NUMERIC(9,6) CHECK ("IncidentLatitude"  IS NULL OR "IncidentLatitude"  BETWEEN -90  AND 90),
    "IncidentLongitude" NUMERIC(9,6) CHECK ("IncidentLongitude" IS NULL OR "IncidentLongitude" BETWEEN -180 AND 180),
    "AssignedDistrictID" INTEGER REFERENCES "District" ("DistrictID"),
    "AssignedUnitID"     INTEGER REFERENCES "Unit" ("UnitID"),
    "geom" geometry(Point, 4326) GENERATED ALWAYS AS (
        CASE WHEN "IncidentLongitude" IS NOT NULL AND "IncidentLatitude" IS NOT NULL
             THEN ST_SetSRID(ST_MakePoint("IncidentLongitude", "IncidentLatitude"), 4326) END
    ) STORED,
    "SnapshotAttributes" JSONB NOT NULL DEFAULT '{}'::jsonb,
    "ChangeReason"     TEXT,
    "Actor"            VARCHAR,
    "ValidFrom"        TIMESTAMPTZ NOT NULL DEFAULT now(),
    "CreatedAt"        TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT "uq_caseversion" UNIQUE ("CaseMasterID", "VersionNo")
);
COMMENT ON TABLE "CaseVersion" IS 'Versioned canonical case snapshot incl. canonical incident coordinates (the spatial-containment source of truth). One IsCurrent per case.';

CREATE UNIQUE INDEX IF NOT EXISTS "uq_caseversion_current"
    ON "CaseVersion" ("CaseMasterID") WHERE "IsCurrent";

CREATE TABLE IF NOT EXISTS "CaseEvent" (
    "CaseEventID"   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "CaseMasterID"  INTEGER NOT NULL REFERENCES "CaseMaster" ("CaseMasterID"),
    "EventType"     VARCHAR NOT NULL,     -- registered|transferred|arrest|chargesheet_filed|court_assigned|missing_reported|traced|recovered|inquest|postmortem|converted|reopened|corrected|closed|disposition...
    "EventCategory" VARCHAR,               -- lifecycle|court|evidence|admin
    "SequenceNo"    INTEGER NOT NULL DEFAULT 1,
    "OccurredAt"    TIMESTAMPTZ,
    "RecordedAt"    TIMESTAMPTZ NOT NULL DEFAULT now(),
    "FromStatus"    VARCHAR,
    "ToStatus"      VARCHAR,
    "Payload"       JSONB NOT NULL DEFAULT '{}'::jsonb,
    "ActorRole"     VARCHAR,
    "Provenance"    JSONB NOT NULL DEFAULT '{}'::jsonb,
    "CreatedAt"     TIMESTAMPTZ NOT NULL DEFAULT now()
);
COMMENT ON TABLE "CaseEvent" IS 'Append-only case lifecycle events. Case status is derived from / validated against these, not set arbitrarily.';

CREATE TABLE IF NOT EXISTS "CaseCategoryWorkflow" (
    "CaseCategoryWorkflowID" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "CaseCategoryCode" VARCHAR NOT NULL,
    "EventType"        VARCHAR NOT NULL,
    "FromStatus"       VARCHAR,
    "ToStatus"         VARCHAR,
    "RequiresPriorEvent" VARCHAR,        -- prerequisite event type (e.g. chargesheet needs arrest OR investigation)
    "IsTerminal"       BOOLEAN NOT NULL DEFAULT FALSE,
    "Description"      TEXT,
    CONSTRAINT "uq_casecategoryworkflow" UNIQUE ("CaseCategoryCode", "EventType", "FromStatus", "ToStatus")
);
COMMENT ON TABLE "CaseCategoryWorkflow" IS 'Category-specific state-machine transitions AS DATA (seeded by datagen scenario_registry). Not hard-coded if-statements.';

-- =============================================================================
-- 4. EVIDENCE <-> ENTITY LINK (Group 5, needs CanonicalEntity)
-- =============================================================================
CREATE TABLE IF NOT EXISTS "EvidenceEntityLink" (
    "EvidenceEntityLinkID" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "EvidenceItemID"    BIGINT NOT NULL REFERENCES "EvidenceItem" ("EvidenceItemID") ON DELETE CASCADE,
    "CanonicalEntityID" BIGINT NOT NULL REFERENCES "CanonicalEntity" ("CanonicalEntityID"),
    "LinkType"      VARCHAR NOT NULL DEFAULT 'mentions',
    "Confidence"    NUMERIC(6,5) CHECK ("Confidence" IS NULL OR "Confidence" BETWEEN 0 AND 1),
    "ReviewStatus"  VARCHAR NOT NULL DEFAULT 'candidate',  -- candidate|reviewed|rejected
    "SourceRecordID" BIGINT REFERENCES "SourceRecord" ("SourceRecordID"),
    "CreatedAt"     TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT "uq_evidenceentitylink" UNIQUE ("EvidenceItemID", "CanonicalEntityID", "LinkType")
);
COMMENT ON TABLE "EvidenceEntityLink" IS 'Evidence-to-entity relationships with provenance + review state (feeds provenanced graph edges).';

-- =============================================================================
-- 5. STATEMENTS (Group 6)
-- =============================================================================
CREATE TABLE IF NOT EXISTS "Statement" (
    "StatementID"   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "CaseMasterID"  INTEGER NOT NULL REFERENCES "CaseMaster" ("CaseMasterID"),
    "CanonicalPersonID" BIGINT REFERENCES "CanonicalPerson" ("CanonicalPersonID"),
    "CasePartyRoleID" BIGINT REFERENCES "CasePartyRole" ("CasePartyRoleID"),
    "StatementType" VARCHAR NOT NULL DEFAULT 'witness',   -- witness|complainant|accused|expert
    "RecordedByActor" VARCHAR,
    "RecordedAt"    TIMESTAMPTZ,
    "Place"         VARCHAR,
    "Language"      VARCHAR DEFAULT 'en',
    "AccessClassification" VARCHAR NOT NULL DEFAULT 'demo_normal',  -- demo_normal|restricted
    "State"         VARCHAR NOT NULL DEFAULT 'recorded',  -- draft|recorded|reviewed
    "EvidenceItemID" BIGINT REFERENCES "EvidenceItem" ("EvidenceItemID"),
    "CreatedAt"     TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT "chk_statement_state" CHECK ("State" IN ('draft','recorded','reviewed'))
);
COMMENT ON TABLE "Statement" IS 'Typed statements/interviews. Speaker links to canonical person + case role. Manual entry only (no auto-transcription in hackathon).';

CREATE TABLE IF NOT EXISTS "StatementVersion" (
    "StatementVersionID" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "StatementID"    BIGINT NOT NULL REFERENCES "Statement" ("StatementID") ON DELETE CASCADE,
    "VersionNo"      INTEGER NOT NULL,
    "StatementText"  TEXT,
    "CorrectionReason" TEXT,
    "Translation"    TEXT,
    "Redacted"       BOOLEAN NOT NULL DEFAULT FALSE,
    "CreatedByActor" VARCHAR,
    "CreatedAt"      TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT "uq_statementversion" UNIQUE ("StatementID", "VersionNo")
);
COMMENT ON TABLE "StatementVersion" IS 'Append-only statement version history (correction/translation/redaction).';

-- =============================================================================
-- 6. PROPERTY / SEIZURE (Group 7)
-- =============================================================================
CREATE TABLE IF NOT EXISTS "Seizure" (
    "SeizureID"    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "CaseMasterID" INTEGER NOT NULL REFERENCES "CaseMaster" ("CaseMasterID"),
    "CaseEventID"  BIGINT REFERENCES "CaseEvent" ("CaseEventID"),
    "SeizureType"  VARCHAR NOT NULL DEFAULT 'seizure',
    "SeizedAt"     TIMESTAMPTZ,
    "Place"        VARCHAR,
    "MemoEvidenceItemID" BIGINT REFERENCES "EvidenceItem" ("EvidenceItemID"),
    "Actor"        VARCHAR,
    "CreatedAt"    TIMESTAMPTZ NOT NULL DEFAULT now()
);
COMMENT ON TABLE "Seizure" IS 'Seizure events with an optional seizure-memo evidence item.';

CREATE TABLE IF NOT EXISTS "PropertyItem" (
    "PropertyItemID" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "SeizureID"      BIGINT REFERENCES "Seizure" ("SeizureID"),
    "CaseMasterID"   INTEGER NOT NULL REFERENCES "CaseMaster" ("CaseMasterID"),
    "ItemType"       VARCHAR NOT NULL DEFAULT 'property',  -- property|vehicle|weapon|substance|document
    "SyntheticIdentifier" VARCHAR,          -- synthetic serial/registration token
    "Description"    VARCHAR,
    "Quantity"       NUMERIC,
    "Unit"           VARCHAR,
    "EstimatedValue" NUMERIC(14,2),
    "OwnerCanonicalPersonID" BIGINT REFERENCES "CanonicalPerson" ("CanonicalPersonID"),
    "Status"         VARCHAR NOT NULL DEFAULT 'seized',    -- seized|recovered|returned|disposed
    "VehicleFields"  JSONB NOT NULL DEFAULT '{}'::jsonb,   -- reg/chassis/engine synthetic tokens
    "WeaponFields"   JSONB NOT NULL DEFAULT '{}'::jsonb,
    "CreatedAt"      TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT "chk_propertyitem_type" CHECK ("ItemType" IN
        ('property','vehicle','weapon','substance','document')),
    CONSTRAINT "chk_propertyitem_status" CHECK ("Status" IN
        ('seized','recovered','returned','disposed'))
);
COMMENT ON TABLE "PropertyItem" IS 'Property/vehicle/weapon/substance metadata (entered via forms). Vehicle/weapon-specific fields in typed JSONB.';

-- =============================================================================
-- 7. DIGITAL (Group 8)
-- =============================================================================
CREATE TABLE IF NOT EXISTS "Device" (
    "DeviceID"     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "CanonicalEntityID" BIGINT REFERENCES "CanonicalEntity" ("CanonicalEntityID"),
    "CaseMasterID" INTEGER REFERENCES "CaseMaster" ("CaseMasterID"),
    "DeviceType"   VARCHAR NOT NULL DEFAULT 'mobile',
    "SyntheticIdentifier" VARCHAR,          -- synthetic IMEI/serial
    "Label"        VARCHAR,
    "SourceRecordID" BIGINT REFERENCES "SourceRecord" ("SourceRecordID"),
    "CreatedAt"    TIMESTAMPTZ NOT NULL DEFAULT now()
);
COMMENT ON TABLE "Device" IS 'Synthetic devices linked to canonical entities/cases.';

CREATE TABLE IF NOT EXISTS "DeviceArtifact" (
    "DeviceArtifactID" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "DeviceID"     BIGINT NOT NULL REFERENCES "Device" ("DeviceID") ON DELETE CASCADE,
    "ArtifactType" VARCHAR NOT NULL DEFAULT 'chat',
    "SyntheticReference" VARCHAR,
    "Detail"       JSONB NOT NULL DEFAULT '{}'::jsonb,
    "EvidenceItemID" BIGINT REFERENCES "EvidenceItem" ("EvidenceItemID"),
    "CreatedAt"    TIMESTAMPTZ NOT NULL DEFAULT now()
);
COMMENT ON TABLE "DeviceArtifact" IS 'Artifacts extracted-by-hand from a device export (chat/app/media reference metadata).';

CREATE TABLE IF NOT EXISTS "CommunicationEvent" (
    "CommunicationEventID" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "CaseMasterID" INTEGER REFERENCES "CaseMaster" ("CaseMasterID"),
    "FromCanonicalEntityID" BIGINT REFERENCES "CanonicalEntity" ("CanonicalEntityID"),
    "ToCanonicalEntityID"   BIGINT REFERENCES "CanonicalEntity" ("CanonicalEntityID"),
    "CommType"     VARCHAR NOT NULL DEFAULT 'call',   -- call|sms|chat|ip
    "OccurredAt"   TIMESTAMPTZ,
    "DurationSec"  INTEGER,
    "SyntheticEndpointA" VARCHAR,
    "SyntheticEndpointB" VARCHAR,
    "ReviewStatus" VARCHAR NOT NULL DEFAULT 'candidate',
    "SourceRecordID" BIGINT REFERENCES "SourceRecord" ("SourceRecordID"),
    "CreatedAt"    TIMESTAMPTZ NOT NULL DEFAULT now()
);
COMMENT ON TABLE "CommunicationEvent" IS 'Synthetic CDR/chat/IP communication events between canonical entities (aggregate/reviewed use only).';

CREATE TABLE IF NOT EXISTS "LocationObservation" (
    "LocationObservationID" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "CanonicalEntityID" BIGINT REFERENCES "CanonicalEntity" ("CanonicalEntityID"),
    "CaseMasterID" INTEGER REFERENCES "CaseMaster" ("CaseMasterID"),
    "ObservedAt"   TIMESTAMPTZ,
    "geom"         geometry(Point, 4326),
    "DistrictID"   INTEGER REFERENCES "District" ("DistrictID"),
    "Source"       VARCHAR,
    "SourceRecordID" BIGINT REFERENCES "SourceRecord" ("SourceRecordID"),
    "CreatedAt"    TIMESTAMPTZ NOT NULL DEFAULT now()
);
COMMENT ON TABLE "LocationObservation" IS 'Synthetic GPS/location observations (validated against jurisdiction; on real KA land).';

CREATE TABLE IF NOT EXISTS "DigitalImportBatch" (
    "DigitalImportBatchID" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "IngestionJobID" BIGINT REFERENCES "IngestionJob" ("IngestionJobID"),
    "BatchKind"    VARCHAR NOT NULL DEFAULT 'cdr',
    "RowCount"     INTEGER,
    "DryRun"       BOOLEAN NOT NULL DEFAULT FALSE,
    "Status"       VARCHAR NOT NULL DEFAULT 'staged',
    "CreatedAt"    TIMESTAMPTZ NOT NULL DEFAULT now()
);
COMMENT ON TABLE "DigitalImportBatch" IS 'A batch of digital import rows (CDR/chat/location) tied to an ingestion job.';

-- =============================================================================
-- 8. COURT / OUTCOMES (Group 9)
-- =============================================================================
CREATE TABLE IF NOT EXISTS "CourtEvent" (
    "CourtEventID" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "CaseMasterID" INTEGER NOT NULL REFERENCES "CaseMaster" ("CaseMasterID"),
    "CourtID"      INTEGER REFERENCES "Court" ("CourtID"),
    "EventType"    VARCHAR NOT NULL,   -- chargesheet_filed|hearing|remand|framing_of_charges|judgment|adjournment
    "ScheduledAt"  TIMESTAMPTZ,
    "OccurredAt"   TIMESTAMPTZ,
    "Outcome"      VARCHAR,
    "Detail"       JSONB NOT NULL DEFAULT '{}'::jsonb,
    "CreatedAt"    TIMESTAMPTZ NOT NULL DEFAULT now()
);
COMMENT ON TABLE "CourtEvent" IS 'Court proceedings for a case (append-only). Court assignment is an event/result, not a mandatory generated field.';

CREATE TABLE IF NOT EXISTS "BailEvent" (
    "BailEventID"  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "CaseMasterID" INTEGER NOT NULL REFERENCES "CaseMaster" ("CaseMasterID"),
    "CanonicalPersonID" BIGINT REFERENCES "CanonicalPerson" ("CanonicalPersonID"),
    "BailType"     VARCHAR,
    "Status"       VARCHAR NOT NULL DEFAULT 'pending',   -- granted|rejected|pending
    "DecidedAt"    TIMESTAMPTZ,
    "CourtID"      INTEGER REFERENCES "Court" ("CourtID"),
    "Detail"       JSONB NOT NULL DEFAULT '{}'::jsonb,
    "CreatedAt"    TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT "chk_bail_status" CHECK ("Status" IN ('granted','rejected','pending'))
);
COMMENT ON TABLE "BailEvent" IS 'Bail decisions for accused persons (investigation-support metadata only).';

CREATE TABLE IF NOT EXISTS "CaseDisposition" (
    "CaseDispositionID" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "CaseMasterID"   INTEGER NOT NULL REFERENCES "CaseMaster" ("CaseMasterID"),
    "DispositionType" VARCHAR NOT NULL,  -- convicted|acquitted|closed_b_report|closed_c_report|transferred|pending
    "DispositionDate" TIMESTAMPTZ,
    "CourtEventID"   BIGINT REFERENCES "CourtEvent" ("CourtEventID"),
    "IsFinal"        BOOLEAN NOT NULL DEFAULT FALSE,
    "Detail"         JSONB NOT NULL DEFAULT '{}'::jsonb,
    "CreatedAt"      TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT "chk_disposition_type" CHECK ("DispositionType" IN
        ('convicted','acquitted','closed_b_report','closed_c_report','transferred','pending','withdrawn'))
);
COMMENT ON TABLE "CaseDisposition" IS 'Final/interim case disposition, tied to the court event that produced it.';

CREATE TABLE IF NOT EXISTS "OutcomeObservation" (
    "OutcomeObservationID" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "CaseMasterID"   INTEGER NOT NULL REFERENCES "CaseMaster" ("CaseMasterID"),
    "ObservationType" VARCHAR NOT NULL DEFAULT 'case_outcome',
    "ObservedAt"     TIMESTAMPTZ NOT NULL,        -- must be >= observation cutoff (label window)
    "ObservationWindowStart" TIMESTAMPTZ,
    "ObservationWindowEnd"   TIMESTAMPTZ,
    "Verified"       BOOLEAN NOT NULL DEFAULT TRUE,
    "SourceEventID"  BIGINT REFERENCES "CaseEvent" ("CaseEventID"),
    "Detail"         JSONB NOT NULL DEFAULT '{}'::jsonb,
    "CreatedAt"      TIMESTAMPTZ NOT NULL DEFAULT now()
);
COMMENT ON TABLE "OutcomeObservation" IS 'Verified outcome events observed after a separate label window. The ONLY safe basis for training labels (no feature leakage).';

-- =============================================================================
-- 9. BACKWARD-COMPATIBLE CANONICAL COLUMNS ON LEGACY TABLES (additive)
-- =============================================================================
ALTER TABLE "Accused"            ADD COLUMN IF NOT EXISTS "CanonicalPersonID" BIGINT REFERENCES "CanonicalPerson" ("CanonicalPersonID");
ALTER TABLE "Accused"            ADD COLUMN IF NOT EXISTS "CasePartyRoleID"  BIGINT REFERENCES "CasePartyRole" ("CasePartyRoleID");
ALTER TABLE "Victim"             ADD COLUMN IF NOT EXISTS "CanonicalPersonID" BIGINT REFERENCES "CanonicalPerson" ("CanonicalPersonID");
ALTER TABLE "ComplainantDetails" ADD COLUMN IF NOT EXISTS "CanonicalPersonID" BIGINT REFERENCES "CanonicalPerson" ("CanonicalPersonID");
ALTER TABLE "EntityGraph"        ADD COLUMN IF NOT EXISTS "CanonicalEntityID" BIGINT REFERENCES "CanonicalEntity" ("CanonicalEntityID");
ALTER TABLE "GangMembership"     ADD COLUMN IF NOT EXISTS "MemberCanonicalPersonID" BIGINT REFERENCES "CanonicalPerson" ("CanonicalPersonID");
-- Edge provenance/verification (audit found all NetworkEdge.EvidenceCaseID null).
ALTER TABLE "NetworkEdge"        ADD COLUMN IF NOT EXISTS "SourceRecordID" BIGINT REFERENCES "SourceRecord" ("SourceRecordID");
ALTER TABLE "NetworkEdge"        ADD COLUMN IF NOT EXISTS "EvidenceEntityLinkID" BIGINT REFERENCES "EvidenceEntityLink" ("EvidenceEntityLinkID");
ALTER TABLE "NetworkEdge"        ADD COLUMN IF NOT EXISTS "ProvenanceStatus" VARCHAR;  -- verified|synthetic_unverified

-- =============================================================================
-- 10. INDEXES
-- =============================================================================
CREATE INDEX IF NOT EXISTS "idx_canonperson_mergedinto"  ON "CanonicalPerson" ("MergedIntoCanonicalPersonID");
CREATE INDEX IF NOT EXISTS "idx_canonentity_person"      ON "CanonicalEntity" ("CanonicalPersonID");
CREATE INDEX IF NOT EXISTS "idx_canonentity_org"         ON "CanonicalEntity" ("CanonicalOrganisationID");
CREATE INDEX IF NOT EXISTS "idx_personalias_person"      ON "PersonAlias" ("CanonicalPersonID");
CREATE INDEX IF NOT EXISTS "gin_personalias_name_trgm"   ON "PersonAlias" USING GIN ("AliasName" gin_trgm_ops);
CREATE INDEX IF NOT EXISTS "idx_personidentifier_person" ON "PersonIdentifier" ("CanonicalPersonID");
CREATE INDEX IF NOT EXISTS "idx_personcontact_person"    ON "PersonContact" ("CanonicalPersonID");
CREATE INDEX IF NOT EXISTS "idx_personaddress_person"    ON "PersonAddress" ("CanonicalPersonID");
CREATE INDEX IF NOT EXISTS "gist_personaddress_geom"     ON "PersonAddress" USING GIST ("geom");
CREATE INDEX IF NOT EXISTS "idx_erc_a"                   ON "EntityResolutionCandidate" ("CanonicalPersonA");
CREATE INDEX IF NOT EXISTS "idx_erc_b"                   ON "EntityResolutionCandidate" ("CanonicalPersonB");
CREATE INDEX IF NOT EXISTS "idx_erc_status"              ON "EntityResolutionCandidate" ("Status");
CREATE INDEX IF NOT EXISTS "idx_casepartyrole_case"      ON "CasePartyRole" ("CaseMasterID");
CREATE INDEX IF NOT EXISTS "idx_casepartyrole_person"    ON "CasePartyRole" ("CanonicalPersonID");
CREATE INDEX IF NOT EXISTS "idx_casepartyrole_role"      ON "CasePartyRole" ("RoleType");
CREATE INDEX IF NOT EXISTS "idx_casepartyrole_legacy"    ON "CasePartyRole" ("LegacyRefTable", "LegacyRefID");
CREATE INDEX IF NOT EXISTS "idx_casesource_case"         ON "CaseSource" ("CaseMasterID");
CREATE INDEX IF NOT EXISTS "idx_caseversion_case"        ON "CaseVersion" ("CaseMasterID");
CREATE INDEX IF NOT EXISTS "gist_caseversion_geom"       ON "CaseVersion" USING GIST ("geom");
CREATE INDEX IF NOT EXISTS "idx_caseevent_case"          ON "CaseEvent" ("CaseMasterID");
CREATE INDEX IF NOT EXISTS "idx_caseevent_type"          ON "CaseEvent" ("EventType");
CREATE INDEX IF NOT EXISTS "idx_caseevent_case_seq"      ON "CaseEvent" ("CaseMasterID", "SequenceNo");
CREATE INDEX IF NOT EXISTS "idx_evidenceentitylink_ent"  ON "EvidenceEntityLink" ("CanonicalEntityID");
CREATE INDEX IF NOT EXISTS "idx_statement_case"          ON "Statement" ("CaseMasterID");
CREATE INDEX IF NOT EXISTS "idx_statement_person"        ON "Statement" ("CanonicalPersonID");
CREATE INDEX IF NOT EXISTS "idx_statementversion_stmt"   ON "StatementVersion" ("StatementID");
CREATE INDEX IF NOT EXISTS "idx_seizure_case"            ON "Seizure" ("CaseMasterID");
CREATE INDEX IF NOT EXISTS "idx_propertyitem_case"       ON "PropertyItem" ("CaseMasterID");
CREATE INDEX IF NOT EXISTS "idx_propertyitem_seizure"    ON "PropertyItem" ("SeizureID");
CREATE INDEX IF NOT EXISTS "idx_device_entity"           ON "Device" ("CanonicalEntityID");
CREATE INDEX IF NOT EXISTS "idx_deviceartifact_device"   ON "DeviceArtifact" ("DeviceID");
CREATE INDEX IF NOT EXISTS "idx_commevent_case"          ON "CommunicationEvent" ("CaseMasterID");
CREATE INDEX IF NOT EXISTS "idx_commevent_from"          ON "CommunicationEvent" ("FromCanonicalEntityID");
CREATE INDEX IF NOT EXISTS "idx_commevent_to"            ON "CommunicationEvent" ("ToCanonicalEntityID");
CREATE INDEX IF NOT EXISTS "idx_locationobs_entity"      ON "LocationObservation" ("CanonicalEntityID");
CREATE INDEX IF NOT EXISTS "gist_locationobs_geom"       ON "LocationObservation" USING GIST ("geom");
CREATE INDEX IF NOT EXISTS "idx_courtevent_case"         ON "CourtEvent" ("CaseMasterID");
CREATE INDEX IF NOT EXISTS "idx_bailevent_case"          ON "BailEvent" ("CaseMasterID");
CREATE INDEX IF NOT EXISTS "idx_disposition_case"        ON "CaseDisposition" ("CaseMasterID");
CREATE INDEX IF NOT EXISTS "idx_outcomeobs_case"         ON "OutcomeObservation" ("CaseMasterID");
CREATE INDEX IF NOT EXISTS "idx_accused_canonperson"     ON "Accused" ("CanonicalPersonID");
CREATE INDEX IF NOT EXISTS "idx_victim_canonperson"      ON "Victim" ("CanonicalPersonID");
CREATE INDEX IF NOT EXISTS "idx_complainant_canonperson" ON "ComplainantDetails" ("CanonicalPersonID");
CREATE INDEX IF NOT EXISTS "idx_entitygraph_canonentity" ON "EntityGraph" ("CanonicalEntityID");
CREATE INDEX IF NOT EXISTS "idx_networkedge_sourcerec"   ON "NetworkEdge" ("SourceRecordID");

-- =============================================================================
-- 11. TRIGGERS + backward-compatible view
-- =============================================================================
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_trigger WHERE tgname = 'trg_canonperson_updated') THEN
        CREATE TRIGGER "trg_canonperson_updated" BEFORE UPDATE ON "CanonicalPerson"
            FOR EACH ROW EXECUTE FUNCTION fn_set_updated_at();
    END IF;
END$$;

-- Resolved case parties via canonical identity (no name joins).
CREATE OR REPLACE VIEW "vw_case_parties" AS
SELECT
    r."CasePartyRoleID",
    r."CaseMasterID",
    cm."CrimeNo",
    r."RoleType",
    r."IsUnknownParty",
    p."CanonicalPersonID",
    p."PublicRef"     AS "PersonRef",
    p."DisplayLabel"  AS "PersonLabel",
    o."CanonicalOrganisationID",
    o."PublicRef"     AS "OrgRef"
FROM "CasePartyRole" r
LEFT JOIN "CaseMaster" cm ON cm."CaseMasterID" = r."CaseMasterID"
LEFT JOIN "CanonicalPerson" p ON p."CanonicalPersonID" = r."CanonicalPersonID"
LEFT JOIN "CanonicalOrganisation" o ON o."CanonicalOrganisationID" = r."CanonicalOrganisationID";
COMMENT ON VIEW "vw_case_parties" IS 'Case parties resolved through canonical identity (replaces name/A1-A2 based joins).';

-- =============================================================================
-- 12. Grants + RLS disabled/NO FORCE + global verification (hackathon).
-- =============================================================================
DO $$
DECLARE t TEXT;
BEGIN
    IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'drishti_readonly') THEN
        FOREACH t IN ARRAY ARRAY[
            'CanonicalPerson','CanonicalOrganisation','CanonicalEntity','PersonAlias',
            'PersonIdentifier','PersonContact','PersonAddress','EntityResolutionCandidate',
            'EntityMergeHistory','CasePartyRole','CaseSource','CaseVersion','CaseEvent',
            'CaseCategoryWorkflow','EvidenceEntityLink','Statement','StatementVersion',
            'Seizure','PropertyItem','Device','DeviceArtifact','CommunicationEvent',
            'LocationObservation','DigitalImportBatch','CourtEvent','BailEvent',
            'CaseDisposition','OutcomeObservation'
        ] LOOP
            EXECUTE format('GRANT SELECT ON %I TO drishti_readonly', t);
        END LOOP;
        GRANT SELECT ON "vw_case_parties" TO drishti_readonly;
    END IF;
END$$;

SELECT fn_disable_rls_all_app();
SELECT fn_assert_rls_disabled();

COMMIT;

-- =============================================================================
-- End of migration 007.
-- =============================================================================
