-- =============================================================================
-- DRISHTI migration 009 — versioned jurisdiction geography + approved external
--                          context (weather/holiday/event/area)
-- Target: PostgreSQL 15+ / Supabase (live PG 17.6)
-- Depends on: 005, 006, 007, 008
-- =============================================================================
--
-- Persists state/district/unit/beat/SHO boundaries and station coordinates so
-- the DATABASE can enforce spatial containment (the audit found no jurisdiction
-- polygons persisted). Boundaries are versioned with validity periods + source
-- metadata. Adds approved external-context source versions (weather/holiday/
-- event/area) that models may consume as covariates.
--
-- Full spatial repair/regeneration + the intake location picker come in Phase 9;
-- here we provide the storage, indexes, containment helpers and the data the
-- Datagen v2 generator validates against.
--
-- RLS stays DISABLED + NO FORCE (hackathon). No RLS policies. Additive +
-- idempotent.
-- =============================================================================

BEGIN;

-- =============================================================================
-- 1. VERSIONED JURISDICTION BOUNDARIES (Group 10)
-- =============================================================================
CREATE TABLE IF NOT EXISTS "JurisdictionBoundary" (
    "JurisdictionBoundaryID" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "Level"       VARCHAR NOT NULL,               -- state|district|unit|beat|sho
    "Name"        VARCHAR NOT NULL,
    "StateID"     INTEGER REFERENCES "State" ("StateID"),
    "DistrictID"  INTEGER REFERENCES "District" ("DistrictID"),
    "UnitID"      INTEGER REFERENCES "Unit" ("UnitID"),
    "geom"        geometry(Geometry, 4326) NOT NULL,   -- polygon/multipolygon
    "Version"     INTEGER NOT NULL DEFAULT 1,
    "IsCurrent"   BOOLEAN NOT NULL DEFAULT TRUE,
    "ValidFrom"   TIMESTAMPTZ NOT NULL DEFAULT now(),
    "ValidTo"     TIMESTAMPTZ,
    "Source"      VARCHAR,                         -- e.g. datagen/geo KGIS-simplified
    "IsSynthetic" BOOLEAN NOT NULL DEFAULT TRUE,
    "CreatedAt"   TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT "chk_jurisdiction_level" CHECK ("Level" IN ('state','district','unit','beat','sho'))
);
COMMENT ON TABLE "JurisdictionBoundary" IS 'Versioned state/district/unit/beat/SHO boundary polygons enabling DB-level spatial containment checks.';

CREATE TABLE IF NOT EXISTS "UnitLocation" (
    "UnitLocationID" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "UnitID"      INTEGER NOT NULL REFERENCES "Unit" ("UnitID"),
    "geom"        geometry(Point, 4326) NOT NULL,
    "Taluk"       VARCHAR,
    "Version"     INTEGER NOT NULL DEFAULT 1,
    "IsCurrent"   BOOLEAN NOT NULL DEFAULT TRUE,
    "ValidFrom"   TIMESTAMPTZ NOT NULL DEFAULT now(),
    "ValidTo"     TIMESTAMPTZ,
    "Source"      VARCHAR,
    "CreatedAt"   TIMESTAMPTZ NOT NULL DEFAULT now()
);
COMMENT ON TABLE "UnitLocation" IS 'Versioned police-unit/station coordinates on the real Karnataka landmass.';

-- =============================================================================
-- 2. APPROVED EXTERNAL CONTEXT (Group covered by 009 mapping)
-- =============================================================================
CREATE TABLE IF NOT EXISTS "ExternalSourceVersion" (
    "ExternalSourceVersionID" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "SourceKind"  VARCHAR NOT NULL,               -- weather|holiday|event|area
    "Provider"    VARCHAR,
    "Version"     VARCHAR NOT NULL,
    "ApprovedByActor" VARCHAR,
    "ValidFrom"   TIMESTAMPTZ,
    "ValidTo"     TIMESTAMPTZ,
    "Detail"      JSONB NOT NULL DEFAULT '{}'::jsonb,
    "IsSynthetic" BOOLEAN NOT NULL DEFAULT TRUE,
    "CreatedAt"   TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT "chk_extsource_kind" CHECK ("SourceKind" IN ('weather','holiday','event','area')),
    CONSTRAINT "uq_extsource" UNIQUE ("SourceKind", "Provider", "Version")
);
COMMENT ON TABLE "ExternalSourceVersion" IS 'Approved, versioned external context sources (weather/holiday/event/area) usable as model covariates.';

CREATE TABLE IF NOT EXISTS "HolidayCalendar" (
    "HolidayCalendarID" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "ObservedDate" DATE NOT NULL,
    "Name"        VARCHAR NOT NULL,
    "Region"      VARCHAR,
    "ExternalSourceVersionID" BIGINT REFERENCES "ExternalSourceVersion" ("ExternalSourceVersionID"),
    "CreatedAt"   TIMESTAMPTZ NOT NULL DEFAULT now()
);
COMMENT ON TABLE "HolidayCalendar" IS 'Approved holiday dates (covariate for aggregate forecasting).';

CREATE TABLE IF NOT EXISTS "PublicEvent" (
    "PublicEventID" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "EventName"   VARCHAR NOT NULL,
    "StartAt"     TIMESTAMPTZ,
    "EndAt"       TIMESTAMPTZ,
    "DistrictID"  INTEGER REFERENCES "District" ("DistrictID"),
    "geom"        geometry(Point, 4326),
    "ExternalSourceVersionID" BIGINT REFERENCES "ExternalSourceVersion" ("ExternalSourceVersionID"),
    "CreatedAt"   TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT "chk_publicevent_window" CHECK ("EndAt" IS NULL OR "StartAt" IS NULL OR "EndAt" >= "StartAt")
);
COMMENT ON TABLE "PublicEvent" IS 'Approved public events (festivals/elections/gatherings) as area/time covariates.';

CREATE TABLE IF NOT EXISTS "AreaContextObservation" (
    "AreaContextObservationID" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "DistrictID"  INTEGER REFERENCES "District" ("DistrictID"),
    "UnitID"      INTEGER REFERENCES "Unit" ("UnitID"),
    "ObservedDate" DATE NOT NULL,
    "Metrics"     JSONB NOT NULL DEFAULT '{}'::jsonb,
    "ExternalSourceVersionID" BIGINT REFERENCES "ExternalSourceVersion" ("ExternalSourceVersionID"),
    "geom"        geometry(Geometry, 4326),
    "CreatedAt"   TIMESTAMPTZ NOT NULL DEFAULT now()
);
COMMENT ON TABLE "AreaContextObservation" IS 'Approved per-area/time context observations (e.g. weather/economic covariates) tied to a source version.';

-- =============================================================================
-- 3. CONTAINMENT HELPERS (functions + view)
--    Used by validation + Phase 9. Return FALSE safely when no boundary exists.
-- =============================================================================
CREATE OR REPLACE FUNCTION fn_point_in_state(p_lon DOUBLE PRECISION, p_lat DOUBLE PRECISION)
RETURNS BOOLEAN
LANGUAGE sql
STABLE
AS $$
    SELECT COALESCE(bool_or(ST_Contains(b."geom",
              ST_SetSRID(ST_MakePoint(p_lon, p_lat), 4326))), FALSE)
    FROM "JurisdictionBoundary" b
    WHERE b."Level" = 'state' AND b."IsCurrent";
$$;
COMMENT ON FUNCTION fn_point_in_state(DOUBLE PRECISION, DOUBLE PRECISION) IS
    'TRUE if the point lies inside the current state boundary. FALSE if outside or no boundary loaded.';

CREATE OR REPLACE FUNCTION fn_point_in_district(p_district_id INTEGER,
                                                p_lon DOUBLE PRECISION,
                                                p_lat DOUBLE PRECISION)
RETURNS BOOLEAN
LANGUAGE sql
STABLE
AS $$
    SELECT COALESCE(bool_or(ST_Contains(b."geom",
              ST_SetSRID(ST_MakePoint(p_lon, p_lat), 4326))), FALSE)
    FROM "JurisdictionBoundary" b
    WHERE b."Level" = 'district' AND b."IsCurrent"
      AND b."DistrictID" = p_district_id;
$$;
COMMENT ON FUNCTION fn_point_in_district(INTEGER, DOUBLE PRECISION, DOUBLE PRECISION) IS
    'TRUE if the point lies inside the given district boundary (current version).';

-- Canonical incident coordinates joined to their state/district containment.
CREATE OR REPLACE VIEW "vw_caseversion_containment" AS
SELECT
    cv."CaseVersionID",
    cv."CaseMasterID",
    cv."AssignedDistrictID",
    cv."IncidentLongitude",
    cv."IncidentLatitude",
    fn_point_in_state(cv."IncidentLongitude"::double precision,
                      cv."IncidentLatitude"::double precision)  AS "InState",
    fn_point_in_district(cv."AssignedDistrictID",
                         cv."IncidentLongitude"::double precision,
                         cv."IncidentLatitude"::double precision) AS "InAssignedDistrict"
FROM "CaseVersion" cv
WHERE cv."IsCurrent"
  AND cv."IncidentLatitude" IS NOT NULL
  AND cv."IncidentLongitude" IS NOT NULL;
COMMENT ON VIEW "vw_caseversion_containment" IS
    'Per-current-CaseVersion spatial containment against state + assigned district (canonical coordinates).';

-- =============================================================================
-- 4. INDEXES
-- =============================================================================
CREATE INDEX IF NOT EXISTS "gist_jurisdiction_geom"   ON "JurisdictionBoundary" USING GIST ("geom");
CREATE INDEX IF NOT EXISTS "idx_jurisdiction_level"   ON "JurisdictionBoundary" ("Level");
CREATE INDEX IF NOT EXISTS "idx_jurisdiction_district" ON "JurisdictionBoundary" ("DistrictID");
CREATE INDEX IF NOT EXISTS "idx_jurisdiction_unit"    ON "JurisdictionBoundary" ("UnitID");
CREATE INDEX IF NOT EXISTS "idx_jurisdiction_current" ON "JurisdictionBoundary" ("IsCurrent");
CREATE INDEX IF NOT EXISTS "gist_unitlocation_geom"   ON "UnitLocation" USING GIST ("geom");
CREATE INDEX IF NOT EXISTS "idx_unitlocation_unit"    ON "UnitLocation" ("UnitID");
CREATE INDEX IF NOT EXISTS "idx_holiday_date"         ON "HolidayCalendar" ("ObservedDate");
CREATE INDEX IF NOT EXISTS "idx_publicevent_district" ON "PublicEvent" ("DistrictID");
CREATE INDEX IF NOT EXISTS "idx_areacontext_district" ON "AreaContextObservation" ("DistrictID");
CREATE INDEX IF NOT EXISTS "idx_areacontext_date"     ON "AreaContextObservation" ("ObservedDate");

-- =============================================================================
-- 5. Grants + RLS disabled/NO FORCE + FINAL global verification (hackathon).
-- =============================================================================
DO $$
DECLARE t TEXT;
BEGIN
    IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'drishti_readonly') THEN
        FOREACH t IN ARRAY ARRAY[
            'JurisdictionBoundary','UnitLocation','ExternalSourceVersion',
            'HolidayCalendar','PublicEvent','AreaContextObservation'
        ] LOOP
            EXECUTE format('GRANT SELECT ON %I TO drishti_readonly', t);
        END LOOP;
        GRANT SELECT ON "vw_caseversion_containment" TO drishti_readonly;
    END IF;
END$$;

-- Final hackathon-mode verification across ALL application tables (005-009).
SELECT fn_disable_rls_all_app();
SELECT fn_assert_rls_disabled();

COMMIT;

-- =============================================================================
-- End of migration 009.
-- =============================================================================
