-- =============================================================================
-- DRISHTI migration 010 — FIR/case intake drafts, draft parties, and the
--                          intake activity/review trail (Phase 2)
-- Target: PostgreSQL 15+ / Supabase (live PG 17.6)
-- Depends on: 005_security_rls_audit.sql, 006_ingestion_evidence.sql,
--             007_identity_case_workflow.sql
-- =============================================================================
--
-- Phase 2 adds the contextual FIR/case intake workflow. A draft is captured in
-- STAGING (never in canonical tables) as an IntakeDraft backed by a SourceRecord
-- + IngestionJob (provenance + idempotent retry). Draft parties are held in
-- IntakeDraftParty until approval, when the intake service canonicalises them
-- into CanonicalPerson/CanonicalOrganisation + CasePartyRole and creates the
-- CaseMaster/CaseSource/CaseVersion/CaseEvent rows in one transaction.
--
-- The draft lifecycle is an explicit state machine:
--   draft -> submitted -> under_review -> approved
--                                      -> rejected
--                                      -> returned_for_correction -> draft ...
--
-- Nothing here relaxes the hackathon posture: RLS stays DISABLED + NO FORCE and
-- the global RLS-disabled verification runs at the end. Additive + idempotent:
-- safe to run repeatedly. No canonical/operational data is dropped or mutated.
-- =============================================================================

BEGIN;

-- =============================================================================
-- 1. Seed the intake source systems (idempotent). The datagen loader may have
--    inserted these already; ON CONFLICT keeps this repeatable on a fresh DB.
--    Kind values must satisfy 006's chk_sourcesystem_kind.
-- =============================================================================
INSERT INTO "SourceSystem" ("Code", "Name", "Kind", "Description") VALUES
    ('FIR_FORM',    'Guided FIR/case intake form', 'manual_form',
        'React FIR wizard — structured manual entry (Phase 2).'),
    ('CSV_IMPORT',  'CSV bulk case import',        'csv_import',
        'Structured CSV import with dry-run + commit review (Phase 2).'),
    ('JSON_IMPORT', 'JSON bulk case import',       'json_import',
        'Structured JSON import with dry-run + commit review (Phase 2).')
ON CONFLICT ("Code") DO NOTHING;

-- =============================================================================
-- 2. INTAKE DRAFT — a staged, versioned FIR/case submission awaiting review.
-- =============================================================================
CREATE TABLE IF NOT EXISTS "IntakeDraft" (
    "IntakeDraftID"   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "DraftKey"        VARCHAR NOT NULL UNIQUE,          -- client-facing stable id (used in URLs)
    "IdempotencyKey"  VARCHAR UNIQUE,                    -- safe create retry (one draft per key)
    "SourceSystemID"  INTEGER REFERENCES "SourceSystem" ("SourceSystemID"),
    "SourceRecordID"  BIGINT  REFERENCES "SourceRecord" ("SourceRecordID"),
    "IngestionJobID"  BIGINT  REFERENCES "IngestionJob" ("IngestionJobID"),
    "CaseKind"        VARCHAR NOT NULL DEFAULT 'fir_standard',  -- fir_standard|zero_fir|udr|ncr|par|missing_person
    "CaseCategoryCode" VARCHAR NOT NULL DEFAULT 'FIR',          -- FIR|Zero FIR|UDR|NCR|PAR
    "Status"          VARCHAR NOT NULL DEFAULT 'draft',
    "Payload"         JSONB   NOT NULL DEFAULT '{}'::jsonb,     -- all wizard step fields (staging)
    "ValidationState" JSONB   NOT NULL DEFAULT '{}'::jsonb,     -- {ok,errors[],warnings[],validated_at}
    "CaseMasterID"    INTEGER REFERENCES "CaseMaster" ("CaseMasterID"),  -- set on approval
    "CreatedByActor"  VARCHAR,                            -- demo actor (UX simulation, NOT auth)
    "SubmittedByActor" VARCHAR,
    "ReviewedByActor" VARCHAR,
    "ReviewNote"      TEXT,
    "ReturnReason"    TEXT,
    "RevisionNo"      INTEGER NOT NULL DEFAULT 0,          -- autosave / optimistic-concurrency counter
    "IsSynthetic"     BOOLEAN NOT NULL DEFAULT TRUE,
    "CreatedAt"       TIMESTAMPTZ NOT NULL DEFAULT now(),
    "UpdatedAt"       TIMESTAMPTZ NOT NULL DEFAULT now(),
    "SubmittedAt"     TIMESTAMPTZ,
    "ReviewedAt"      TIMESTAMPTZ,
    CONSTRAINT "chk_intakedraft_status" CHECK ("Status" IN
        ('draft','submitted','under_review','approved','rejected','returned_for_correction')),
    CONSTRAINT "chk_intakedraft_kind" CHECK ("CaseKind" IN
        ('fir_standard','zero_fir','udr','ncr','par','missing_person')),
    CONSTRAINT "chk_intakedraft_category" CHECK ("CaseCategoryCode" IN
        ('FIR','Zero FIR','UDR','NCR','PAR')),
    -- an approved draft MUST reference the case it produced (data-integrity gate)
    CONSTRAINT "chk_intakedraft_approved_case" CHECK (
        "Status" <> 'approved' OR "CaseMasterID" IS NOT NULL
    )
);
COMMENT ON TABLE "IntakeDraft" IS 'Staged FIR/case intake submission with an explicit review state machine. Canonicalised into CaseMaster/CaseVersion/CasePartyRole only on approval; invalid/incomplete drafts never reach canonical tables.';

-- =============================================================================
-- 3. INTAKE DRAFT PARTY — draft-scoped case parties (pre-canonicalisation).
--    Mirrors CasePartyRole roles. A party links an existing CanonicalPerson/
--    CanonicalOrganisation OR carries new-person attributes OR is unknown.
-- =============================================================================
CREATE TABLE IF NOT EXISTS "IntakeDraftParty" (
    "IntakeDraftPartyID" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "IntakeDraftID"   BIGINT NOT NULL REFERENCES "IntakeDraft" ("IntakeDraftID") ON DELETE CASCADE,
    "RoleType"        VARCHAR NOT NULL,   -- accused|victim|complainant|witness|informant|guardian|organisation|unknown
    "PartyNature"     VARCHAR NOT NULL DEFAULT 'person',  -- person|organisation|unknown
    "CanonicalPersonID"       BIGINT REFERENCES "CanonicalPerson" ("CanonicalPersonID"),
    "CanonicalOrganisationID" BIGINT REFERENCES "CanonicalOrganisation" ("CanonicalOrganisationID"),
    "IsUnknownParty"  BOOLEAN NOT NULL DEFAULT FALSE,
    "DisplayName"     VARCHAR,
    "Attributes"      JSONB NOT NULL DEFAULT '{}'::jsonb,  -- age/gender/alias/contact/address/org fields
    "SequenceNo"      INTEGER,
    "CreatedAt"       TIMESTAMPTZ NOT NULL DEFAULT now(),
    "UpdatedAt"       TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT "chk_intakeparty_role" CHECK ("RoleType" IN
        ('accused','victim','complainant','witness','informant','guardian','organisation','unknown')),
    CONSTRAINT "chk_intakeparty_nature" CHECK ("PartyNature" IN ('person','organisation','unknown')),
    -- a party must resolve to something: linked identity, unknown, or a label to canonicalise
    CONSTRAINT "chk_intakeparty_ref" CHECK (
        "CanonicalPersonID" IS NOT NULL
        OR "CanonicalOrganisationID" IS NOT NULL
        OR "IsUnknownParty" = TRUE
        OR ("DisplayName" IS NOT NULL AND length(btrim("DisplayName")) > 0)
    )
);
COMMENT ON TABLE "IntakeDraftParty" IS 'Draft-scoped case parties. Canonicalised into CanonicalPerson/CanonicalOrganisation + CasePartyRole on approval. Names are attributes, never identity keys.';

-- =============================================================================
-- 4. INTAKE DRAFT ACTIVITY — append-only autosave/submit/review trail.
-- =============================================================================
CREATE TABLE IF NOT EXISTS "IntakeDraftActivity" (
    "IntakeDraftActivityID" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "IntakeDraftID"   BIGINT NOT NULL REFERENCES "IntakeDraft" ("IntakeDraftID") ON DELETE CASCADE,
    "EventType"       VARCHAR NOT NULL,
    "Actor"           VARCHAR,
    "Detail"          JSONB NOT NULL DEFAULT '{}'::jsonb,
    "CreatedAt"       TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT "chk_intakeactivity_type" CHECK ("EventType" IN
        ('created','autosaved','updated','validated','submitted','review_started',
         'approved','rejected','returned_for_correction','reopened',
         'party_added','party_updated','party_removed','event_added'))
);
COMMENT ON TABLE "IntakeDraftActivity" IS 'Append-only intake draft activity/review trail (autosave/submit/approve/return). Never overwrites history.';

-- =============================================================================
-- 5. INDEXES
-- =============================================================================
CREATE INDEX IF NOT EXISTS "idx_intakedraft_status"     ON "IntakeDraft" ("Status");
CREATE INDEX IF NOT EXISTS "idx_intakedraft_case"       ON "IntakeDraft" ("CaseMasterID");
CREATE INDEX IF NOT EXISTS "idx_intakedraft_source"     ON "IntakeDraft" ("SourceRecordID");
CREATE INDEX IF NOT EXISTS "idx_intakedraft_kind"       ON "IntakeDraft" ("CaseKind");
CREATE INDEX IF NOT EXISTS "idx_intakedraft_updated"    ON "IntakeDraft" ("UpdatedAt");
CREATE INDEX IF NOT EXISTS "gin_intakedraft_payload"    ON "IntakeDraft" USING GIN ("Payload");
CREATE INDEX IF NOT EXISTS "idx_intakeparty_draft"      ON "IntakeDraftParty" ("IntakeDraftID");
CREATE INDEX IF NOT EXISTS "idx_intakeparty_person"     ON "IntakeDraftParty" ("CanonicalPersonID");
CREATE INDEX IF NOT EXISTS "idx_intakeparty_role"       ON "IntakeDraftParty" ("RoleType");
CREATE INDEX IF NOT EXISTS "idx_intakeactivity_draft"   ON "IntakeDraftActivity" ("IntakeDraftID");
CREATE INDEX IF NOT EXISTS "idx_intakeactivity_type"    ON "IntakeDraftActivity" ("EventType");

-- =============================================================================
-- 6. TRIGGERS — updated_at maintenance (reuse shared fn_set_updated_at()).
-- =============================================================================
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_trigger WHERE tgname = 'trg_intakedraft_updated') THEN
        CREATE TRIGGER "trg_intakedraft_updated" BEFORE UPDATE ON "IntakeDraft"
            FOR EACH ROW EXECUTE FUNCTION fn_set_updated_at();
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_trigger WHERE tgname = 'trg_intakeparty_updated') THEN
        CREATE TRIGGER "trg_intakeparty_updated" BEFORE UPDATE ON "IntakeDraftParty"
            FOR EACH ROW EXECUTE FUNCTION fn_set_updated_at();
    END IF;
END$$;

-- =============================================================================
-- 7. VIEW — intake inbox read model (drafts + party counts, no PII expansion).
-- =============================================================================
CREATE OR REPLACE VIEW "vw_intake_inbox" AS
SELECT
    d."IntakeDraftID",
    d."DraftKey",
    d."CaseKind",
    d."CaseCategoryCode",
    d."Status",
    d."CaseMasterID",
    cm."CrimeNo",
    d."CreatedByActor",
    d."SubmittedByActor",
    d."ReviewedByActor",
    d."RevisionNo",
    (SELECT COUNT(*) FROM "IntakeDraftParty" p WHERE p."IntakeDraftID" = d."IntakeDraftID") AS "PartyCount",
    (d."ValidationState" ->> 'ok')::boolean AS "ValidationOk",
    d."CreatedAt",
    d."UpdatedAt",
    d."SubmittedAt",
    d."ReviewedAt"
FROM "IntakeDraft" d
LEFT JOIN "CaseMaster" cm ON cm."CaseMasterID" = d."CaseMasterID";
COMMENT ON VIEW "vw_intake_inbox" IS 'Intake inbox read model: drafts with party counts + validation flag. No narrative/PII expansion.';

-- =============================================================================
-- 8. Grants + RLS disabled/NO FORCE + global verification (hackathon).
-- =============================================================================
DO $$
BEGIN
    IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'drishti_readonly') THEN
        GRANT SELECT ON "IntakeDraft"         TO drishti_readonly;
        GRANT SELECT ON "IntakeDraftParty"    TO drishti_readonly;
        GRANT SELECT ON "IntakeDraftActivity" TO drishti_readonly;
        GRANT SELECT ON "vw_intake_inbox"     TO drishti_readonly;
    END IF;
END$$;

SELECT fn_disable_rls_all_app();
SELECT fn_assert_rls_disabled();

COMMIT;

-- =============================================================================
-- End of migration 010.
-- =============================================================================
