-- =============================================================================
-- DRISHTI migration 015 — template-driven digital + financial import pipeline
-- Target: PostgreSQL 15+ / AWS RDS PostgreSQL (ap-south-1)
-- Depends on: 005, 006, 007, 008 (+ police_fir_extensions.sql financial tables)
-- =============================================================================
--
-- Phase 8: validated high-volume STRUCTURED imports (CDR/chat/IP/device/GPS +
-- bank transactions / account-KYC / wallet-UPI) and reviewed graph links for
-- digital and money evidence, all through FastAPI.
--
-- The digital canonical tables (Device, DeviceArtifact, CommunicationEvent,
-- LocationObservation) and the financial tables (FinancialAccount,
-- FinancialTransaction, TransactionLink) already exist. This migration adds:
--   1. A template registry (ImportTemplate + versioned ImportTemplateVersion) so
--      imports are template/schema-version driven.
--   2. ImportBatch + ImportStagingRow: the staging layer where parsed rows land
--      for a dry-run BEFORE any canonical write, with approve-commit, idempotency,
--      partial errors, rollback and supersession.
--   3. Additive provenance/version/currency/normalised-channel/reviewed-owner
--      columns on the financial + digital tables (source file never mutates a
--      prediction; only committed, provenanced canonical rows do).
--   4. MoneyAlert + MoneyAlertReview: rule-based, reason-coded, evidence-backed
--      money alerts with a reviewer disposition. No link implies guilt.
--
-- HACKATHON SCOPE: structured CSV/JSON only. No OCR / extraction. RLS stays
-- DISABLED + NO FORCE. No RLS policies. Additive + idempotent: safe to re-run.
-- =============================================================================

BEGIN;

-- =============================================================================
-- 1. IMPORT TEMPLATE REGISTRY (template/schema-version driven imports)
-- =============================================================================
CREATE TABLE IF NOT EXISTS "ImportTemplate" (
    "ImportTemplateID" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "Code"        VARCHAR NOT NULL UNIQUE,       -- e.g. cdr_call_events, bank_transactions
    "Name"        VARCHAR NOT NULL,
    "Domain"      VARCHAR NOT NULL,              -- cdr|chat|ip_log|device_artifact|location|bank_txn|account_kyc|wallet_upi
    "TargetTable" VARCHAR NOT NULL,              -- CommunicationEvent|DeviceArtifact|LocationObservation|FinancialTransaction|FinancialAccount
    "Description" TEXT,
    "IsSynthetic" BOOLEAN NOT NULL DEFAULT TRUE,
    "CreatedAt"   TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT "chk_importtemplate_domain" CHECK ("Domain" IN
        ('cdr','chat','ip_log','device_artifact','location',
         'bank_txn','account_kyc','wallet_upi'))
);
COMMENT ON TABLE "ImportTemplate" IS 'Named import template per digital/financial domain. Imports are template-driven (Phase 8).';

CREATE TABLE IF NOT EXISTS "ImportTemplateVersion" (
    "ImportTemplateVersionID" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "ImportTemplateID" INTEGER NOT NULL REFERENCES "ImportTemplate" ("ImportTemplateID") ON DELETE CASCADE,
    "Version"       VARCHAR NOT NULL,
    "ColumnMapping" JSONB NOT NULL DEFAULT '{}'::jsonb,  -- {"fields":[{canonical,source,required,type,default}], ...}
    "RequiredColumns" JSONB NOT NULL DEFAULT '[]'::jsonb,
    "DedupeKeys"    JSONB NOT NULL DEFAULT '[]'::jsonb,   -- canonical field names forming the row dedupe hash
    "Status"        VARCHAR NOT NULL DEFAULT 'approved',  -- draft|approved|retired
    "Notes"         TEXT,
    "CreatedAt"     TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT "uq_importtemplateversion" UNIQUE ("ImportTemplateID", "Version"),
    CONSTRAINT "chk_importtemplateversion_status" CHECK ("Status" IN ('draft','approved','retired'))
);
COMMENT ON TABLE "ImportTemplateVersion" IS 'Versioned column-mapping/schema for a template. A batch binds to an exact template version (strict contract).';

-- =============================================================================
-- 2. IMPORT BATCH + STAGING ROWS (staging -> dry-run -> approve commit)
-- =============================================================================
CREATE TABLE IF NOT EXISTS "ImportBatch" (
    "ImportBatchID"  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "IngestionJobID" BIGINT REFERENCES "IngestionJob" ("IngestionJobID"),
    "ImportTemplateVersionID" BIGINT NOT NULL REFERENCES "ImportTemplateVersion" ("ImportTemplateVersionID"),
    "EvidenceItemID" BIGINT REFERENCES "EvidenceItem" ("EvidenceItemID"),  -- source file uploaded as evidence
    "CaseMasterID"   INTEGER REFERENCES "CaseMaster" ("CaseMasterID"),
    "Domain"         VARCHAR NOT NULL,
    "SourceFileName" VARCHAR,
    "SourceFormat"   VARCHAR NOT NULL DEFAULT 'csv',      -- csv|json
    "SourceSha256"   VARCHAR,                              -- REAL sha256 of the uploaded structured file
    "IdempotencyKey" VARCHAR UNIQUE,                       -- safe retry / de-dup
    "Status"         VARCHAR NOT NULL DEFAULT 'staged',    -- staged|dry_run|committed|partial|rolled_back|superseded|failed
    "DryRun"         BOOLEAN NOT NULL DEFAULT TRUE,
    "MappingResolved" JSONB NOT NULL DEFAULT '{}'::jsonb,  -- the effective mapping used (template default + overrides)
    "Totals"         JSONB NOT NULL DEFAULT '{}'::jsonb,   -- parsed/valid/rejected/duplicate/committed counts
    "ErrorSummary"   JSONB NOT NULL DEFAULT '{}'::jsonb,   -- reason -> count
    "SupersededByImportBatchID" BIGINT REFERENCES "ImportBatch" ("ImportBatchID"),
    "CreatedByActor" VARCHAR,
    "ApprovedByActor" VARCHAR,
    "CommittedAt"    TIMESTAMPTZ,
    "IsSynthetic"    BOOLEAN NOT NULL DEFAULT TRUE,
    "CreatedAt"      TIMESTAMPTZ NOT NULL DEFAULT now(),
    "UpdatedAt"      TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT "chk_importbatch_status" CHECK ("Status" IN
        ('staged','dry_run','committed','partial','rolled_back','superseded','failed')),
    CONSTRAINT "chk_importbatch_format" CHECK ("SourceFormat" IN ('csv','json'))
);
COMMENT ON TABLE "ImportBatch" IS 'A template-driven import run: source file (as evidence) parsed into staging for a dry-run, then approve-committed to canonical tables with provenance. Idempotent; supports rollback/supersession.';

CREATE TABLE IF NOT EXISTS "ImportStagingRow" (
    "ImportStagingRowID" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "ImportBatchID"  BIGINT NOT NULL REFERENCES "ImportBatch" ("ImportBatchID") ON DELETE CASCADE,
    "RowNumber"      INTEGER,
    "RawValues"      JSONB NOT NULL DEFAULT '{}'::jsonb,   -- as-parsed source columns
    "MappedValues"   JSONB NOT NULL DEFAULT '{}'::jsonb,   -- canonical-field values after mapping
    "RowHash"        VARCHAR,                               -- dedupe key (over DedupeKeys)
    "Status"         VARCHAR NOT NULL DEFAULT 'staged',     -- staged|valid|rejected|duplicate|committed
    "RejectReason"   TEXT,
    "CanonicalTargetTable" VARCHAR,
    "CanonicalTargetID"    BIGINT,                          -- set on commit (traceability + rollback)
    "SourceRecordID" BIGINT REFERENCES "SourceRecord" ("SourceRecordID"),  -- provenance, set on commit
    "CreatedAt"      TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT "chk_importstagingrow_status" CHECK ("Status" IN
        ('staged','valid','rejected','duplicate','committed'))
);
COMMENT ON TABLE "ImportStagingRow" IS 'Per-row staging outcome for an import batch. Invalid/rejected/duplicate rows stay here and never reach canonical tables.';

-- =============================================================================
-- 3. MONEY ALERTS (rule-based, reason-coded, evidence-backed, reviewable)
-- =============================================================================
CREATE TABLE IF NOT EXISTS "MoneyAlert" (
    "MoneyAlertID"  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "AlertType"     VARCHAR NOT NULL,          -- structuring|layering|circular|fan_in|rapid_movement
    "ReasonCode"    VARCHAR NOT NULL,          -- explicit machine reason code
    "Severity"      VARCHAR NOT NULL DEFAULT 'medium',  -- low|medium|high|critical
    "Title"         VARCHAR,
    "Message"       TEXT,                       -- neutral wording; a pattern is NOT proof of guilt
    "AccountID"     INTEGER REFERENCES "FinancialAccount" ("AccountID"),
    "CaseMasterID"  INTEGER REFERENCES "CaseMaster" ("CaseMasterID"),
    "EvidenceItemID" BIGINT REFERENCES "EvidenceItem" ("EvidenceItemID"),
    "ModelVersionID" INTEGER REFERENCES "ModelVersion" ("ModelVersionID"),
    "TransactionIDs" JSONB NOT NULL DEFAULT '[]'::jsonb,   -- provenance: the flagged txn ids
    "SourceRecordIDs" JSONB NOT NULL DEFAULT '[]'::jsonb,  -- provenance: contributing source records
    "Payload"       JSONB NOT NULL DEFAULT '{}'::jsonb,
    "Status"        VARCHAR NOT NULL DEFAULT 'open',       -- open|reviewed|dismissed|escalated|confirmed_pattern|false_positive
    "CreatedAt"     TIMESTAMPTZ NOT NULL DEFAULT now(),
    "UpdatedAt"     TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT "chk_moneyalert_type" CHECK ("AlertType" IN
        ('structuring','layering','circular','fan_in','rapid_movement')),
    CONSTRAINT "chk_moneyalert_severity" CHECK ("Severity" IN ('low','medium','high','critical')),
    CONSTRAINT "chk_moneyalert_status" CHECK ("Status" IN
        ('open','reviewed','dismissed','escalated','confirmed_pattern','false_positive'))
);
COMMENT ON TABLE "MoneyAlert" IS 'Rule-based money-pattern alert with an explicit reason code, transaction/source provenance and a reviewer disposition. A financial pattern is investigation support only, never proof of guilt.';

CREATE TABLE IF NOT EXISTS "MoneyAlertReview" (
    "MoneyAlertReviewID" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "MoneyAlertID"  BIGINT NOT NULL REFERENCES "MoneyAlert" ("MoneyAlertID") ON DELETE CASCADE,
    "Disposition"   VARCHAR NOT NULL,          -- acknowledge|dismiss|escalate|false_positive|confirm_pattern
    "ReviewerActor" VARCHAR,
    "Reason"        TEXT,
    "ReviewedAt"    TIMESTAMPTZ NOT NULL DEFAULT now(),
    "CreatedAt"     TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT "chk_moneyalertreview_disp" CHECK ("Disposition" IN
        ('acknowledge','dismiss','escalate','false_positive','confirm_pattern'))
);
COMMENT ON TABLE "MoneyAlertReview" IS 'Append-only reviewer disposition history for a money alert (human-in-the-loop).';

-- =============================================================================
-- 4. ADDITIVE COLUMNS — financial tables (source/version/reference/currency/
--    normalised channel/reviewed owner + case links + import provenance)
-- =============================================================================
ALTER TABLE "FinancialAccount" ADD COLUMN IF NOT EXISTS "SourceRecordID" BIGINT REFERENCES "SourceRecord" ("SourceRecordID");
ALTER TABLE "FinancialAccount" ADD COLUMN IF NOT EXISTS "IngestionJobID" BIGINT REFERENCES "IngestionJob" ("IngestionJobID");
ALTER TABLE "FinancialAccount" ADD COLUMN IF NOT EXISTS "ImportBatchID"  BIGINT REFERENCES "ImportBatch" ("ImportBatchID");
ALTER TABLE "FinancialAccount" ADD COLUMN IF NOT EXISTS "Version"        INTEGER NOT NULL DEFAULT 1;
ALTER TABLE "FinancialAccount" ADD COLUMN IF NOT EXISTS "SyntheticReference" VARCHAR;
ALTER TABLE "FinancialAccount" ADD COLUMN IF NOT EXISTS "Currency"       VARCHAR NOT NULL DEFAULT 'INR';
ALTER TABLE "FinancialAccount" ADD COLUMN IF NOT EXISTS "OwnerCanonicalPersonID" BIGINT REFERENCES "CanonicalPerson" ("CanonicalPersonID");
ALTER TABLE "FinancialAccount" ADD COLUMN IF NOT EXISTS "CanonicalEntityID" BIGINT REFERENCES "CanonicalEntity" ("CanonicalEntityID");
ALTER TABLE "FinancialAccount" ADD COLUMN IF NOT EXISTS "OwnerReviewStatus" VARCHAR NOT NULL DEFAULT 'candidate';
ALTER TABLE "FinancialAccount" ADD COLUMN IF NOT EXISTS "KycDetail"      JSONB NOT NULL DEFAULT '{}'::jsonb;
ALTER TABLE "FinancialAccount" ADD COLUMN IF NOT EXISTS "IsSynthetic"    BOOLEAN NOT NULL DEFAULT TRUE;

ALTER TABLE "FinancialTransaction" ADD COLUMN IF NOT EXISTS "SourceRecordID" BIGINT REFERENCES "SourceRecord" ("SourceRecordID");
ALTER TABLE "FinancialTransaction" ADD COLUMN IF NOT EXISTS "ImportBatchID"  BIGINT REFERENCES "ImportBatch" ("ImportBatchID");
ALTER TABLE "FinancialTransaction" ADD COLUMN IF NOT EXISTS "Version"        INTEGER NOT NULL DEFAULT 1;
ALTER TABLE "FinancialTransaction" ADD COLUMN IF NOT EXISTS "SyntheticReference" VARCHAR;
ALTER TABLE "FinancialTransaction" ADD COLUMN IF NOT EXISTS "Currency"       VARCHAR NOT NULL DEFAULT 'INR';
ALTER TABLE "FinancialTransaction" ADD COLUMN IF NOT EXISTS "NormalizedChannel" VARCHAR;  -- upi|imps|neft|rtgs|cash|atm|wallet|card|unknown
ALTER TABLE "FinancialTransaction" ADD COLUMN IF NOT EXISTS "SupersededByTransactionID" BIGINT REFERENCES "FinancialTransaction" ("TransactionID");
ALTER TABLE "FinancialTransaction" ADD COLUMN IF NOT EXISTS "ReviewStatus"   VARCHAR NOT NULL DEFAULT 'candidate';
ALTER TABLE "FinancialTransaction" ADD COLUMN IF NOT EXISTS "IsSynthetic"    BOOLEAN NOT NULL DEFAULT TRUE;

-- reviewed case link provenance (TransactionLink already M:N txn<->case)
ALTER TABLE "TransactionLink" ADD COLUMN IF NOT EXISTS "ReviewStatus"   VARCHAR NOT NULL DEFAULT 'candidate';
ALTER TABLE "TransactionLink" ADD COLUMN IF NOT EXISTS "SourceRecordID" BIGINT REFERENCES "SourceRecord" ("SourceRecordID");
ALTER TABLE "TransactionLink" ADD COLUMN IF NOT EXISTS "ReviewedByActor" VARCHAR;
ALTER TABLE "TransactionLink" ADD COLUMN IF NOT EXISTS "ReviewedAt"     TIMESTAMPTZ;

-- =============================================================================
-- 5. ADDITIVE COLUMNS — digital tables (import provenance + reviewed link)
-- =============================================================================
ALTER TABLE "Device"              ADD COLUMN IF NOT EXISTS "ImportBatchID" BIGINT REFERENCES "ImportBatch" ("ImportBatchID");
ALTER TABLE "DeviceArtifact"      ADD COLUMN IF NOT EXISTS "ImportBatchID" BIGINT REFERENCES "ImportBatch" ("ImportBatchID");
ALTER TABLE "CommunicationEvent"  ADD COLUMN IF NOT EXISTS "ImportBatchID" BIGINT REFERENCES "ImportBatch" ("ImportBatchID");
ALTER TABLE "CommunicationEvent"  ADD COLUMN IF NOT EXISTS "ReviewedByActor" VARCHAR;
ALTER TABLE "CommunicationEvent"  ADD COLUMN IF NOT EXISTS "ReviewedAt"    TIMESTAMPTZ;
ALTER TABLE "LocationObservation" ADD COLUMN IF NOT EXISTS "ImportBatchID" BIGINT REFERENCES "ImportBatch" ("ImportBatchID");

-- reviewed entity-link queue needs reviewer/timestamp on EvidenceEntityLink
ALTER TABLE "EvidenceEntityLink"  ADD COLUMN IF NOT EXISTS "ReviewedByActor" VARCHAR;
ALTER TABLE "EvidenceEntityLink"  ADD COLUMN IF NOT EXISTS "ReviewedAt"    TIMESTAMPTZ;
ALTER TABLE "EvidenceEntityLink"  ADD COLUMN IF NOT EXISTS "ImportBatchID" BIGINT REFERENCES "ImportBatch" ("ImportBatchID");

-- =============================================================================
-- 6. INDEXES
-- =============================================================================
CREATE INDEX IF NOT EXISTS "idx_importtemplate_domain"     ON "ImportTemplate" ("Domain");
CREATE INDEX IF NOT EXISTS "idx_importtemplateversion_tpl" ON "ImportTemplateVersion" ("ImportTemplateID");
CREATE INDEX IF NOT EXISTS "idx_importbatch_tplver"        ON "ImportBatch" ("ImportTemplateVersionID");
CREATE INDEX IF NOT EXISTS "idx_importbatch_status"        ON "ImportBatch" ("Status");
CREATE INDEX IF NOT EXISTS "idx_importbatch_domain"        ON "ImportBatch" ("Domain");
CREATE INDEX IF NOT EXISTS "idx_importbatch_case"          ON "ImportBatch" ("CaseMasterID");
CREATE INDEX IF NOT EXISTS "idx_importbatch_evidence"      ON "ImportBatch" ("EvidenceItemID");
CREATE INDEX IF NOT EXISTS "idx_importstagingrow_batch"    ON "ImportStagingRow" ("ImportBatchID");
CREATE INDEX IF NOT EXISTS "idx_importstagingrow_status"   ON "ImportStagingRow" ("Status");
CREATE INDEX IF NOT EXISTS "idx_importstagingrow_hash"     ON "ImportStagingRow" ("RowHash");
CREATE INDEX IF NOT EXISTS "idx_importstagingrow_target"   ON "ImportStagingRow" ("CanonicalTargetTable", "CanonicalTargetID");
CREATE INDEX IF NOT EXISTS "idx_moneyalert_status"         ON "MoneyAlert" ("Status");
CREATE INDEX IF NOT EXISTS "idx_moneyalert_type"           ON "MoneyAlert" ("AlertType");
CREATE INDEX IF NOT EXISTS "idx_moneyalert_account"        ON "MoneyAlert" ("AccountID");
CREATE INDEX IF NOT EXISTS "idx_moneyalert_case"           ON "MoneyAlert" ("CaseMasterID");
CREATE INDEX IF NOT EXISTS "idx_moneyalertreview_alert"    ON "MoneyAlertReview" ("MoneyAlertID");

CREATE INDEX IF NOT EXISTS "idx_finaccount_sourcerec"      ON "FinancialAccount" ("SourceRecordID");
CREATE INDEX IF NOT EXISTS "idx_finaccount_batch"          ON "FinancialAccount" ("ImportBatchID");
CREATE INDEX IF NOT EXISTS "idx_finaccount_owner"          ON "FinancialAccount" ("OwnerCanonicalPersonID");
CREATE INDEX IF NOT EXISTS "idx_finaccount_canonentity"    ON "FinancialAccount" ("CanonicalEntityID");
CREATE INDEX IF NOT EXISTS "idx_fintxn_sourcerec"          ON "FinancialTransaction" ("SourceRecordID");
CREATE INDEX IF NOT EXISTS "idx_fintxn_batch"              ON "FinancialTransaction" ("ImportBatchID");
CREATE INDEX IF NOT EXISTS "idx_fintxn_review"             ON "FinancialTransaction" ("ReviewStatus");
CREATE INDEX IF NOT EXISTS "idx_txnlink_review"            ON "TransactionLink" ("ReviewStatus");
CREATE INDEX IF NOT EXISTS "idx_commevent_batch"           ON "CommunicationEvent" ("ImportBatchID");
CREATE INDEX IF NOT EXISTS "idx_locationobs_batch"         ON "LocationObservation" ("ImportBatchID");
CREATE INDEX IF NOT EXISTS "idx_device_batch"              ON "Device" ("ImportBatchID");
CREATE INDEX IF NOT EXISTS "idx_evidenceentitylink_review" ON "EvidenceEntityLink" ("ReviewStatus");

CREATE INDEX IF NOT EXISTS "gin_importtemplateversion_map" ON "ImportTemplateVersion" USING GIN ("ColumnMapping");
CREATE INDEX IF NOT EXISTS "gin_importbatch_totals"        ON "ImportBatch" USING GIN ("Totals");
CREATE INDEX IF NOT EXISTS "gin_importstagingrow_mapped"   ON "ImportStagingRow" USING GIN ("MappedValues");
CREATE INDEX IF NOT EXISTS "gin_moneyalert_txns"           ON "MoneyAlert" USING GIN ("TransactionIDs");

-- =============================================================================
-- 7. TRIGGERS (updated_at maintenance — reuse shared fn_set_updated_at())
-- =============================================================================
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_trigger WHERE tgname = 'trg_importbatch_updated') THEN
        CREATE TRIGGER "trg_importbatch_updated" BEFORE UPDATE ON "ImportBatch"
            FOR EACH ROW EXECUTE FUNCTION fn_set_updated_at();
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_trigger WHERE tgname = 'trg_moneyalert_updated') THEN
        CREATE TRIGGER "trg_moneyalert_updated" BEFORE UPDATE ON "MoneyAlert"
            FOR EACH ROW EXECUTE FUNCTION fn_set_updated_at();
    END IF;
END$$;

-- =============================================================================
-- 8. SEED — built-in import templates + versions (idempotent)
--    ColumnMapping.fields: {canonical, source, required, type[, default]}
--    type in string|int|float|datetime|decimal. dedupe_keys = canonical names.
-- =============================================================================
INSERT INTO "ImportTemplate" ("Code","Name","Domain","TargetTable","Description") VALUES
    ('cdr_call_events',   'CDR / call events',      'cdr',            'CommunicationEvent', 'Call detail records: caller/callee, time, duration.'),
    ('chat_messages',     'Chat / message export',  'chat',           'CommunicationEvent', 'Chat/message export: sender/recipient handles, time.'),
    ('ip_network_logs',   'IP / network logs',      'ip_log',         'CommunicationEvent', 'IP/network session logs: endpoints + time.'),
    ('device_artifacts',  'Device artifacts',       'device_artifact','DeviceArtifact',     'Device export artifacts: device id, artifact type, reference.'),
    ('gps_location',      'GPS / location',         'location',       'LocationObservation','GPS/location observations: entity, time, lat/long.'),
    ('bank_transactions', 'Bank transactions',      'bank_txn',       'FinancialTransaction','Bank transactions: source/destination account, amount, time, channel.'),
    ('account_kyc',       'Account / KYC records',  'account_kyc',    'FinancialAccount',   'Account/KYC records: account no, type, holder, bank, IFSC.'),
    ('wallet_upi',        'Wallet / UPI references','wallet_upi',     'FinancialTransaction','Wallet/UPI transfer references: handles, amount, time.')
ON CONFLICT ("Code") DO NOTHING;

-- Template versions (v1 for all; a v2 for CDR to exercise template versioning).
INSERT INTO "ImportTemplateVersion" ("ImportTemplateID","Version","ColumnMapping","RequiredColumns","DedupeKeys","Status","Notes")
SELECT t."ImportTemplateID", v.version, v.mapping::jsonb, v.required::jsonb, v.dedupe::jsonb, 'approved', v.notes
FROM "ImportTemplate" t
JOIN (VALUES
 ('cdr_call_events','v1',
  '{"target_table":"CommunicationEvent","comm_type":"call","fields":['
    '{"canonical":"endpoint_a","source":"caller_msisdn","required":true,"type":"string"},'
    '{"canonical":"endpoint_b","source":"callee_msisdn","required":true,"type":"string"},'
    '{"canonical":"occurred_at","source":"event_time","required":true,"type":"datetime"},'
    '{"canonical":"duration_sec","source":"duration_sec","required":false,"type":"int"},'
    '{"canonical":"comm_type","source":"call_type","required":false,"type":"string","default":"call"}]}',
  '["endpoint_a","endpoint_b","occurred_at"]',
  '["endpoint_a","endpoint_b","occurred_at"]',
  'Standard CDR layout.'),
 ('cdr_call_events','v2',
  '{"target_table":"CommunicationEvent","comm_type":"call","fields":['
    '{"canonical":"endpoint_a","source":"a_party","required":true,"type":"string"},'
    '{"canonical":"endpoint_b","source":"b_party","required":true,"type":"string"},'
    '{"canonical":"occurred_at","source":"start_ts","required":true,"type":"datetime"},'
    '{"canonical":"duration_sec","source":"dur","required":false,"type":"int"},'
    '{"canonical":"comm_type","source":"type","required":false,"type":"string","default":"call"}]}',
  '["endpoint_a","endpoint_b","occurred_at"]',
  '["endpoint_a","endpoint_b","occurred_at"]',
  'Alternate CDR column names (v2).'),
 ('chat_messages','v1',
  '{"target_table":"CommunicationEvent","comm_type":"chat","fields":['
    '{"canonical":"endpoint_a","source":"sender","required":true,"type":"string"},'
    '{"canonical":"endpoint_b","source":"recipient","required":true,"type":"string"},'
    '{"canonical":"occurred_at","source":"sent_at","required":true,"type":"datetime"},'
    '{"canonical":"comm_type","source":"channel","required":false,"type":"string","default":"chat"}]}',
  '["endpoint_a","endpoint_b","occurred_at"]',
  '["endpoint_a","endpoint_b","occurred_at"]',
  'Chat/message export layout.'),
 ('ip_network_logs','v1',
  '{"target_table":"CommunicationEvent","comm_type":"ip","fields":['
    '{"canonical":"endpoint_a","source":"src_ip","required":true,"type":"string"},'
    '{"canonical":"endpoint_b","source":"dst_ip","required":true,"type":"string"},'
    '{"canonical":"occurred_at","source":"log_time","required":true,"type":"datetime"},'
    '{"canonical":"comm_type","source":"proto","required":false,"type":"string","default":"ip"}]}',
  '["endpoint_a","endpoint_b","occurred_at"]',
  '["endpoint_a","endpoint_b","occurred_at"]',
  'IP/network session log layout.'),
 ('device_artifacts','v1',
  '{"target_table":"DeviceArtifact","fields":['
    '{"canonical":"device_identifier","source":"device_id","required":true,"type":"string"},'
    '{"canonical":"artifact_type","source":"artifact_type","required":true,"type":"string"},'
    '{"canonical":"reference","source":"reference","required":false,"type":"string"}]}',
  '["device_identifier","artifact_type"]',
  '["device_identifier","artifact_type","reference"]',
  'Device artifact export layout.'),
 ('gps_location','v1',
  '{"target_table":"LocationObservation","fields":['
    '{"canonical":"entity_ref","source":"entity_ref","required":false,"type":"string"},'
    '{"canonical":"observed_at","source":"observed_at","required":true,"type":"datetime"},'
    '{"canonical":"latitude","source":"lat","required":true,"type":"float"},'
    '{"canonical":"longitude","source":"lon","required":true,"type":"float"}]}',
  '["observed_at","latitude","longitude"]',
  '["entity_ref","observed_at","latitude","longitude"]',
  'GPS/location observation layout.'),
 ('bank_transactions','v1',
  '{"target_table":"FinancialTransaction","fields":['
    '{"canonical":"source_account_no","source":"from_account","required":true,"type":"string"},'
    '{"canonical":"destination_account_no","source":"to_account","required":true,"type":"string"},'
    '{"canonical":"amount","source":"amount","required":true,"type":"decimal"},'
    '{"canonical":"txn_timestamp","source":"txn_time","required":true,"type":"datetime"},'
    '{"canonical":"channel","source":"channel","required":false,"type":"string","default":"neft"},'
    '{"canonical":"reference","source":"ref_no","required":false,"type":"string"}]}',
  '["source_account_no","destination_account_no","amount","txn_timestamp"]',
  '["source_account_no","destination_account_no","amount","txn_timestamp","reference"]',
  'Bank statement/transaction layout.'),
 ('account_kyc','v1',
  '{"target_table":"FinancialAccount","fields":['
    '{"canonical":"account_no","source":"account_no","required":true,"type":"string"},'
    '{"canonical":"account_type","source":"account_type","required":false,"type":"string","default":"unknown"},'
    '{"canonical":"holder_name","source":"holder_name","required":false,"type":"string"},'
    '{"canonical":"bank","source":"bank","required":false,"type":"string"},'
    '{"canonical":"ifsc","source":"ifsc","required":false,"type":"string"},'
    '{"canonical":"kyc_reference","source":"kyc_ref","required":false,"type":"string"}]}',
  '["account_no"]',
  '["account_no"]',
  'Account/KYC record layout.'),
 ('wallet_upi','v1',
  '{"target_table":"FinancialTransaction","fields":['
    '{"canonical":"source_account_no","source":"payer_vpa","required":true,"type":"string"},'
    '{"canonical":"destination_account_no","source":"payee_vpa","required":true,"type":"string"},'
    '{"canonical":"amount","source":"amount","required":true,"type":"decimal"},'
    '{"canonical":"txn_timestamp","source":"txn_time","required":true,"type":"datetime"},'
    '{"canonical":"channel","source":"channel","required":false,"type":"string","default":"upi"},'
    '{"canonical":"reference","source":"rrn","required":false,"type":"string"}]}',
  '["source_account_no","destination_account_no","amount","txn_timestamp"]',
  '["source_account_no","destination_account_no","amount","txn_timestamp","reference"]',
  'Wallet/UPI reference layout.')
) AS v(code, version, mapping, required, dedupe, notes) ON t."Code" = v.code
ON CONFLICT ("ImportTemplateID","Version") DO NOTHING;

-- A source system for structured digital/financial imports (idempotent).
INSERT INTO "SourceSystem" ("Code","Name","Kind","Description") VALUES
    ('DIGITAL_IMPORT',  'Digital structured import',  'digital_export', 'CDR/chat/IP/device/GPS structured imports (Phase 8).'),
    ('FINANCIAL_IMPORT','Financial structured import','csv_import',     'Bank/account/wallet structured imports (Phase 8).')
ON CONFLICT ("Code") DO NOTHING;

-- =============================================================================
-- 9. VIEW — reviewed entity-link queue (candidate links needing review)
-- =============================================================================
CREATE OR REPLACE VIEW "vw_entity_link_queue" AS
SELECT
    l."EvidenceEntityLinkID",
    l."EvidenceItemID",
    l."CanonicalEntityID",
    e."EntityKind",
    e."Label"        AS "EntityLabel",
    e."PublicRef"    AS "EntityRef",
    l."LinkType",
    l."Confidence",
    l."ReviewStatus",
    l."ReviewedByActor",
    l."ReviewedAt",
    l."SourceRecordID",
    l."ImportBatchID",
    ei."Title"       AS "EvidenceTitle",
    ei."EvidenceType",
    ei."CaseMasterID"
FROM "EvidenceEntityLink" l
JOIN "CanonicalEntity" e ON e."CanonicalEntityID" = l."CanonicalEntityID"
LEFT JOIN "EvidenceItem" ei ON ei."EvidenceItemID" = l."EvidenceItemID";
COMMENT ON VIEW "vw_entity_link_queue" IS 'Reviewed entity-link queue: evidence->entity links with their review state and provenance (Phase 8).';

-- =============================================================================
-- 10. Grants + RLS disabled/NO FORCE + global verification (hackathon).
-- =============================================================================
DO $$
DECLARE t TEXT;
BEGIN
    IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'drishti_readonly') THEN
        FOREACH t IN ARRAY ARRAY[
            'ImportTemplate','ImportTemplateVersion','ImportBatch','ImportStagingRow',
            'MoneyAlert','MoneyAlertReview'
        ] LOOP
            EXECUTE format('GRANT SELECT ON %I TO drishti_readonly', t);
        END LOOP;
        GRANT SELECT ON "vw_entity_link_queue" TO drishti_readonly;
    END IF;
END$$;

SELECT fn_disable_rls_all_app();
SELECT fn_assert_rls_disabled();

COMMIT;

-- =============================================================================
-- End of migration 015.
-- =============================================================================
