-- =============================================================================
-- DRISHTI migration 019 — forecast backtest persistence + governed forecasting
--                          feature schema seed (Phase 12)
-- Target: PostgreSQL 15+ / AWS RDS PostgreSQL (ap-south-1)
-- Depends on: 008 (FeatureDefinition/FeatureSchemaVersion/PredictionRequest/
--             Result/Review + ModelVersion governance columns), 009
--             (JurisdictionBoundary + fn_point_in_state for valid geography),
--             police_fir_intelligence.sql (ModelVersion, CrimeHead)
-- =============================================================================
--
-- Phase 12 makes the aggregate area/time forecast BACKTESTED, uncertainty-aware,
-- baseline-compared and governed. This migration adds:
--   1. "ForecastBacktest" — a typed, auditable record of a rolling-origin
--      backtest run (MAE/RMSE/WAPE/sMAPE + interval coverage + baseline skill +
--      the full per-district/head/season + geographic-holdout report).
--   2. An APPROVED forecasting feature schema ("forecast-area-incident" v1) and
--      its non-protected, aggregate, strictly-pre-cutoff FeatureDefinitions, so
--      the forecast persists through the governed FeatureSnapshot ->
--      PredictionRequest -> PredictionResult contract (Phase 10) exactly like
--      any other model. No protected attribute is included.
--
-- Forecasts are aggregate area/period decision support only — never a
-- person-level judgement. RLS stays DISABLED + NO FORCE (hackathon). No RLS
-- policies. Additive + idempotent: safe to re-run.
-- =============================================================================

BEGIN;

-- =============================================================================
-- 1. Forecast backtest record
-- =============================================================================
CREATE TABLE IF NOT EXISTS "ForecastBacktest" (
    "ForecastBacktestID" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "ModelVersionID"    INTEGER REFERENCES "ModelVersion" ("ModelVersionID"),
    "CrimeHeadID"       INTEGER REFERENCES "CrimeHead" ("CrimeHeadID"),   -- NULL = all heads
    "Horizon"           INTEGER NOT NULL,
    "NOrigins"          INTEGER,
    "LatestOrigin"      VARCHAR,                       -- last cutoff period used (YYYY-MM)
    "MAE"               NUMERIC,
    "RMSE"              NUMERIC,
    "WAPE"              NUMERIC,
    "SMAPE"             NUMERIC,
    "Coverage80"        NUMERIC,
    "Coverage50"        NUMERIC,
    "ScoredPoints"      INTEGER,
    "AbstainedCells"    INTEGER,
    "AbstentionRate"    NUMERIC,
    "BeatsAllBaselines" BOOLEAN,
    "ValidGeography"    VARCHAR,                        -- active|inactive_no_boundary
    "Baselines"         JSONB NOT NULL DEFAULT '{}'::jsonb,   -- baseline metrics + skill
    "Report"            JSONB NOT NULL DEFAULT '{}'::jsonb,   -- full report (by district/head/season, geo holdout)
    "Actor"             VARCHAR,
    "CreatedAt"         TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT "chk_forecastbacktest_horizon" CHECK ("Horizon" >= 1)
);
COMMENT ON TABLE "ForecastBacktest" IS
    'Rolling-origin backtest results for the aggregate forecast: MAE/RMSE/WAPE/sMAPE, interval coverage, baseline skill, geographic holdout and per-dimension error. Evidence that a forecast beats/compares to simple baselines.';

CREATE INDEX IF NOT EXISTS "idx_forecastbacktest_model" ON "ForecastBacktest" ("ModelVersionID");
CREATE INDEX IF NOT EXISTS "idx_forecastbacktest_head"  ON "ForecastBacktest" ("CrimeHeadID");
CREATE INDEX IF NOT EXISTS "idx_forecastbacktest_time"  ON "ForecastBacktest" ("CreatedAt");

-- =============================================================================
-- 2. Governed forecasting feature schema (approved, non-protected, pre-cutoff)
-- =============================================================================
-- Aggregate, area-level, strictly-pre-cutoff features. All Sensitivity='normal'
-- (no caste/religion/gender/juvenile/protected attribute enters a forecast).
INSERT INTO "FeatureDefinition"
    ("Name","ValueType","Description","SourceTable","SourceField","Transformation",
     "WindowSpec","ObservationCutoffBehavior","Sensitivity","AllowedTasks",
     "MissingPolicy","StalePolicy","Owner","ApprovalStatus")
VALUES
    ('fc_recent_mean_incidents','numeric','Trailing mean monthly incident count for the area (pre-cutoff).',
     'CaseMaster','CrimeRegisteredDate','mean_over_window','trailing_6m','strict_pre_cutoff','normal',
     ARRAY['area_incident_forecast'],'null_ok','invalidate_on_source_change','forecasting','approved'),
    ('fc_trend_slope','numeric','Linear trend slope of the monthly incident series over the recent window (pre-cutoff).',
     'CaseMaster','CrimeRegisteredDate','ols_slope','trailing_12m','strict_pre_cutoff','normal',
     ARRAY['area_incident_forecast'],'null_ok','invalidate_on_source_change','forecasting','approved'),
    ('fc_seasonal_index','numeric','Month-of-year seasonal factor for the area (pre-cutoff, multiplicative).',
     'CaseMaster','CrimeRegisteredDate','seasonal_factor','trailing_24m','strict_pre_cutoff','normal',
     ARRAY['area_incident_forecast'],'null_ok','invalidate_on_source_change','forecasting','approved'),
    ('fc_prioryear_count','numeric','Incident count for the same month one year before the cutoff.',
     'CaseMaster','CrimeRegisteredDate','lag_12m','point','strict_pre_cutoff','normal',
     ARRAY['area_incident_forecast'],'null_ok','invalidate_on_source_change','forecasting','approved'),
    ('fc_last_value','numeric','Most recent observed monthly incident count (pre-cutoff).',
     'CaseMaster','CrimeRegisteredDate','last','point','strict_pre_cutoff','normal',
     ARRAY['area_incident_forecast'],'null_ok','invalidate_on_source_change','forecasting','approved'),
    ('fc_history_months','numeric','Number of observed months available (data sufficiency for abstention).',
     'CaseMaster','CrimeRegisteredDate','count_months','all','strict_pre_cutoff','normal',
     ARRAY['area_incident_forecast'],'null_ok','invalidate_on_source_change','forecasting','approved')
ON CONFLICT ("Name") DO NOTHING;

-- Approved schema binding those definitions (idempotent on SchemaName+Version).
DO $$
DECLARE
    v_ids JSONB;
BEGIN
    SELECT to_jsonb(array_agg("FeatureDefinitionID" ORDER BY "FeatureDefinitionID"))
      INTO v_ids
    FROM "FeatureDefinition"
    WHERE "Name" IN ('fc_recent_mean_incidents','fc_trend_slope','fc_seasonal_index',
                     'fc_prioryear_count','fc_last_value','fc_history_months');

    IF NOT EXISTS (SELECT 1 FROM "FeatureSchemaVersion"
                   WHERE "SchemaName" = 'forecast-area-incident' AND "Version" = '1') THEN
        INSERT INTO "FeatureSchemaVersion"
            ("SchemaName","Version","FeatureDefinitionIDs","Task","Status","ApprovedByActor","ApprovedAt")
        VALUES ('forecast-area-incident','1', COALESCE(v_ids, '[]'::jsonb),
                'area_incident_forecast','approved','datagen-system', now());
    END IF;
END$$;

-- =============================================================================
-- 3. Grants + RLS disabled/NO FORCE + verification (hackathon).
-- =============================================================================
DO $$
BEGIN
    IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'drishti_readonly') THEN
        EXECUTE 'GRANT SELECT ON "ForecastBacktest" TO drishti_readonly';
    END IF;
END$$;

SELECT fn_disable_rls_all_app();
SELECT fn_assert_rls_disabled();

COMMIT;

-- =============================================================================
-- End of migration 019.
-- =============================================================================
