-- =============================================================================
-- DRISHTI migration 022 — hackathon admin/governance, notifications/work,
--                          reports, saved filters, optional-RAG audit, and
--                          model independent-review / drift signals (Phase 15)
-- Target: PostgreSQL 15+ / AWS RDS PostgreSQL (ap-south-1)
-- Depends on: 005 (synthetic marker + RLS helpers + audit view),
--             006 (source/ingestion/evidence), 008 (ModelVersion governance),
--             police_fir_schema.sql (CaseMaster/Unit/District), fn_set_updated_at()
-- =============================================================================
--
-- Phase 15 finishes the hackathon-facing administration, observability,
-- reporting and (optional) approved-text knowledge assistant. Everything here is
-- SYNTHETIC-DEMO metadata:
--
--   * Retention / archival / evidence-expiry / legal-hold are CONFIGURATION +
--     COMPUTED STATE only. NOTHING in this migration deletes data. The only
--     expiry "actions" are flag/archive-flag/review — never destructive delete.
--   * Notifications carry a short, non-sensitive synthetic SUMMARY only. Bodies
--     never hold evidence content, full narratives, or personal identifiers
--     (enforced again in the API layer).
--   * Reports store a reproducible STRUCTURED source snapshot + a SHA-256 + a
--     Stratus object pointer + source/version citations. No uploaded-file bytes
--     are ever parsed (no OCR/extraction).
--   * The optional RAG assistant persists only DATA-MINIMIZED prompt/response/
--     audit metadata with an explicit synthetic retention window; it never logs
--     secrets or unrestricted evidence text.
--
-- RLS stays DISABLED + NO FORCE (hackathon). No RLS policies. Additive +
-- idempotent: safe to run repeatedly. No data is dropped.
-- =============================================================================

BEGIN;

-- =============================================================================
-- 1. RETENTION / ARCHIVAL / EVIDENCE-EXPIRY / LEGAL-HOLD (non-destructive)
-- =============================================================================

-- 1a. Retention policies — configuration for synthetic demonstration records.
--     ExpiryAction is intentionally NON-DESTRUCTIVE: flag / archive-flag /
--     review only. There is NO 'delete' option — the hackathon never auto-deletes.
CREATE TABLE IF NOT EXISTS "RetentionPolicy" (
    "RetentionPolicyID" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "Code"           VARCHAR NOT NULL UNIQUE,
    "Name"           VARCHAR NOT NULL,
    "AppliesTo"      VARCHAR NOT NULL,             -- case|evidence|audit|report|prediction|notification
    "RetentionDays"  INTEGER NOT NULL CHECK ("RetentionDays" > 0),
    "ArchiveAfterDays" INTEGER CHECK ("ArchiveAfterDays" IS NULL OR "ArchiveAfterDays" > 0),
    "ExpiryAction"   VARCHAR NOT NULL DEFAULT 'flag_only',
    "Description"    TEXT,
    "IsActive"       BOOLEAN NOT NULL DEFAULT TRUE,
    "IsSynthetic"    BOOLEAN NOT NULL DEFAULT TRUE,
    "CreatedByActor" VARCHAR,
    "CreatedAt"      TIMESTAMPTZ NOT NULL DEFAULT now(),
    "UpdatedAt"      TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT "chk_retention_appliesto" CHECK ("AppliesTo" IN
        ('case','evidence','audit','report','prediction','notification')),
    -- Non-destructive by construction: no 'delete'/'purge' action is permitted.
    CONSTRAINT "chk_retention_action" CHECK ("ExpiryAction" IN
        ('flag_only','archive_flag','review_required'))
);
COMMENT ON TABLE "RetentionPolicy" IS
    'Synthetic-demo retention/archival config. Non-destructive: ExpiryAction never deletes (flag/archive-flag/review only).';

-- 1b. Legal holds — block expiry/archival for a subject (case/evidence).
CREATE TABLE IF NOT EXISTS "LegalHold" (
    "LegalHoldID"    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "SubjectKind"    VARCHAR NOT NULL,             -- case|evidence
    "SubjectRefID"   VARCHAR NOT NULL,             -- CaseMasterID / EvidenceItemID as text
    "Reason"         TEXT NOT NULL,
    "Status"         VARCHAR NOT NULL DEFAULT 'active',   -- active|released
    "PlacedByActor"  VARCHAR,
    "PlacedAt"       TIMESTAMPTZ NOT NULL DEFAULT now(),
    "ReleasedByActor" VARCHAR,
    "ReleasedAt"     TIMESTAMPTZ,
    "IsSynthetic"    BOOLEAN NOT NULL DEFAULT TRUE,
    CONSTRAINT "chk_legalhold_subject" CHECK ("SubjectKind" IN ('case','evidence')),
    CONSTRAINT "chk_legalhold_status"  CHECK ("Status" IN ('active','released'))
);
COMMENT ON TABLE "LegalHold" IS
    'Legal hold on a synthetic case/evidence subject. An active hold blocks any expiry/archival flag (never destructive).';
CREATE INDEX IF NOT EXISTS "idx_legalhold_subject"
    ON "LegalHold" ("SubjectKind", "SubjectRefID");
CREATE INDEX IF NOT EXISTS "idx_legalhold_status" ON "LegalHold" ("Status");

-- =============================================================================
-- 2. NOTIFICATIONS / WORK (data-minimized synthetic summaries only)
-- =============================================================================

-- 2a. Per-actor notification preferences + escalation SLA.
CREATE TABLE IF NOT EXISTS "NotificationPreference" (
    "NotificationPreferenceID" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "ActorKey"       VARCHAR NOT NULL UNIQUE,      -- matches DemoActor.ActorKey / users.username
    "InApp"          BOOLEAN NOT NULL DEFAULT TRUE,
    "Email"          BOOLEAN NOT NULL DEFAULT FALSE,
    "Push"           BOOLEAN NOT NULL DEFAULT FALSE,
    "DigestFrequency" VARCHAR NOT NULL DEFAULT 'immediate',  -- immediate|hourly|daily
    "EscalationSlaHours" INTEGER NOT NULL DEFAULT 24 CHECK ("EscalationSlaHours" > 0),
    "UpdatedAt"      TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT "chk_notifpref_digest" CHECK ("DigestFrequency" IN ('immediate','hourly','daily'))
);
COMMENT ON TABLE "NotificationPreference" IS
    'Per demo-actor notification channel toggles + escalation SLA. Channels: in-app/email/push (synthetic summaries only).';

-- 2b. Work tasks — optional case/evidence/review assignments with SLA/due state.
CREATE TABLE IF NOT EXISTS "WorkTask" (
    "WorkTaskID"     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "TaskType"       VARCHAR NOT NULL,             -- case_review|evidence_review|prediction_review|entity_review|general
    "Title"          VARCHAR NOT NULL,             -- SHORT non-sensitive synthetic summary
    "RelatedResource" VARCHAR,                     -- logical resource name (e.g. 'case')
    "RelatedResourceID" VARCHAR,                   -- id as text (no PII)
    "CaseMasterID"   INTEGER REFERENCES "CaseMaster" ("CaseMasterID"),
    "UnitID"         INTEGER REFERENCES "Unit" ("UnitID"),
    "AssigneeActor"  VARCHAR,
    "AssignedByActor" VARCHAR,
    "Priority"       VARCHAR NOT NULL DEFAULT 'medium',    -- low|medium|high
    "Status"         VARCHAR NOT NULL DEFAULT 'open',      -- open|in_progress|done|escalated|cancelled
    "DueAt"          TIMESTAMPTZ,
    "EscalationSlaHours" INTEGER CHECK ("EscalationSlaHours" IS NULL OR "EscalationSlaHours" > 0),
    "EscalatedAt"    TIMESTAMPTZ,
    "IsSynthetic"    BOOLEAN NOT NULL DEFAULT TRUE,
    "CreatedAt"      TIMESTAMPTZ NOT NULL DEFAULT now(),
    "UpdatedAt"      TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT "chk_worktask_type" CHECK ("TaskType" IN
        ('case_review','evidence_review','prediction_review','entity_review','general')),
    CONSTRAINT "chk_worktask_priority" CHECK ("Priority" IN ('low','medium','high')),
    CONSTRAINT "chk_worktask_status" CHECK ("Status" IN
        ('open','in_progress','done','escalated','cancelled'))
);
COMMENT ON TABLE "WorkTask" IS
    'Optional synthetic task assignments (case/evidence/review). Title is a short non-sensitive summary — never evidence content or narrative.';
CREATE INDEX IF NOT EXISTS "idx_worktask_assignee" ON "WorkTask" ("AssigneeActor");
CREATE INDEX IF NOT EXISTS "idx_worktask_status"   ON "WorkTask" ("Status");
CREATE INDEX IF NOT EXISTS "idx_worktask_case"     ON "WorkTask" ("CaseMasterID");
CREATE INDEX IF NOT EXISTS "idx_worktask_due"      ON "WorkTask" ("DueAt");

-- 2c. Notification messages — the data-minimized summary a recipient sees.
CREATE TABLE IF NOT EXISTS "NotificationMessage" (
    "NotificationMessageID" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "NotificationType" VARCHAR NOT NULL,           -- task_assigned|task_due|task_escalated|report_ready|prediction_reviewed|source_reconcile|system
    "RecipientActor" VARCHAR NOT NULL,
    "Summary"        VARCHAR NOT NULL,             -- short non-sensitive synthetic summary
    "Severity"       VARCHAR NOT NULL DEFAULT 'info',   -- info|warning|action_required
    "RelatedResource" VARCHAR,
    "RelatedResourceID" VARCHAR,
    "WorkTaskID"     BIGINT REFERENCES "WorkTask" ("WorkTaskID") ON DELETE SET NULL,
    "ReadAt"         TIMESTAMPTZ,
    "CreatedAt"      TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT "chk_notifmsg_type" CHECK ("NotificationType" IN
        ('task_assigned','task_due','task_escalated','report_ready',
         'prediction_reviewed','source_reconcile','system')),
    CONSTRAINT "chk_notifmsg_severity" CHECK ("Severity" IN ('info','warning','action_required'))
);
COMMENT ON TABLE "NotificationMessage" IS
    'In-app notification (data-minimized). Summary holds NO evidence content, full narrative, or personal identifiers.';
CREATE INDEX IF NOT EXISTS "idx_notifmsg_recipient" ON "NotificationMessage" ("RecipientActor");
CREATE INDEX IF NOT EXISTS "idx_notifmsg_created"   ON "NotificationMessage" ("CreatedAt");

-- 2d. Delivery history — one row per channel attempt.
CREATE TABLE IF NOT EXISTS "NotificationDelivery" (
    "NotificationDeliveryID" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "NotificationMessageID" BIGINT NOT NULL
        REFERENCES "NotificationMessage" ("NotificationMessageID") ON DELETE CASCADE,
    "Channel"        VARCHAR NOT NULL,             -- in_app|email|push
    "Provider"       VARCHAR NOT NULL DEFAULT 'in_app',  -- in_app|catalyst_mail|catalyst_push|none
    "Status"         VARCHAR NOT NULL DEFAULT 'queued',  -- queued|sent|failed|suppressed
    "Detail"         JSONB NOT NULL DEFAULT '{}'::jsonb, -- non-sensitive status detail only
    "CreatedAt"      TIMESTAMPTZ NOT NULL DEFAULT now(),
    "DeliveredAt"    TIMESTAMPTZ,
    CONSTRAINT "chk_notifdelivery_channel"  CHECK ("Channel" IN ('in_app','email','push')),
    CONSTRAINT "chk_notifdelivery_provider" CHECK ("Provider" IN
        ('in_app','catalyst_mail','catalyst_push','none')),
    CONSTRAINT "chk_notifdelivery_status"   CHECK ("Status" IN ('queued','sent','failed','suppressed'))
);
COMMENT ON TABLE "NotificationDelivery" IS
    'Per-channel delivery history (in-app/email/push). Detail holds status only — never message body PII.';
CREATE INDEX IF NOT EXISTS "idx_notifdelivery_msg"
    ON "NotificationDelivery" ("NotificationMessageID");

-- =============================================================================
-- 3. REPORTS (structured-field generation, watermark, reproducible snapshot)
-- =============================================================================

-- 3a. Report templates — role-appropriate configurable templates.
CREATE TABLE IF NOT EXISTS "ReportTemplate" (
    "ReportTemplateID" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "Code"           VARCHAR NOT NULL UNIQUE,
    "Name"           VARCHAR NOT NULL,
    "Description"    TEXT,
    "ReportKind"     VARCHAR NOT NULL,             -- case_summary|unit_activity|district_dashboard|model_governance|audit_extract
    "ScopeKind"      VARCHAR NOT NULL DEFAULT 'global',  -- case|unit|district|global
    "AllowedRoles"   TEXT[] NOT NULL DEFAULT '{}',
    "ConfigSchema"   JSONB NOT NULL DEFAULT '{}'::jsonb, -- configurable field/filter descriptor
    "IsActive"       BOOLEAN NOT NULL DEFAULT TRUE,
    "IsSynthetic"    BOOLEAN NOT NULL DEFAULT TRUE,
    "CreatedByActor" VARCHAR,
    "CreatedAt"      TIMESTAMPTZ NOT NULL DEFAULT now(),
    "UpdatedAt"      TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT "chk_reporttemplate_kind" CHECK ("ReportKind" IN
        ('case_summary','unit_activity','district_dashboard','model_governance','audit_extract')),
    CONSTRAINT "chk_reporttemplate_scope" CHECK ("ScopeKind" IN
        ('case','unit','district','global'))
);
COMMENT ON TABLE "ReportTemplate" IS
    'Role-appropriate configurable report templates. Reports are generated from structured DB fields only (no OCR/file parsing).';

-- 3b. Report snapshots — reproducible, hashed, watermarked, Stratus-backed.
CREATE TABLE IF NOT EXISTS "ReportSnapshot" (
    "ReportSnapshotID" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "ReportTemplateID" INTEGER REFERENCES "ReportTemplate" ("ReportTemplateID"),
    "Title"          VARCHAR NOT NULL,
    "RequestedByActor" VARCHAR,
    "RequestedByRole"  VARCHAR,
    "ScopeKind"      VARCHAR NOT NULL DEFAULT 'global',
    "ScopeRefID"     VARCHAR,                       -- CaseMasterID/UnitID/DistrictID as text
    "Filters"        JSONB NOT NULL DEFAULT '{}'::jsonb,
    "SourceSnapshot" JSONB NOT NULL DEFAULT '{}'::jsonb,  -- exact structured data the report was built from
    "SourceCitations" JSONB NOT NULL DEFAULT '[]'::jsonb, -- [{source, version, ...}] provenance
    "ContentHash"    VARCHAR NOT NULL,             -- sha256 of the canonicalised source snapshot
    "Watermark"      VARCHAR NOT NULL DEFAULT 'Synthetic Hackathon Demo',
    "StratusBucket"  VARCHAR,                       -- logical bucket (report)
    "StratusObjectKey" VARCHAR,
    "StratusVersionId" VARCHAR,
    "ObjectSha256"   VARCHAR,                       -- sha256 of the rendered PDF object
    "ObjectSizeBytes" BIGINT CHECK ("ObjectSizeBytes" IS NULL OR "ObjectSizeBytes" >= 0),
    "ContentType"    VARCHAR,
    "RenderBackend"  VARCHAR,                       -- smartbrowz|appsail_fallback
    "Status"         VARCHAR NOT NULL DEFAULT 'generated',  -- generated|failed
    "Version"        INTEGER NOT NULL DEFAULT 1,
    "ExpiresAt"      TIMESTAMPTZ,                    -- retention (non-destructive; informational)
    "IsSynthetic"    BOOLEAN NOT NULL DEFAULT TRUE,
    "CreatedAt"      TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT "chk_reportsnapshot_scope"  CHECK ("ScopeKind" IN ('case','unit','district','global')),
    CONSTRAINT "chk_reportsnapshot_status" CHECK ("Status" IN ('generated','failed'))
);
COMMENT ON TABLE "ReportSnapshot" IS
    'Generated report: reproducible structured source snapshot + SHA-256 + Stratus object pointer + source/version citations + synthetic watermark. Audited.';
CREATE INDEX IF NOT EXISTS "idx_reportsnapshot_template" ON "ReportSnapshot" ("ReportTemplateID");
CREATE INDEX IF NOT EXISTS "idx_reportsnapshot_scope"    ON "ReportSnapshot" ("ScopeKind", "ScopeRefID");
CREATE INDEX IF NOT EXISTS "idx_reportsnapshot_created"  ON "ReportSnapshot" ("CreatedAt");

-- =============================================================================
-- 4. SAVED DASHBOARD / REPORT FILTERS
-- =============================================================================
CREATE TABLE IF NOT EXISTS "SavedFilter" (
    "SavedFilterID"  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "OwnerActor"     VARCHAR NOT NULL,
    "Scope"          VARCHAR NOT NULL DEFAULT 'dashboard',  -- dashboard|report|cases|map
    "Name"           VARCHAR NOT NULL,
    "FilterJSON"     JSONB NOT NULL DEFAULT '{}'::jsonb,
    "IsShared"       BOOLEAN NOT NULL DEFAULT FALSE,
    "CreatedAt"      TIMESTAMPTZ NOT NULL DEFAULT now(),
    "UpdatedAt"      TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT "chk_savedfilter_scope" CHECK ("Scope" IN ('dashboard','report','cases','map')),
    CONSTRAINT "uq_savedfilter" UNIQUE ("OwnerActor", "Scope", "Name")
);
COMMENT ON TABLE "SavedFilter" IS
    'Saved dashboard/report filters (per demo actor; optionally shared). Synthetic demo state only.';
CREATE INDEX IF NOT EXISTS "idx_savedfilter_owner" ON "SavedFilter" ("OwnerActor");

-- =============================================================================
-- 5. OPTIONAL RAG — data-minimized prompt/response/audit metadata + retention
-- =============================================================================
CREATE TABLE IF NOT EXISTS "RagInteraction" (
    "RagInteractionID" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "Actor"          VARCHAR,
    "Role"           VARCHAR,
    "QuestionHash"   VARCHAR,                       -- sha256 of the question (not the raw text)
    "QuestionPreview" VARCHAR,                      -- short, sanitised, capped preview only
    "AnswerCitations" JSONB NOT NULL DEFAULT '[]'::jsonb, -- approved-source refs only
    "Refused"        BOOLEAN NOT NULL DEFAULT FALSE,
    "KnowledgeBaseVersion" VARCHAR,
    "CaseScopeRefID" VARCHAR,
    "UnitScopeRefID" VARCHAR,
    "LatencyMs"      INTEGER,
    "RetentionDays"  INTEGER NOT NULL DEFAULT 30 CHECK ("RetentionDays" > 0),
    "ExpiresAt"      TIMESTAMPTZ,
    "IsSynthetic"    BOOLEAN NOT NULL DEFAULT TRUE,
    "CreatedAt"      TIMESTAMPTZ NOT NULL DEFAULT now()
);
COMMENT ON TABLE "RagInteraction" IS
    'Optional-RAG audit: DATA-MINIMIZED prompt/response metadata + citations + refusal + explicit synthetic retention. Never stores secrets or unrestricted evidence text.';
CREATE INDEX IF NOT EXISTS "idx_raginteraction_created" ON "RagInteraction" ("CreatedAt");

-- =============================================================================
-- 6. FEATURE FLAGS (admin-visible; env-driven flags are surfaced by the API)
-- =============================================================================
CREATE TABLE IF NOT EXISTS "FeatureFlag" (
    "FeatureFlagID"  INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "Key"            VARCHAR NOT NULL UNIQUE,
    "Enabled"        BOOLEAN NOT NULL DEFAULT FALSE,
    "Category"       VARCHAR NOT NULL DEFAULT 'admin',  -- rag|notifications|reports|admin|ml
    "Description"    TEXT,
    "UpdatedByActor" VARCHAR,
    "UpdatedAt"      TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT "chk_featureflag_category" CHECK ("Category" IN
        ('rag','notifications','reports','admin','ml'))
);
COMMENT ON TABLE "FeatureFlag" IS
    'Admin feature flags (synthetic demo). Some capabilities (RAG, Mail/Push) are ALSO gated by server env; the API reports both.';

-- =============================================================================
-- 7. MODEL INDEPENDENT-REVIEW / DRIFT-QUALITY SIGNALS
-- =============================================================================
CREATE TABLE IF NOT EXISTS "ModelReview" (
    "ModelReviewID"  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "ModelVersionID" INTEGER NOT NULL REFERENCES "ModelVersion" ("ModelVersionID") ON DELETE CASCADE,
    "ReviewKind"     VARCHAR NOT NULL DEFAULT 'independent',  -- independent|drift|quality
    "Status"         VARCHAR NOT NULL DEFAULT 'due',          -- due|in_progress|completed|overdue|waived
    "DueAt"          TIMESTAMPTZ,
    "ReviewerActor"  VARCHAR,
    "Findings"       JSONB NOT NULL DEFAULT '{}'::jsonb,
    "DriftSignal"    JSONB NOT NULL DEFAULT '{}'::jsonb,      -- e.g. {metric: 'wape', baseline, current, delta}
    "CompletedAt"    TIMESTAMPTZ,
    "CreatedAt"      TIMESTAMPTZ NOT NULL DEFAULT now(),
    "UpdatedAt"      TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT "chk_modelreview_kind"   CHECK ("ReviewKind" IN ('independent','drift','quality')),
    CONSTRAINT "chk_modelreview_status" CHECK ("Status" IN
        ('due','in_progress','completed','overdue','waived')),
    CONSTRAINT "uq_modelreview_kind" UNIQUE ("ModelVersionID", "ReviewKind")
);
COMMENT ON TABLE "ModelReview" IS
    'Periodic independent-review due state + drift/quality signals per ModelVersion. Investigation-support governance only.';
CREATE INDEX IF NOT EXISTS "idx_modelreview_model"  ON "ModelReview" ("ModelVersionID");
CREATE INDEX IF NOT EXISTS "idx_modelreview_status" ON "ModelReview" ("Status");

-- =============================================================================
-- 8. RECONCILIATION / STATE VIEWS (read models over existing + new tables)
-- =============================================================================

-- 8a. Source reconciliation status per source system.
CREATE OR REPLACE VIEW "vw_source_reconciliation" AS
SELECT
    ss."SourceSystemID",
    ss."Code",
    ss."Name",
    ss."Kind",
    COUNT(DISTINCT sr."SourceRecordID")                                    AS "TotalSourceRecords",
    COUNT(DISTINCT sr."SourceRecordID") FILTER (WHERE sr."Status" = 'committed') AS "CommittedRecords",
    COUNT(DISTINCT sr."SourceRecordID") FILTER (WHERE sr."Status" = 'rejected')  AS "RejectedRecords",
    COUNT(DISTINCT sr."SourceRecordID") FILTER (WHERE sr."Status" = 'duplicate') AS "DuplicateRecords",
    COUNT(DISTINCT sr."SourceRecordID") FILTER (WHERE sr."Status" IN ('received','staged')) AS "PendingRecords",
    COUNT(DISTINCT ij."IngestionJobID")                                    AS "TotalJobs",
    COUNT(DISTINCT ij."IngestionJobID") FILTER (WHERE ij."Status" = 'partial') AS "PartialJobs",
    COUNT(DISTINCT ij."IngestionJobID") FILTER (WHERE ij."Status" = 'failed')  AS "FailedJobs",
    MAX(sr."ReceivedAt")                                                    AS "LastReceivedAt"
FROM "SourceSystem" ss
LEFT JOIN "SourceRecord" sr ON sr."SourceSystemID" = ss."SourceSystemID"
LEFT JOIN "IngestionJob" ij ON ij."SourceSystemID" = ss."SourceSystemID"
GROUP BY ss."SourceSystemID", ss."Code", ss."Name", ss."Kind";
COMMENT ON VIEW "vw_source_reconciliation" IS
    'Per-source reconciliation status: committed/rejected/duplicate/pending source records + partial/failed jobs.';

-- 8b. Evidence retention/expiry state (NON-DESTRUCTIVE computed state).
--     Uses the active evidence RetentionPolicy with the smallest RetentionDays.
CREATE OR REPLACE VIEW "vw_evidence_retention" AS
WITH pol AS (
    SELECT "RetentionDays", "ArchiveAfterDays", "ExpiryAction"
    FROM "RetentionPolicy"
    WHERE "AppliesTo" = 'evidence' AND "IsActive"
    ORDER BY "RetentionDays" ASC
    LIMIT 1
)
SELECT
    ei."EvidenceItemID",
    ei."CaseMasterID",
    ei."State",
    ei."Confidentiality",
    ei."CreatedAt",
    (SELECT "RetentionDays" FROM pol)  AS "RetentionDays",
    (SELECT "ExpiryAction"  FROM pol)  AS "ExpiryAction",
    CASE WHEN (SELECT "RetentionDays" FROM pol) IS NOT NULL
         THEN ei."CreatedAt" + ((SELECT "RetentionDays" FROM pol) || ' days')::interval
    END AS "ExpiresAt",
    CASE WHEN (SELECT "ArchiveAfterDays" FROM pol) IS NOT NULL
         THEN ei."CreatedAt" + ((SELECT "ArchiveAfterDays" FROM pol) || ' days')::interval
    END AS "ArchiveDueAt",
    EXISTS (
        SELECT 1 FROM "LegalHold" lh
        WHERE lh."SubjectKind" = 'evidence'
          AND lh."SubjectRefID" = ei."EvidenceItemID"::text
          AND lh."Status" = 'active'
    ) AS "OnLegalHold",
    (
        (SELECT "RetentionDays" FROM pol) IS NOT NULL
        AND now() > ei."CreatedAt" + ((SELECT "RetentionDays" FROM pol) || ' days')::interval
        AND NOT EXISTS (
            SELECT 1 FROM "LegalHold" lh
            WHERE lh."SubjectKind" = 'evidence'
              AND lh."SubjectRefID" = ei."EvidenceItemID"::text
              AND lh."Status" = 'active'
        )
    ) AS "ExpiryFlagged"
FROM "EvidenceItem" ei;
COMMENT ON VIEW "vw_evidence_retention" IS
    'Computed (non-destructive) evidence expiry/archival state. ExpiryFlagged is a FLAG only; an active LegalHold always suppresses it. Nothing is ever deleted.';

-- 8c. Evidence quarantine / security-scan queue (NO OCR/extraction queue).
CREATE OR REPLACE VIEW "vw_evidence_quarantine_queue" AS
SELECT
    eo."EvidenceObjectID",
    eo."EvidenceItemID",
    ei."Title",
    ei."CaseMasterID",
    eo."StorageStatus",
    eo."FileName",
    eo."MimeType",
    eo."SizeBytes",
    eo."Sha256",
    eo."CreatedAt"
FROM "EvidenceObject" eo
JOIN "EvidenceItem" ei ON ei."EvidenceItemID" = eo."EvidenceItemID"
WHERE eo."StorageStatus" IN ('quarantined','missing','failed');
COMMENT ON VIEW "vw_evidence_quarantine_queue" IS
    'Evidence objects awaiting security-scan clearance / repair. Security control only — NO OCR/transcription/semantic extraction.';

-- 8d. Model review-due read model (joins governance ModelVersion + ModelReview).
CREATE OR REPLACE VIEW "vw_model_review_due" AS
SELECT
    mv."ModelVersionID",
    mv."ModelName",
    mv."Version",
    mv."ApprovalStatus",
    mv."Environment",
    mv."ApprovedAt",
    mr."ModelReviewID",
    mr."ReviewKind",
    mr."Status"      AS "ReviewStatus",
    mr."DueAt",
    mr."DriftSignal",
    CASE
        WHEN mr."ModelReviewID" IS NULL THEN 'no_review_scheduled'
        WHEN mr."Status" IN ('completed','waived') THEN mr."Status"
        WHEN mr."DueAt" IS NOT NULL AND now() > mr."DueAt" THEN 'overdue'
        ELSE mr."Status"
    END AS "EffectiveReviewState"
FROM "ModelVersion" mv
LEFT JOIN "ModelReview" mr ON mr."ModelVersionID" = mv."ModelVersionID"
WHERE mv."ApprovalStatus" IS NOT NULL;
COMMENT ON VIEW "vw_model_review_due" IS
    'Model lifecycle review-due state (independent review + drift/quality) over governed ModelVersions.';

-- =============================================================================
-- 9. SEED synthetic-demo configuration (idempotent)
-- =============================================================================

-- 9a. Default non-destructive retention policies.
INSERT INTO "RetentionPolicy" ("Code","Name","AppliesTo","RetentionDays","ArchiveAfterDays","ExpiryAction","Description","CreatedByActor") VALUES
    ('CASE_STD',   'Case records (demo)',        'case',       3650, 1825, 'review_required', 'Synthetic case retention — flag for review, never auto-delete.', 'system'),
    ('EVID_STD',   'Digital evidence (demo)',    'evidence',   1825,  730, 'archive_flag',    'Synthetic evidence retention — archive flag only; legal hold overrides.', 'system'),
    ('AUDIT_STD',  'Audit log (demo)',           'audit',      3650, NULL, 'flag_only',       'Synthetic audit retention — flag only.', 'system'),
    ('REPORT_STD', 'Generated reports (demo)',   'report',      365,  180, 'flag_only',       'Synthetic report object retention — flag only.', 'system')
ON CONFLICT ("Code") DO NOTHING;

-- 9b. Report templates. INTERIM ("all roles have access to everything"): every
-- seeded command role is allowed on every template, so AllowedRoles is derived
-- from the seeded "roles" table instead of a hard-coded per-template list.
INSERT INTO "ReportTemplate" ("Code","Name","Description","ReportKind","ScopeKind","AllowedRoles","ConfigSchema","CreatedByActor") VALUES
    ('CASE_SUMMARY', 'Case summary', 'Structured single-case summary from database fields (no file parsing).',
        'case_summary', 'case', ARRAY(SELECT "role_name" FROM "roles" ORDER BY "role_id"),
        '{"sections":["identity","classification","status","timeline_counts"],"citations":true}'::jsonb, 'system'),
    ('UNIT_ACTIVITY', 'Unit activity', 'Station/unit activity summary from structured case counts.',
        'unit_activity', 'unit', ARRAY(SELECT "role_name" FROM "roles" ORDER BY "role_id"),
        '{"sections":["case_counts","status_breakdown"],"citations":true}'::jsonb, 'system'),
    ('DISTRICT_DASHBOARD', 'District dashboard', 'District-level aggregate dashboard export.',
        'district_dashboard', 'district', ARRAY(SELECT "role_name" FROM "roles" ORDER BY "role_id"),
        '{"sections":["aggregate_counts","category_breakdown"],"citations":true}'::jsonb, 'system'),
    ('MODEL_GOVERNANCE', 'Model governance', 'Model registry + review-due governance extract.',
        'model_governance', 'global', ARRAY(SELECT "role_name" FROM "roles" ORDER BY "role_id"),
        '{"sections":["models","review_due"],"citations":true}'::jsonb, 'system'),
    ('AUDIT_EXTRACT', 'Audit extract', 'Filtered audit-event extract.',
        'audit_extract', 'global', ARRAY(SELECT "role_name" FROM "roles" ORDER BY "role_id"),
        '{"sections":["audit_events"],"citations":true}'::jsonb, 'system')
ON CONFLICT ("Code") DO NOTHING;

-- 9c. Feature flags mirroring the optional capabilities (default OFF where env-gated).
INSERT INTO "FeatureFlag" ("Key","Enabled","Category","Description","UpdatedByActor") VALUES
    ('rag_assistant',      FALSE, 'rag',           'Optional approved-text QuickML RAG assistant. Also requires DRISHTI_QUICKML_RAG_ENABLED.', 'system'),
    ('notifications_email', FALSE, 'notifications', 'Catalyst Mail delivery for synthetic summaries. Also requires DRISHTI_NOTIFY_ENABLED.', 'system'),
    ('notifications_push',  FALSE, 'notifications', 'Catalyst Push delivery for synthetic summaries. Also requires DRISHTI_NOTIFY_ENABLED.', 'system'),
    ('reports_smartbrowz',  TRUE,  'reports',       'Use Catalyst SmartBrowz for report rendering (else AppSail fallback).', 'system'),
    ('signals_enabled',     TRUE,  'admin',         'Publish Catalyst Signals (report.ready/prediction.reviewed/notification) after Data Store commit.', 'system')
ON CONFLICT ("Key") DO NOTHING;

-- 9d. Notification preferences for existing synthetic demo actors (in-app on).
INSERT INTO "NotificationPreference" ("ActorKey")
SELECT "ActorKey" FROM "DemoActor"
ON CONFLICT ("ActorKey") DO NOTHING;

-- 9e. One independent-review row per approved governed model (idempotent).
--     Due 180 days after approval; already-overdue rows are surfaced by the view.
INSERT INTO "ModelReview" ("ModelVersionID","ReviewKind","Status","DueAt")
SELECT mv."ModelVersionID", 'independent', 'due',
       COALESCE(mv."ApprovedAt", now()) + interval '180 days'
FROM "ModelVersion" mv
WHERE mv."ApprovalStatus" = 'approved'
ON CONFLICT ("ModelVersionID","ReviewKind") DO NOTHING;

-- =============================================================================
-- 10. TRIGGERS (updated_at maintenance — reuse shared fn_set_updated_at())
-- =============================================================================
DO $$
DECLARE
    tbl TEXT;
    trg TEXT;
BEGIN
    FOREACH tbl IN ARRAY ARRAY[
        'RetentionPolicy','WorkTask','ReportTemplate','SavedFilter','ModelReview'
    ] LOOP
        trg := 'trg_' || lower(tbl) || '_updated';
        IF NOT EXISTS (SELECT 1 FROM pg_trigger WHERE tgname = trg) THEN
            EXECUTE format(
                'CREATE TRIGGER %I BEFORE UPDATE ON %I FOR EACH ROW EXECUTE FUNCTION fn_set_updated_at()',
                trg, tbl);
        END IF;
    END LOOP;
END$$;

-- =============================================================================
-- 11. Grants (read-only role) + RLS disabled/NO FORCE + global verification.
-- =============================================================================
DO $$
DECLARE t TEXT;
BEGIN
    IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'drishti_readonly') THEN
        FOREACH t IN ARRAY ARRAY[
            'RetentionPolicy','LegalHold','NotificationPreference','WorkTask',
            'NotificationMessage','NotificationDelivery','ReportTemplate',
            'ReportSnapshot','SavedFilter','RagInteraction','FeatureFlag','ModelReview'
        ] LOOP
            EXECUTE format('GRANT SELECT ON %I TO drishti_readonly', t);
        END LOOP;
        GRANT SELECT ON "vw_source_reconciliation"    TO drishti_readonly;
        GRANT SELECT ON "vw_evidence_retention"       TO drishti_readonly;
        GRANT SELECT ON "vw_evidence_quarantine_queue" TO drishti_readonly;
        GRANT SELECT ON "vw_model_review_due"         TO drishti_readonly;
    END IF;
END$$;

SELECT fn_disable_rls_all_app();
SELECT fn_assert_rls_disabled();

COMMIT;

-- =============================================================================
-- End of migration 022.
-- =============================================================================
