-- =============================================================================
-- DRISHTI migration 025 — face recognition (biometric gallery + probe audit)
-- Target: PostgreSQL 15+ / AWS RDS PostgreSQL (ap-south-1)
-- Depends on: police_fir_intelligence.sql (ModelVersion, vector extension),
--             006 (EvidenceItem/EvidenceObject),
--             007 (CanonicalPerson, CanonicalEntity, EntityResolutionCandidate)
-- =============================================================================
--
-- Adds a 1:N face-search capability over the CANONICAL person layer:
--
--   1. "PersonFaceEmbedding" — the gallery. One row per enrolled face crop of a
--      canonical person: a 512-dim ArcFace-style descriptor plus detector
--      geometry/quality and the source evidence object. HNSW + vector_cosine_ops
--      mirrors CrimeEmbedding so 1:N search is an ANN scan, not a table scan.
--   2. "FaceSearchProbe" — one row per SEARCH (the uploaded/captured photo).
--      Biometric searches are a sensitive action, so every probe is recorded
--      with actor, role, the image hash, how many faces were found and what the
--      top score was. The probe descriptor is retained so a later "yes, this is
--      them" decision can enrol without re-uploading the photo.
--   3. "FaceProbeMatch" — the ranked candidate list a probe returned, so the
--      shortlist an officer actually saw is reconstructable after the fact.
--
-- GOVERNANCE — this is the important part of the design:
--   * A face score NEVER asserts identity. Confirming a match writes an
--     "EntityResolutionCandidate" (Method='face') for human review, exactly like
--     every other matching signal in this schema. Nothing auto-merges.
--   * Descriptors are Sensitivity='restricted' and are ANALYTICS_ONLY: they stay
--     in RDS and are never mirrored to the Catalyst Data Store.
--   * Cross-model comparison is meaningless, so every search is scoped to one
--     "ModelVersionID". The dimension is fixed at 512 and must match the
--     deployed encoder's EmbeddingDim.
--   * Deleting a person cascades their biometrics away (ON DELETE CASCADE).
--
-- HACKATHON SCOPE: synthetic data only. RLS stays DISABLED (no policies).
-- Additive + idempotent: safe to re-run.
-- =============================================================================

BEGIN;

CREATE EXTENSION IF NOT EXISTS vector;

-- =============================================================================
-- 1. GALLERY — enrolled face descriptors per canonical person
-- =============================================================================
CREATE TABLE IF NOT EXISTS "PersonFaceEmbedding" (
    "PersonFaceEmbeddingID" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "CanonicalPersonID" BIGINT NOT NULL
        REFERENCES "CanonicalPerson" ("CanonicalPersonID") ON DELETE CASCADE,
    "ModelVersionID"    INTEGER NOT NULL REFERENCES "ModelVersion" ("ModelVersionID"),
    "Embedding"         vector(512) NOT NULL,   -- L2-normalised; cosine space
    -- provenance: the photo this descriptor came from (never the bytes)
    "EvidenceItemID"    BIGINT REFERENCES "EvidenceItem" ("EvidenceItemID") ON DELETE SET NULL,
    "EvidenceObjectID"  BIGINT REFERENCES "EvidenceObject" ("EvidenceObjectID") ON DELETE SET NULL,
    "SourceRecordID"    BIGINT REFERENCES "SourceRecord" ("SourceRecordID"),
    "ImageSha256"       VARCHAR NOT NULL,       -- sha256 of the source image bytes
    "ImageLabel"        VARCHAR,                -- e.g. 'arrest-photo-2024' (display only)
    -- detector geometry + quality, so a weak crop can be excluded from matching
    "BoundingBox"       JSONB NOT NULL DEFAULT '{}'::jsonb,  -- {x,y,w,h} in source px
    "DetectorScore"     NUMERIC(6,5) CHECK ("DetectorScore" IS NULL OR "DetectorScore" BETWEEN 0 AND 1),
    "QualityScore"      NUMERIC(6,5) CHECK ("QualityScore"  IS NULL OR "QualityScore"  BETWEEN 0 AND 1),
    "FaceCount"         INTEGER NOT NULL DEFAULT 1 CHECK ("FaceCount" >= 0),
    "IsPrimary"         BOOLEAN NOT NULL DEFAULT FALSE,  -- the person's reference photo
    "EnrolledByActor"   VARCHAR,
    "EnrolmentSource"   VARCHAR NOT NULL DEFAULT 'manual_upload',
    "Sensitivity"       VARCHAR NOT NULL DEFAULT 'restricted',
    "IsSynthetic"       BOOLEAN NOT NULL DEFAULT TRUE,
    "IsArchived"        BOOLEAN NOT NULL DEFAULT FALSE,
    "ArchivedAt"        TIMESTAMPTZ,
    "ArchiveReason"     VARCHAR,
    "CreatedAt"         TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT "chk_personface_source" CHECK ("EnrolmentSource" IN
        ('manual_upload','camera_capture','evidence_item','fixture_import','probe_confirmation')),
    CONSTRAINT "chk_personface_sensitivity" CHECK ("Sensitivity" IN
        ('public','demo_normal','restricted','protected'))
);
COMMENT ON TABLE "PersonFaceEmbedding" IS
    'Biometric face gallery: L2-normalised 512-dim descriptors per canonical person, scoped to one ModelVersion. Restricted sensitivity, ANALYTICS_ONLY (never mirrored to the Data Store). A high cosine score is a LEAD for human review, never an identity assertion.';
COMMENT ON COLUMN "PersonFaceEmbedding"."Embedding" IS
    'Unit-norm face descriptor. Only comparable within the same ModelVersionID; cross-model distances are meaningless.';

-- One descriptor per (person, image, model): re-enrolling the same photo is a
-- no-op instead of skewing the gallery with duplicates.
CREATE UNIQUE INDEX IF NOT EXISTS "uq_personface_person_image_model"
    ON "PersonFaceEmbedding" ("CanonicalPersonID", "ImageSha256", "ModelVersionID");

-- At most one reference photo per person.
CREATE UNIQUE INDEX IF NOT EXISTS "uq_personface_primary"
    ON "PersonFaceEmbedding" ("CanonicalPersonID")
    WHERE "IsPrimary" AND NOT "IsArchived";

CREATE INDEX IF NOT EXISTS "idx_personface_person"
    ON "PersonFaceEmbedding" ("CanonicalPersonID");
CREATE INDEX IF NOT EXISTS "idx_personface_live"
    ON "PersonFaceEmbedding" ("ModelVersionID") WHERE "IsArchived" = FALSE;
CREATE INDEX IF NOT EXISTS "idx_personface_evidence"
    ON "PersonFaceEmbedding" ("EvidenceItemID");

-- ANN index: same operator class as CrimeEmbedding so cosine `<=>` is indexed.
CREATE INDEX IF NOT EXISTS "hnsw_personface_vec"
    ON "PersonFaceEmbedding" USING hnsw ("Embedding" vector_cosine_ops);

-- =============================================================================
-- 2. PROBE AUDIT — one row per biometric search
-- =============================================================================
CREATE TABLE IF NOT EXISTS "FaceSearchProbe" (
    "FaceSearchProbeID" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "ProbeRef"          VARCHAR NOT NULL UNIQUE,   -- opaque handle returned to the client
    "ModelVersionID"    INTEGER NOT NULL REFERENCES "ModelVersion" ("ModelVersionID"),
    -- who searched, and from where in the product
    "Actor"             VARCHAR,
    "ActorRole"         VARCHAR,
    "RequestID"         VARCHAR,
    "Origin"            VARCHAR NOT NULL DEFAULT 'standalone',  -- intake_fir|standalone|case_file|person_page
    "IntakeDraftKey"    VARCHAR,
    "CaseMasterID"      INTEGER REFERENCES "CaseMaster" ("CaseMasterID"),
    -- what was searched (hash + geometry only; the image bytes are NOT stored)
    "ImageSha256"       VARCHAR NOT NULL,
    "ImageBytes"        BIGINT CHECK ("ImageBytes" IS NULL OR "ImageBytes" >= 0),
    "CaptureMode"       VARCHAR NOT NULL DEFAULT 'upload',      -- upload|camera
    "FacesDetected"     INTEGER NOT NULL DEFAULT 0 CHECK ("FacesDetected" >= 0),
    "BoundingBox"       JSONB NOT NULL DEFAULT '{}'::jsonb,
    "DetectorScore"     NUMERIC(6,5) CHECK ("DetectorScore" IS NULL OR "DetectorScore" BETWEEN 0 AND 1),
    "QualityScore"      NUMERIC(6,5) CHECK ("QualityScore"  IS NULL OR "QualityScore"  BETWEEN 0 AND 1),
    -- retained so a later confirmation can enrol without re-uploading the photo
    "Embedding"         vector(512),
    -- outcome
    "GallerySize"       INTEGER NOT NULL DEFAULT 0 CHECK ("GallerySize" >= 0),
    "MatchCount"        INTEGER NOT NULL DEFAULT 0 CHECK ("MatchCount" >= 0),
    "TopSimilarity"     NUMERIC(6,5) CHECK ("TopSimilarity" IS NULL OR "TopSimilarity" BETWEEN 0 AND 1),
    "TopCanonicalPersonID" BIGINT REFERENCES "CanonicalPerson" ("CanonicalPersonID"),
    "Threshold"         NUMERIC(6,5) CHECK ("Threshold" IS NULL OR "Threshold" BETWEEN 0 AND 1),
    "Decision"          VARCHAR NOT NULL DEFAULT 'pending',
    "DecidedCanonicalPersonID" BIGINT REFERENCES "CanonicalPerson" ("CanonicalPersonID"),
    "DecidedByActor"    VARCHAR,
    "DecidedAt"         TIMESTAMPTZ,
    "LatencyMs"         INTEGER CHECK ("LatencyMs" IS NULL OR "LatencyMs" >= 0),
    "IsSynthetic"       BOOLEAN NOT NULL DEFAULT TRUE,
    "CreatedAt"         TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT "chk_faceprobe_capture" CHECK ("CaptureMode" IN ('upload','camera')),
    CONSTRAINT "chk_faceprobe_origin"  CHECK ("Origin" IN
        ('intake_fir','standalone','case_file','person_page','enrolment')),
    CONSTRAINT "chk_faceprobe_decision" CHECK ("Decision" IN
        ('pending','no_match','confirmed','rejected','new_person'))
);
COMMENT ON TABLE "FaceSearchProbe" IS
    'Append-only audit of every biometric face search: who searched, the image hash (never the bytes), the shortlist size and the human decision. The probe descriptor is retained so a confirmation can enrol without re-upload.';
COMMENT ON COLUMN "FaceSearchProbe"."Decision" IS
    'Human disposition of the shortlist. ''pending'' until an officer acts; ''confirmed'' also raises an EntityResolutionCandidate for review — it does not merge identities.';

CREATE INDEX IF NOT EXISTS "idx_faceprobe_created"    ON "FaceSearchProbe" ("CreatedAt" DESC);
CREATE INDEX IF NOT EXISTS "idx_faceprobe_actor"      ON "FaceSearchProbe" ("Actor");
CREATE INDEX IF NOT EXISTS "idx_faceprobe_draft"      ON "FaceSearchProbe" ("IntakeDraftKey");
CREATE INDEX IF NOT EXISTS "idx_faceprobe_case"       ON "FaceSearchProbe" ("CaseMasterID");
CREATE INDEX IF NOT EXISTS "idx_faceprobe_hash"       ON "FaceSearchProbe" ("ImageSha256");
CREATE INDEX IF NOT EXISTS "idx_faceprobe_decision"   ON "FaceSearchProbe" ("Decision");

-- =============================================================================
-- 3. PROBE SHORTLIST — the ranked candidates the officer actually saw
-- =============================================================================
CREATE TABLE IF NOT EXISTS "FaceProbeMatch" (
    "FaceProbeMatchID"  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "FaceSearchProbeID" BIGINT NOT NULL
        REFERENCES "FaceSearchProbe" ("FaceSearchProbeID") ON DELETE CASCADE,
    "CanonicalPersonID" BIGINT NOT NULL REFERENCES "CanonicalPerson" ("CanonicalPersonID"),
    "PersonFaceEmbeddingID" BIGINT
        REFERENCES "PersonFaceEmbedding" ("PersonFaceEmbeddingID") ON DELETE SET NULL,
    "RankOrder"   INTEGER NOT NULL CHECK ("RankOrder" >= 1),
    "Similarity"  NUMERIC(6,5) NOT NULL CHECK ("Similarity" BETWEEN 0 AND 1),
    "Distance"    NUMERIC(9,6),
    "Band"        VARCHAR NOT NULL DEFAULT 'weak',   -- strong|probable|weak
    "CreatedAt"   TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT "uq_faceprobematch_rank" UNIQUE ("FaceSearchProbeID", "RankOrder"),
    CONSTRAINT "chk_faceprobematch_band" CHECK ("Band" IN ('strong','probable','weak'))
);
COMMENT ON TABLE "FaceProbeMatch" IS
    'Ranked shortlist returned by one face probe. Preserves what an officer was shown (and in what order) for later review of the decision.';

CREATE INDEX IF NOT EXISTS "idx_faceprobematch_probe"  ON "FaceProbeMatch" ("FaceSearchProbeID");
CREATE INDEX IF NOT EXISTS "idx_faceprobematch_person" ON "FaceProbeMatch" ("CanonicalPersonID");

-- =============================================================================
-- 4. Entity-resolution method vocabulary
-- =============================================================================
-- EntityResolutionCandidate.Method was documented as deterministic|fuzzy. A face
-- confirmation records Method='face' so a reviewer can see WHY two identities
-- were proposed as the same person. The column has no CHECK constraint, so this
-- is a comment refresh only (no DDL change required).
COMMENT ON COLUMN "EntityResolutionCandidate"."Method" IS
    'How the pair was proposed: deterministic | fuzzy | face. Face pairs carry the probe ref + cosine similarity in MatchFeatures and are NEVER auto-merged.';

-- =============================================================================
-- 5. ROW LEVEL SECURITY — explicitly DISABLED (hackathon posture, as elsewhere)
-- =============================================================================
ALTER TABLE "PersonFaceEmbedding" DISABLE ROW LEVEL SECURITY;
ALTER TABLE "FaceSearchProbe"     DISABLE ROW LEVEL SECURITY;
ALTER TABLE "FaceProbeMatch"      DISABLE ROW LEVEL SECURITY;

COMMIT;
