-- =============================================================================
-- DRISHTI migration 025 — scanned-FIR intake (Catalyst Zia OCR) staging layer
-- Target: PostgreSQL 15+ / AWS RDS PostgreSQL (ap-south-1)
-- Depends on: 006_ingestion_evidence.sql (SourceSystem/SourceRecord/EvidenceItem),
--             010_intake_workflow.sql (IntakeDraft/IntakeDraftActivity),
--             005_security_rls_audit.sql (RLS helpers), fn_set_updated_at()
-- =============================================================================
--
-- Adds the SECOND intake lane: an officer photographs/scans a written FIR, Zia
-- OCR recognises the text (English and/or Kannada), a bounded parser maps it onto
-- the SAME wizard fields, and the officer reviews/corrects before submitting.
--
-- SCOPE BOUNDARY — this is intake-document prefill, NOT evidence extraction:
--   * OCR output lands ONLY in staging (IntakeScan + IntakeDraft.Payload). It is
--     never written to a canonical table and never bypasses review. CaseMaster is
--     still created exclusively by the human approve transition in
--     app/intake/service._approve.
--   * Evidence-media analysis stays OFF (EVIDENCE_EXTRACTION_ENABLED=false):
--     no transcription of evidence audio/video, no face/object recognition, and
--     no auto-parsing of files uploaded through the /evidence custody path.
--   * Every extracted field carries its own confidence + provenance so a
--     reviewer can always tell machine-derived values from typed ones, and the
--     approved case can be traced back to the exact scanned page (SHA-256).
--
-- RLS stays DISABLED + NO FORCE (hackathon). No RLS policies. Additive +
-- idempotent: safe to run repeatedly.
-- =============================================================================

BEGIN;

-- =============================================================================
-- 1. WIDEN EXISTING CHECK CONSTRAINTS (additive vocabulary, no data change)
-- =============================================================================

-- 1a. SourceSystem.Kind gains 'scanned_form' so a scanned/handwritten FIR has an
--     honest provenance kind instead of being mislabelled a manual form.
DO $$
BEGIN
    IF EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'chk_sourcesystem_kind') THEN
        ALTER TABLE "SourceSystem" DROP CONSTRAINT "chk_sourcesystem_kind";
    END IF;
    ALTER TABLE "SourceSystem" ADD CONSTRAINT "chk_sourcesystem_kind" CHECK ("Kind" IN
        ('manual_form','csv_import','json_import','external_reference',
         'digital_export','court_document','scanned_form'));
END$$;

-- 1b. IntakeDraftActivity.EventType gains the scan lifecycle events so the
--     append-only trail can record that a draft was machine-prefilled, and by
--     which scan. Without this the provenance would be invisible in the audit.
DO $$
BEGIN
    IF EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'chk_intakeactivity_type') THEN
        ALTER TABLE "IntakeDraftActivity" DROP CONSTRAINT "chk_intakeactivity_type";
    END IF;
    ALTER TABLE "IntakeDraftActivity" ADD CONSTRAINT "chk_intakeactivity_type" CHECK ("EventType" IN
        ('created','autosaved','updated','validated','submitted','review_started',
         'approved','rejected','returned_for_correction','reopened',
         'party_added','party_updated','party_removed','event_added',
         'scan_uploaded','scan_ocr_completed','scan_prefilled','scan_field_overridden'));
END$$;

-- =============================================================================
-- 2. SEED the scanned-FIR source system (idempotent)
-- =============================================================================
INSERT INTO "SourceSystem" ("Code","Name","Kind","Description","IsSynthetic") VALUES
    ('FIR_SCAN_OCR',
     'Scanned FIR (Catalyst Zia OCR)',
     'scanned_form',
     'Written/printed FIR page recognised by Catalyst Zia OCR and parsed into draft '
     'fields for MANDATORY officer review. Machine-derived values are never canonical '
     'until a human approves the draft.',
     TRUE)
ON CONFLICT ("Code") DO NOTHING;

-- =============================================================================
-- 3. INTAKE SCAN — one row per OCR run over one uploaded page-set
--    The file bytes NEVER live in PostgreSQL: StorageKey + Sha256 point at the
--    object in Catalyst Stratus (or the private S3 evidence bucket), exactly
--    like EvidenceObject does. This row is the audit bridge between the scanned
--    page and the draft it produced.
-- =============================================================================
CREATE TABLE IF NOT EXISTS "IntakeScan" (
    "IntakeScanID"     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "ScanKey"          VARCHAR NOT NULL UNIQUE,      -- client-facing stable id (URLs)
    "IdempotencyKey"   VARCHAR UNIQUE,                -- safe retry of one OCR run
    "IntakeDraftID"    BIGINT REFERENCES "IntakeDraft" ("IntakeDraftID") ON DELETE SET NULL,
    "SourceSystemID"   INTEGER REFERENCES "SourceSystem" ("SourceSystemID"),
    "SourceRecordID"   BIGINT  REFERENCES "SourceRecord" ("SourceRecordID"),
    -- The scanned page kept as evidence in its own right (chain of custody), so
    -- an approved FIR can always be compared against the original document.
    "EvidenceItemID"   BIGINT  REFERENCES "EvidenceItem" ("EvidenceItemID") ON DELETE SET NULL,

    -- object manifest (bytes live in Stratus/S3, never here)
    "StorageKey"       VARCHAR,
    "FileName"         VARCHAR,
    "MimeType"         VARCHAR,
    "SizeBytes"        BIGINT CHECK ("SizeBytes" IS NULL OR "SizeBytes" >= 0),
    "Sha256"           VARCHAR,                       -- integrity of the exact page scanned
    "PageCount"        INTEGER CHECK ("PageCount" IS NULL OR "PageCount" >= 0),

    -- OCR run
    "Provider"         VARCHAR NOT NULL DEFAULT 'catalyst-zia-ocr',
    "ModelType"        VARCHAR NOT NULL DEFAULT 'OCR',   -- Zia model_type (OCR|AADHAAR|...)
    "RequestedLanguages" TEXT[] NOT NULL DEFAULT '{}',   -- e.g. {eng,kan}
    "DetectedLanguage" VARCHAR,                          -- en|kn|mixed
    "OcrConfidence"    NUMERIC(6,3),                     -- Zia document-level score (0-100)
    "RawText"          TEXT,                             -- recognised text, verbatim
    "TemplateCode"     VARCHAR,                          -- matched FIR template, if any
    "TemplateMatched"  BOOLEAN NOT NULL DEFAULT FALSE,

    -- extraction result
    "ExtractedPayload" JSONB NOT NULL DEFAULT '{}'::jsonb,  -- DraftPayload-shaped proposal
    "FieldConfidence"  JSONB NOT NULL DEFAULT '{}'::jsonb,  -- {"field.path": 0.0-1.0}
    "UnresolvedFields" JSONB NOT NULL DEFAULT '[]'::jsonb,  -- [{field,text,candidates[]}]
    "ExtractedParties" JSONB NOT NULL DEFAULT '[]'::jsonb,  -- proposed PartyInput rows
    "ReviewState"      VARCHAR NOT NULL DEFAULT 'pending_review',
    "Status"           VARCHAR NOT NULL DEFAULT 'uploaded',

    "FailureReason"    TEXT,
    "CreatedByActor"   VARCHAR,
    "ReviewedByActor"  VARCHAR,
    "IsSynthetic"      BOOLEAN NOT NULL DEFAULT TRUE,
    "CreatedAt"        TIMESTAMPTZ NOT NULL DEFAULT now(),
    "UpdatedAt"        TIMESTAMPTZ NOT NULL DEFAULT now(),
    "OcrStartedAt"     TIMESTAMPTZ,
    "OcrFinishedAt"    TIMESTAMPTZ,
    "AppliedAt"        TIMESTAMPTZ,

    CONSTRAINT "chk_intakescan_status" CHECK ("Status" IN
        ('uploaded','ocr_running','ocr_failed','extracted','applied','discarded')),
    CONSTRAINT "chk_intakescan_review" CHECK ("ReviewState" IN
        ('pending_review','accepted_with_edits','accepted_as_is','rejected')),
    CONSTRAINT "chk_intakescan_conf" CHECK
        ("OcrConfidence" IS NULL OR "OcrConfidence" BETWEEN 0 AND 100),
    -- an applied scan MUST name the draft it prefilled (provenance integrity)
    CONSTRAINT "chk_intakescan_applied_draft" CHECK
        ("Status" <> 'applied' OR "IntakeDraftID" IS NOT NULL)
);
COMMENT ON TABLE "IntakeScan" IS
    'One Catalyst Zia OCR run over one scanned/written FIR page-set. Holds the recognised text, the DraftPayload-shaped proposal, per-field confidence and unresolved lookups. STAGING ONLY: nothing here is canonical until an officer approves the draft it prefilled.';
COMMENT ON COLUMN "IntakeScan"."RawText" IS
    'Verbatim Zia OCR output, retained so a reviewer can always audit an extracted field against what the recogniser actually read.';
COMMENT ON COLUMN "IntakeScan"."FieldConfidence" IS
    'Per-field extraction confidence 0-1 keyed by dotted payload path. Derived by the parser, NOT by Zia (Zia returns one document-level score only).';
COMMENT ON COLUMN "IntakeScan"."UnresolvedFields" IS
    'Lookups the parser refused to auto-fill (ambiguous or low-confidence station/section/etc). Surfaced to the officer as suggestions instead of silently guessing.';
COMMENT ON COLUMN "IntakeScan"."Sha256" IS
    'SHA-256 of the exact scanned bytes, so an approved FIR is always traceable to the original page it was read from.';

-- =============================================================================
-- 4. INTAKE SCAN FIELD — per-field provenance for a prefilled draft.
--    Append-only: records what OCR proposed, what the officer finally accepted,
--    and whether the value was edited. This is the record that lets a reviewer
--    (or an auditor) separate machine-derived fields from typed ones.
-- =============================================================================
CREATE TABLE IF NOT EXISTS "IntakeScanField" (
    "IntakeScanFieldID" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "IntakeScanID"     BIGINT NOT NULL REFERENCES "IntakeScan" ("IntakeScanID") ON DELETE CASCADE,
    "FieldPath"        VARCHAR NOT NULL,          -- dotted DraftPayload path
    "ExtractedText"    TEXT,                      -- raw span the parser matched
    "ProposedValue"    JSONB,                     -- typed value OCR proposed
    "AcceptedValue"    JSONB,                     -- value after officer review
    "Confidence"       NUMERIC(5,4) CHECK ("Confidence" IS NULL OR "Confidence" BETWEEN 0 AND 1),
    "Origin"           VARCHAR NOT NULL DEFAULT 'ocr',   -- ocr|ocr_edited|manual
    "WasEdited"        BOOLEAN NOT NULL DEFAULT FALSE,
    "RequiresReview"   BOOLEAN NOT NULL DEFAULT FALSE,   -- low confidence -> must confirm
    "CreatedAt"        TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT "uq_intakescanfield" UNIQUE ("IntakeScanID", "FieldPath"),
    CONSTRAINT "chk_intakescanfield_origin" CHECK ("Origin" IN ('ocr','ocr_edited','manual'))
);
COMMENT ON TABLE "IntakeScanField" IS
    'Per-field provenance for an OCR-prefilled draft: what was proposed, at what confidence, what the officer accepted, and whether it was edited. Makes machine-derived values distinguishable from typed values for the whole life of the case.';

-- =============================================================================
-- 5. INDEXES
-- =============================================================================
CREATE INDEX IF NOT EXISTS "idx_intakescan_draft"     ON "IntakeScan" ("IntakeDraftID");
CREATE INDEX IF NOT EXISTS "idx_intakescan_status"    ON "IntakeScan" ("Status");
CREATE INDEX IF NOT EXISTS "idx_intakescan_review"    ON "IntakeScan" ("ReviewState");
CREATE INDEX IF NOT EXISTS "idx_intakescan_hash"      ON "IntakeScan" ("Sha256");
CREATE INDEX IF NOT EXISTS "idx_intakescan_evidence"  ON "IntakeScan" ("EvidenceItemID");
CREATE INDEX IF NOT EXISTS "idx_intakescan_created"   ON "IntakeScan" ("CreatedAt" DESC);
CREATE INDEX IF NOT EXISTS "idx_intakescanfield_scan" ON "IntakeScanField" ("IntakeScanID");
CREATE INDEX IF NOT EXISTS "idx_intakescanfield_review"
    ON "IntakeScanField" ("IntakeScanID") WHERE "RequiresReview";

CREATE INDEX IF NOT EXISTS "gin_intakescan_payload"
    ON "IntakeScan" USING GIN ("ExtractedPayload");
CREATE INDEX IF NOT EXISTS "gin_intakescan_fieldconf"
    ON "IntakeScan" USING GIN ("FieldConfidence");

-- =============================================================================
-- 6. TRIGGERS (updated_at maintenance — reuse shared fn_set_updated_at())
-- =============================================================================
DO $$
BEGIN
    IF EXISTS (SELECT 1 FROM pg_proc WHERE proname = 'fn_set_updated_at')
       AND NOT EXISTS (SELECT 1 FROM pg_trigger WHERE tgname = 'trg_intakescan_updated') THEN
        CREATE TRIGGER "trg_intakescan_updated" BEFORE UPDATE ON "IntakeScan"
            FOR EACH ROW EXECUTE FUNCTION fn_set_updated_at();
    END IF;
END$$;

-- =============================================================================
-- 7. REVIEW QUEUE VIEW — scans awaiting officer confirmation.
--    Drives the admin "extraction queue" panel, which until now honestly
--    reported that no extraction queue existed.
-- =============================================================================
CREATE OR REPLACE VIEW "vw_intake_scan_queue" AS
SELECT
    s."IntakeScanID",
    s."ScanKey",
    s."Status",
    s."ReviewState",
    s."DetectedLanguage",
    s."OcrConfidence",
    s."TemplateCode",
    s."TemplateMatched",
    s."FileName",
    s."MimeType",
    s."SizeBytes",
    s."CreatedByActor",
    s."CreatedAt",
    s."OcrFinishedAt",
    d."DraftKey",
    d."Status" AS "DraftStatus",
    d."CaseKind",
    d."CaseMasterID",
    (SELECT count(*) FROM "IntakeScanField" f
      WHERE f."IntakeScanID" = s."IntakeScanID")                       AS "FieldCount",
    (SELECT count(*) FROM "IntakeScanField" f
      WHERE f."IntakeScanID" = s."IntakeScanID" AND f."RequiresReview") AS "FieldsNeedingReview",
    (SELECT count(*) FROM "IntakeScanField" f
      WHERE f."IntakeScanID" = s."IntakeScanID" AND f."WasEdited")      AS "FieldsEdited",
    jsonb_array_length(s."UnresolvedFields")                           AS "UnresolvedCount"
FROM "IntakeScan" s
LEFT JOIN "IntakeDraft" d ON d."IntakeDraftID" = s."IntakeDraftID";
COMMENT ON VIEW "vw_intake_scan_queue" IS
    'Scanned-FIR OCR review queue: one row per scan with its draft, confidence, and the count of fields still needing human confirmation.';

-- =============================================================================
-- 8. READ-ONLY GRANTS (retained analytics reader)
-- =============================================================================
DO $$
DECLARE
    t TEXT;
BEGIN
    IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'drishti_readonly') THEN
        FOREACH t IN ARRAY ARRAY['IntakeScan','IntakeScanField'] LOOP
            EXECUTE format('GRANT SELECT ON %I TO drishti_readonly;', t);
        END LOOP;
        EXECUTE 'GRANT SELECT ON "vw_intake_scan_queue" TO drishti_readonly;';
    END IF;
END$$;

-- =============================================================================
-- 9. RLS posture (unchanged — disabled + NO FORCE across app tables, hackathon)
-- =============================================================================
SELECT fn_disable_rls_all_app();
SELECT fn_assert_rls_disabled();

COMMIT;
