-- =============================================================================
-- DRISHTI migration 026 — CCTV monitoring (video-analytics review + dispatch)
-- Target: PostgreSQL 15+ / AWS RDS PostgreSQL (ap-south-1)
-- Depends on: police_fir_schema.sql (State, District, Unit),
--             009_jurisdiction_external_events.sql (UnitLocation + GIST index,
--                 fn_point_in_district), 005_security_rls_audit.sql
--                 (fn_disable_rls_all_app / fn_assert_rls_disabled)
-- =============================================================================
--
-- This is the ANALYTICS MIRROR of the Data Store-native CCTV tables defined in
-- app/datastore/cctv_schema.py. Catalyst Data Store is authoritative for the
-- operational surface; this mirror is reconstructable, keyed by the same
-- ExternalIDs, and exists so the estate can be analysed with PostGIS (camera
-- coverage vs hotspots, response-distance distributions, false-positive rates by
-- class and camera). It is never the browser CRUD path.
--
-- The pipeline these tables record:
--
--   1. "Camera" — the monitored estate. A real point geometry so coverage can be
--      compared against incident hotspots, plus a per-camera analytics switch and
--      an optional detector profile (which incident classes this camera is
--      watched for).
--   2. "PatrolUnit" — dispatchable responders (station desks, Hoysala patrol
--      cars, Cheetah traffic bikes, control rooms) with a point geometry, so
--      "nearest responder" is a real KNN query rather than a guess.
--   3. "CctvDetection" — APPEND-ONLY detector output. Carries "DetectorKind"
--      ('synthetic_replay' | 'external_analytics') and "DetectorLabel" so the
--      provenance of every claim is recorded, plus "Confidence" and
--      "QualityFlag" so a weak detection can never read as a certainty. Unique
--      on "SourceRecordID", which is what makes ingestion idempotent.
--   4. "CctvAlert" — the REVIEWABLE alert. Starts at 'proposed'. A recorded human
--      actor moves it to 'confirmed' or 'dismissed'; a dismissal keeps its
--      reason, which is the only honest measure of detector precision.
--   5. "CctvDispatch" — the nearest-responder assignment, with the ranking inputs
--      kept in "Reason" (distance, geometry source, ETA assumption, rule) so the
--      choice is explainable after the fact.
--   6. "CctvActivity" — APPEND-ONLY audit of every camera/alert/dispatch action.
--
-- GOVERNANCE — the important part:
--   * NOTHING AUTO-DISPATCHES. A detection can only propose an alert; a human
--     confirms the alert; a human separately confirms the dispatch. The
--     CHECK constraints below encode that a confirmed/dismissed alert must carry
--     a reviewer, and that a dismissal must carry a reason.
--   * This schema stores NO frame or clip BYTES and no biometric descriptor. A
--     detection points at an object key in the evidence bucket; bounding boxes
--     are normalised geometry with a class label ('person', 'vehicle'), never an
--     identity. Face recognition is a separate, separately-gated capability
--     (025) and is deliberately not joined to this table.
--   * Detection and activity tables are append-only by trigger, so a detection
--     can never be rewritten after review to agree with the decision made.
--
-- HACKATHON SCOPE: synthetic data only. RLS stays DISABLED (no policies).
-- Additive + idempotent: safe to re-run.
-- =============================================================================

BEGIN;

CREATE EXTENSION IF NOT EXISTS postgis;

-- =============================================================================
-- 1. CAMERA — the monitored estate
-- =============================================================================
CREATE TABLE IF NOT EXISTS "Camera" (
    "CameraID"        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "ExternalID"      VARCHAR NOT NULL,          -- 'cam:<pk>' (Data Store key)
    "Code"            VARCHAR NOT NULL,          -- operator-facing camera code
    "Name"            VARCHAR NOT NULL,
    "LocationLabel"   VARCHAR,
    "geom"            geometry(Point, 4326) NOT NULL,
    "BearingDegrees"  DOUBLE PRECISION,
    "FovDegrees"      DOUBLE PRECISION,
    "DistrictID"      INTEGER REFERENCES "District" ("DistrictID"),
    "UnitID"          INTEGER REFERENCES "Unit" ("UnitID"),
    "StreamKind"      VARCHAR NOT NULL DEFAULT 'none',
    "StreamURL"       TEXT,
    "PosterURL"       TEXT,
    "Status"          VARCHAR NOT NULL DEFAULT 'online',
    "AnalyticsEnabled" BOOLEAN NOT NULL DEFAULT TRUE,
    "DetectorProfile" VARCHAR,                   -- comma-separated class list
    "LastHeartbeatAt" TIMESTAMPTZ,
    "LastAnalysedAt"  TIMESTAMPTZ,
    "Notes"           TEXT,
    "Version"         INTEGER NOT NULL DEFAULT 1,
    "CreatedAt"       TIMESTAMPTZ NOT NULL DEFAULT now(),
    "UpdatedAt"       TIMESTAMPTZ NOT NULL DEFAULT now(),
    "DeletedAt"       TIMESTAMPTZ,
    CONSTRAINT "uq_camera_external"  UNIQUE ("ExternalID"),
    CONSTRAINT "uq_camera_code"      UNIQUE ("Code"),
    CONSTRAINT "chk_camera_status"
        CHECK ("Status" IN ('online','degraded','offline','maintenance')),
    CONSTRAINT "chk_camera_stream_kind"
        CHECK ("StreamKind" IN ('hls','mp4_loop','image_snapshot','none')),
    -- A stream kind other than 'none' is a claim that imagery exists, so it must
    -- come with a URL. 'none' is the honest state for a registered-but-dark camera.
    CONSTRAINT "chk_camera_stream_url"
        CHECK ("StreamKind" = 'none' OR "StreamURL" IS NOT NULL)
);
COMMENT ON TABLE "Camera" IS
    'Monitored CCTV estate (synthetic). Point geometry enables coverage-vs-hotspot analysis. AnalyticsEnabled is the per-camera detector switch.';
COMMENT ON COLUMN "Camera"."StreamKind" IS
    '''none'' means no imagery is configured — the UI shows an explicit no-stream state rather than a placeholder that looks like live video.';

-- =============================================================================
-- 2. PATROLUNIT — dispatchable responders
-- =============================================================================
CREATE TABLE IF NOT EXISTS "PatrolUnit" (
    "PatrolUnitID"  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "ExternalID"    VARCHAR NOT NULL,            -- 'patrol:<pk>'
    "Code"          VARCHAR NOT NULL,            -- callsign
    "Name"          VARCHAR NOT NULL,
    "Kind"          VARCHAR NOT NULL,
    "UnitID"        INTEGER REFERENCES "Unit" ("UnitID"),
    "DistrictID"    INTEGER REFERENCES "District" ("DistrictID"),
    "geom"          geometry(Point, 4326) NOT NULL,
    "Status"        VARCHAR NOT NULL DEFAULT 'available',
    "ContactLabel"  VARCHAR,                     -- control-room reference only
    "Capabilities"  JSONB NOT NULL DEFAULT '[]'::jsonb,
    "Version"       INTEGER NOT NULL DEFAULT 1,
    "LastUpdatedAt" TIMESTAMPTZ NOT NULL DEFAULT now(),
    "CreatedAt"     TIMESTAMPTZ NOT NULL DEFAULT now(),
    "UpdatedAt"     TIMESTAMPTZ NOT NULL DEFAULT now(),
    "DeletedAt"     TIMESTAMPTZ,
    CONSTRAINT "uq_patrolunit_external" UNIQUE ("ExternalID"),
    CONSTRAINT "uq_patrolunit_code"     UNIQUE ("Code"),
    CONSTRAINT "chk_patrolunit_kind"
        CHECK ("Kind" IN ('station','patrol_vehicle','traffic_patrol','control_room')),
    CONSTRAINT "chk_patrolunit_status"
        CHECK ("Status" IN ('available','engaged','offline'))
);
COMMENT ON TABLE "PatrolUnit" IS
    'Dispatchable responders (synthetic). ContactLabel is a control-room reference, never a real phone number.';

-- =============================================================================
-- 3. CCTVDETECTION — append-only detector output
-- =============================================================================
CREATE TABLE IF NOT EXISTS "CctvDetection" (
    "CctvDetectionID" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "ExternalID"      VARCHAR NOT NULL,          -- 'cctvdet:<pk>'
    "CameraID"        BIGINT NOT NULL REFERENCES "Camera" ("CameraID"),
    "DetectionType"   VARCHAR NOT NULL,
    "Confidence"      DOUBLE PRECISION NOT NULL,
    "Severity"        VARCHAR NOT NULL,
    "ObjectCount"     INTEGER,
    "BBoxJSON"        JSONB NOT NULL DEFAULT '[]'::jsonb,
    "Attributes"      JSONB NOT NULL DEFAULT '{}'::jsonb,
    "DetectorKind"    VARCHAR NOT NULL,
    "DetectorLabel"   VARCHAR NOT NULL,
    "FrameObjectKey"  TEXT,                      -- evidence-bucket key, not bytes
    "ClipObjectKey"   TEXT,
    "DetectedAt"      TIMESTAMPTZ NOT NULL,
    "ReceivedAt"      TIMESTAMPTZ NOT NULL DEFAULT now(),
    "WindowSeconds"   DOUBLE PRECISION,
    "QualityFlag"     VARCHAR NOT NULL DEFAULT 'valid',
    "SourceRecordID"  VARCHAR NOT NULL,          -- producer idempotency key
    "DistrictID"      INTEGER REFERENCES "District" ("DistrictID"),
    "geom"            geometry(Point, 4326),
    "CreatedAt"       TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT "uq_cctvdetection_external" UNIQUE ("ExternalID"),
    CONSTRAINT "uq_cctvdetection_source"   UNIQUE ("SourceRecordID"),
    CONSTRAINT "chk_cctvdetection_type" CHECK ("DetectionType" IN (
        'fight','road_rage','traffic_block','crowd_surge','vehicle_accident',
        'fire_smoke','weapon_suspected','abandoned_object','trespass','person_down')),
    CONSTRAINT "chk_cctvdetection_severity"
        CHECK ("Severity" IN ('minor','moderate','severe','extreme')),
    CONSTRAINT "chk_cctvdetection_confidence"
        CHECK ("Confidence" >= 0.0 AND "Confidence" <= 1.0),
    CONSTRAINT "chk_cctvdetection_detector"
        CHECK ("DetectorKind" IN ('synthetic_replay','external_analytics')),
    CONSTRAINT "chk_cctvdetection_quality"
        CHECK ("QualityFlag" IN ('valid','low_confidence','suspect','superseded'))
);
COMMENT ON TABLE "CctvDetection" IS
    'APPEND-ONLY video-analytics output. DetectorKind/DetectorLabel record provenance so a synthetic detection is never presentable as a model inference. Stores no frame bytes and no biometric descriptor.';
COMMENT ON COLUMN "CctvDetection"."BBoxJSON" IS
    'Normalised [0,1] boxes with a CLASS label (person/vehicle/bag) — never an identity.';
COMMENT ON COLUMN "CctvDetection"."SourceRecordID" IS
    'Producer-side idempotency key (camera:class:window). UNIQUE, so a retried post or a re-run analysis window suppresses instead of duplicating.';

-- =============================================================================
-- 4. CCTVALERT — the reviewable alert (proposed -> confirmed | dismissed)
-- =============================================================================
CREATE TABLE IF NOT EXISTS "CctvAlert" (
    "CctvAlertID"     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "ExternalID"      VARCHAR NOT NULL,          -- 'cctvalert:<pk>'
    "CctvDetectionID" BIGINT NOT NULL
        REFERENCES "CctvDetection" ("CctvDetectionID"),
    "CameraID"        BIGINT NOT NULL REFERENCES "Camera" ("CameraID"),
    "AlertType"       VARCHAR NOT NULL,
    "Severity"        VARCHAR NOT NULL,
    "Title"           VARCHAR NOT NULL,
    "Message"         TEXT,
    "Confidence"      DOUBLE PRECISION NOT NULL,
    "Status"          VARCHAR NOT NULL DEFAULT 'proposed',
    "ReviewedByActor" VARCHAR,
    "ReviewedAt"      TIMESTAMPTZ,
    "ReviewNote"      TEXT,
    "DismissReason"   VARCHAR,
    "DistrictID"      INTEGER REFERENCES "District" ("DistrictID"),
    "geom"            geometry(Point, 4326),
    "LocationLabel"   VARCHAR,
    "NearestUnitID"   INTEGER REFERENCES "Unit" ("UnitID"),
    "Payload"         JSONB NOT NULL DEFAULT '{}'::jsonb,
    "Version"         INTEGER NOT NULL DEFAULT 1,
    "CreatedAt"       TIMESTAMPTZ NOT NULL DEFAULT now(),
    "UpdatedAt"       TIMESTAMPTZ NOT NULL DEFAULT now(),
    "DeletedAt"       TIMESTAMPTZ,
    CONSTRAINT "uq_cctvalert_external"  UNIQUE ("ExternalID"),
    -- One reviewable alert per detection: a detector cannot flood the queue by
    -- re-raising the same detection.
    CONSTRAINT "uq_cctvalert_detection" UNIQUE ("CctvDetectionID"),
    CONSTRAINT "chk_cctvalert_status"
        CHECK ("Status" IN ('proposed','confirmed','dismissed','dispatched','resolved')),
    CONSTRAINT "chk_cctvalert_severity"
        CHECK ("Severity" IN ('minor','moderate','severe','extreme')),
    CONSTRAINT "chk_cctvalert_dismiss_reason" CHECK (
        "DismissReason" IS NULL OR "DismissReason" IN (
            'false_positive','duplicate','already_handled','not_actionable',
            'poor_visibility','other')),
    -- A reviewed alert MUST name the human who reviewed it. This is the database
    -- refusing to let an alert move out of 'proposed' anonymously.
    CONSTRAINT "chk_cctvalert_reviewer_recorded" CHECK (
        "Status" = 'proposed' OR "ReviewedByActor" IS NOT NULL),
    -- A dismissal MUST carry a reason: the false-positive trail is the only
    -- honest measure of the detector's precision.
    CONSTRAINT "chk_cctvalert_dismissal_reasoned" CHECK (
        "Status" <> 'dismissed' OR "DismissReason" IS NOT NULL)
);
COMMENT ON TABLE "CctvAlert" IS
    'Reviewable CCTV alert. Created only as ''proposed''; a recorded human actor confirms or dismisses it. CHECK constraints enforce that a reviewed alert names its reviewer and a dismissal names its reason.';

-- =============================================================================
-- 5. CCTVDISPATCH — nearest-responder assignment
-- =============================================================================
CREATE TABLE IF NOT EXISTS "CctvDispatch" (
    "CctvDispatchID"  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "ExternalID"      VARCHAR NOT NULL,          -- 'cctvdisp:<pk>'
    "CctvAlertID"     BIGINT NOT NULL REFERENCES "CctvAlert" ("CctvAlertID"),
    "PatrolUnitID"    BIGINT REFERENCES "PatrolUnit" ("PatrolUnitID"),
    "UnitID"          INTEGER REFERENCES "Unit" ("UnitID"),
    "UnitName"        VARCHAR NOT NULL,
    "UnitKind"        VARCHAR,
    "DistanceKm"      DOUBLE PRECISION NOT NULL,
    "EtaMinutes"      DOUBLE PRECISION,
    "Score"           DOUBLE PRECISION,
    "Reason"          JSONB NOT NULL DEFAULT '{}'::jsonb,
    "Status"          VARCHAR NOT NULL DEFAULT 'proposed',
    "ProposedByActor" VARCHAR,
    "ApprovedByActor" VARCHAR,
    "DistrictID"      INTEGER REFERENCES "District" ("DistrictID"),
    "ProposedAt"      TIMESTAMPTZ,
    "DispatchedAt"    TIMESTAMPTZ,
    "AcknowledgedAt"  TIMESTAMPTZ,
    "EnrouteAt"       TIMESTAMPTZ,
    "OnsiteAt"        TIMESTAMPTZ,
    "ClosedAt"        TIMESTAMPTZ,
    "CancelledAt"     TIMESTAMPTZ,
    "Notes"           TEXT,
    "Version"         INTEGER NOT NULL DEFAULT 1,
    "CreatedAt"       TIMESTAMPTZ NOT NULL DEFAULT now(),
    "UpdatedAt"       TIMESTAMPTZ NOT NULL DEFAULT now(),
    "DeletedAt"       TIMESTAMPTZ,
    CONSTRAINT "uq_cctvdispatch_external" UNIQUE ("ExternalID"),
    CONSTRAINT "chk_cctvdispatch_status" CHECK ("Status" IN (
        'proposed','dispatched','acknowledged','enroute','onsite','closed','cancelled')),
    CONSTRAINT "chk_cctvdispatch_distance" CHECK ("DistanceKm" >= 0.0),
    -- A dispatched unit MUST name the human who approved sending it. Combined
    -- with the alert-reviewer constraint, the pair of human decisions behind any
    -- unit on the road is recoverable from the rows alone.
    CONSTRAINT "chk_cctvdispatch_approver_recorded" CHECK (
        "Status" IN ('proposed','cancelled') OR "ApprovedByActor" IS NOT NULL),
    -- A dispatch must point at SOMETHING dispatchable.
    CONSTRAINT "chk_cctvdispatch_target" CHECK (
        "PatrolUnitID" IS NOT NULL OR "UnitID" IS NOT NULL)
);
COMMENT ON TABLE "CctvDispatch" IS
    'Nearest-responder assignment for a CONFIRMED alert. Created as ''proposed''; moving to ''dispatched'' requires a second human confirmation at the API. Reason records the ranking inputs so the pick is explainable.';
COMMENT ON COLUMN "CctvDispatch"."Reason" IS
    'Explainability payload: distance_km, eta_minutes, geometry_source (postgis_knn | datastore_haversine), eta_assumptions_version, search_radius_km, rule.';

-- =============================================================================
-- 6. CCTVACTIVITY — append-only audit
-- =============================================================================
CREATE TABLE IF NOT EXISTS "CctvActivity" (
    "CctvActivityID" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "ExternalID"     VARCHAR NOT NULL,           -- 'cctvact:<pk>'
    "SubjectType"    VARCHAR NOT NULL,
    "SubjectID"      VARCHAR NOT NULL,
    "Actor"          VARCHAR NOT NULL,
    "Action"         VARCHAR NOT NULL,
    "DiffJSON"       JSONB NOT NULL DEFAULT '{}'::jsonb,
    "RequestID"      VARCHAR,
    "CreatedAt"      TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT "uq_cctvactivity_external" UNIQUE ("ExternalID"),
    CONSTRAINT "chk_cctvactivity_subject" CHECK ("SubjectType" IN (
        'camera','patrol_unit','detection','alert','dispatch','access'))
);
COMMENT ON TABLE "CctvActivity" IS
    'APPEND-ONLY audit of every CCTV camera/alert/dispatch action, including denied access attempts.';

-- =============================================================================
-- 7. Indexes — spatial (KNN for nearest responder) + queue access paths
-- =============================================================================
CREATE INDEX IF NOT EXISTS "gist_camera_geom"       ON "Camera" USING GIST ("geom");
CREATE INDEX IF NOT EXISTS "idx_camera_district"    ON "Camera" ("DistrictID");
CREATE INDEX IF NOT EXISTS "idx_camera_unit"        ON "Camera" ("UnitID");
CREATE INDEX IF NOT EXISTS "idx_camera_status"      ON "Camera" ("Status");

-- The KNN index behind "nearest responder": ORDER BY geom <-> point.
CREATE INDEX IF NOT EXISTS "gist_patrolunit_geom"   ON "PatrolUnit" USING GIST ("geom");
CREATE INDEX IF NOT EXISTS "idx_patrolunit_district" ON "PatrolUnit" ("DistrictID");
CREATE INDEX IF NOT EXISTS "idx_patrolunit_status"  ON "PatrolUnit" ("Status");

CREATE INDEX IF NOT EXISTS "idx_cctvdet_camera_time"
    ON "CctvDetection" ("CameraID", "DetectedAt" DESC);
CREATE INDEX IF NOT EXISTS "idx_cctvdet_type_time"
    ON "CctvDetection" ("DetectionType", "DetectedAt" DESC);
CREATE INDEX IF NOT EXISTS "idx_cctvdet_district"   ON "CctvDetection" ("DistrictID");
CREATE INDEX IF NOT EXISTS "idx_cctvdet_quality"    ON "CctvDetection" ("QualityFlag");
CREATE INDEX IF NOT EXISTS "gist_cctvdet_geom"      ON "CctvDetection" USING GIST ("geom");

-- The review queue is read by status constantly; keep it a partial index.
CREATE INDEX IF NOT EXISTS "idx_cctvalert_pending"
    ON "CctvAlert" ("CreatedAt" DESC) WHERE "Status" = 'proposed';
CREATE INDEX IF NOT EXISTS "idx_cctvalert_status"   ON "CctvAlert" ("Status");
CREATE INDEX IF NOT EXISTS "idx_cctvalert_camera"   ON "CctvAlert" ("CameraID");
CREATE INDEX IF NOT EXISTS "idx_cctvalert_district" ON "CctvAlert" ("DistrictID");
CREATE INDEX IF NOT EXISTS "idx_cctvalert_type"     ON "CctvAlert" ("AlertType");
CREATE INDEX IF NOT EXISTS "gist_cctvalert_geom"    ON "CctvAlert" USING GIST ("geom");

CREATE INDEX IF NOT EXISTS "idx_cctvdisp_alert"     ON "CctvDispatch" ("CctvAlertID");
CREATE INDEX IF NOT EXISTS "idx_cctvdisp_status"    ON "CctvDispatch" ("Status");
CREATE INDEX IF NOT EXISTS "idx_cctvdisp_unit"      ON "CctvDispatch" ("UnitID");
CREATE INDEX IF NOT EXISTS "idx_cctvdisp_district"  ON "CctvDispatch" ("DistrictID");

CREATE INDEX IF NOT EXISTS "idx_cctvact_subject"
    ON "CctvActivity" ("SubjectType", "SubjectID");
CREATE INDEX IF NOT EXISTS "idx_cctvact_seq"        ON "CctvActivity" ("CctvActivityID");

-- =============================================================================
-- 8. Append-only enforcement (detections + activity)
-- =============================================================================
-- A detection that could be edited after review is worthless as evidence of what
-- the detector actually claimed, so the database refuses the write outright
-- rather than trusting every future code path to remember.
CREATE OR REPLACE FUNCTION fn_cctv_forbid_mutation()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
BEGIN
    RAISE EXCEPTION
        '%.% is append-only: % is forbidden',
        TG_TABLE_SCHEMA, TG_TABLE_NAME, TG_OP
        USING HINT = 'Insert a new row (e.g. a superseding detection) instead.';
END$$;
COMMENT ON FUNCTION fn_cctv_forbid_mutation() IS
    'Raises on UPDATE/DELETE for the append-only CCTV tables.';

DROP TRIGGER IF EXISTS "trg_cctvdetection_append_only" ON "CctvDetection";
CREATE TRIGGER "trg_cctvdetection_append_only"
    BEFORE UPDATE OR DELETE ON "CctvDetection"
    FOR EACH ROW EXECUTE FUNCTION fn_cctv_forbid_mutation();

DROP TRIGGER IF EXISTS "trg_cctvactivity_append_only" ON "CctvActivity";
CREATE TRIGGER "trg_cctvactivity_append_only"
    BEFORE UPDATE OR DELETE ON "CctvActivity"
    FOR EACH ROW EXECUTE FUNCTION fn_cctv_forbid_mutation();

-- =============================================================================
-- 9. Analysis helpers
-- =============================================================================
-- Nearest dispatchable responders to a point, using the GIST KNN operator.
-- This is the SQL form of app/cctv/dispatch.py::rank_responders, kept here so the
-- same ranking can be reproduced in analysis without going through the API.
CREATE OR REPLACE FUNCTION fn_cctv_nearest_responders(
    p_lon        DOUBLE PRECISION,
    p_lat        DOUBLE PRECISION,
    p_max_km     DOUBLE PRECISION DEFAULT 25.0,
    p_limit      INTEGER DEFAULT 5
)
RETURNS TABLE (
    patrol_unit_id BIGINT,
    code           VARCHAR,
    name           VARCHAR,
    kind           VARCHAR,
    status         VARCHAR,
    district_id    INTEGER,
    distance_km    DOUBLE PRECISION
)
LANGUAGE sql
STABLE
AS $$
    SELECT p."PatrolUnitID", p."Code", p."Name", p."Kind", p."Status", p."DistrictID",
           ST_Distance(p."geom"::geography,
                       ST_SetSRID(ST_MakePoint(p_lon, p_lat), 4326)::geography) / 1000.0
    FROM "PatrolUnit" p
    WHERE p."DeletedAt" IS NULL
      AND p."Status" <> 'offline'
      AND ST_DWithin(p."geom"::geography,
                     ST_SetSRID(ST_MakePoint(p_lon, p_lat), 4326)::geography,
                     p_max_km * 1000.0)
    ORDER BY p."geom" <-> ST_SetSRID(ST_MakePoint(p_lon, p_lat), 4326)
    LIMIT GREATEST(1, p_limit);
$$;
COMMENT ON FUNCTION fn_cctv_nearest_responders(DOUBLE PRECISION, DOUBLE PRECISION, DOUBLE PRECISION, INTEGER) IS
    'KNN nearest available responders to a point, within a radius. SQL mirror of the API ranking.';

-- Per-class / per-camera review outcomes: the honest precision read-out. A demo
-- that shows detections without showing how many were dismissed is marketing.
CREATE OR REPLACE VIEW "vw_cctv_detector_precision" AS
SELECT
    a."AlertType"                                        AS "AlertType",
    c."Code"                                             AS "CameraCode",
    c."Name"                                             AS "CameraName",
    a."DistrictID"                                       AS "DistrictID",
    COUNT(*)                                             AS "TotalAlerts",
    COUNT(*) FILTER (WHERE a."Status" = 'proposed')       AS "AwaitingReview",
    COUNT(*) FILTER (WHERE a."Status" IN ('confirmed','dispatched','resolved'))
                                                         AS "Confirmed",
    COUNT(*) FILTER (WHERE a."Status" = 'dismissed')      AS "Dismissed",
    COUNT(*) FILTER (WHERE a."DismissReason" = 'false_positive')
                                                         AS "FalsePositives",
    ROUND(AVG(a."Confidence")::numeric, 4)               AS "MeanConfidence",
    -- Precision is only defined over REVIEWED alerts; NULL while nothing has been
    -- reviewed, rather than a misleading 0 or 1.
    CASE WHEN COUNT(*) FILTER (WHERE a."Status" <> 'proposed') > 0
         THEN ROUND(
              (COUNT(*) FILTER (WHERE a."Status" IN ('confirmed','dispatched','resolved'))::numeric
               / COUNT(*) FILTER (WHERE a."Status" <> 'proposed')), 4)
         ELSE NULL
    END                                                  AS "ReviewedPrecision"
FROM "CctvAlert" a
JOIN "Camera" c ON c."CameraID" = a."CameraID"
WHERE a."DeletedAt" IS NULL
GROUP BY a."AlertType", c."Code", c."Name", a."DistrictID";
COMMENT ON VIEW "vw_cctv_detector_precision" IS
    'Review outcomes per class and camera. ReviewedPrecision is NULL until alerts have actually been reviewed.';

-- Response-time distribution for dispatches that were actually sent.
CREATE OR REPLACE VIEW "vw_cctv_response_performance" AS
SELECT
    d."CctvDispatchID"                                   AS "CctvDispatchID",
    d."CctvAlertID"                                      AS "CctvAlertID",
    a."AlertType"                                        AS "AlertType",
    a."Severity"                                         AS "Severity",
    d."UnitName"                                         AS "UnitName",
    d."DistanceKm"                                       AS "DistanceKm",
    d."EtaMinutes"                                       AS "EtaMinutes",
    d."Reason" ->> 'geometry_source'                     AS "GeometrySource",
    EXTRACT(EPOCH FROM (d."DispatchedAt" - a."CreatedAt")) / 60.0
                                                         AS "DetectionToDispatchMinutes",
    EXTRACT(EPOCH FROM (a."ReviewedAt" - a."CreatedAt")) / 60.0
                                                         AS "DetectionToReviewMinutes",
    EXTRACT(EPOCH FROM (d."OnsiteAt" - d."DispatchedAt")) / 60.0
                                                         AS "DispatchToOnsiteMinutes",
    d."Status"                                           AS "Status"
FROM "CctvDispatch" d
JOIN "CctvAlert" a ON a."CctvAlertID" = d."CctvAlertID"
WHERE d."DeletedAt" IS NULL
  AND d."DispatchedAt" IS NOT NULL;
COMMENT ON VIEW "vw_cctv_response_performance" IS
    'Detection -> review -> dispatch -> onsite timings, with the actual vs estimated travel comparison. Only rows that were really dispatched.';

-- Camera coverage sanity: which cameras sit outside their claimed district.
-- A camera whose point falls outside the district it is filed under is a data
-- error that would silently corrupt every district-scoped query above it.
CREATE OR REPLACE VIEW "vw_cctv_camera_geo_mismatch" AS
SELECT c."CameraID", c."Code", c."Name", c."DistrictID",
       ST_X(c."geom") AS "Lon", ST_Y(c."geom") AS "Lat"
FROM "Camera" c
WHERE c."DeletedAt" IS NULL
  AND c."DistrictID" IS NOT NULL
  AND NOT fn_point_in_district(c."DistrictID", ST_X(c."geom"), ST_Y(c."geom"));
COMMENT ON VIEW "vw_cctv_camera_geo_mismatch" IS
    'Cameras whose point geometry falls outside the district they are filed under (degrades safely to empty when no boundary is loaded).';

-- =============================================================================
-- 10. Read-only grants (retained analytics reader) + RLS-disabled verification
-- =============================================================================
DO $$
DECLARE
    t TEXT;
BEGIN
    IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname='drishti_readonly') THEN
        FOREACH t IN ARRAY ARRAY[
            'Camera','PatrolUnit','CctvDetection','CctvAlert','CctvDispatch',
            'CctvActivity'
        ] LOOP
            EXECUTE format('GRANT SELECT ON %I TO drishti_readonly;', t);
        END LOOP;
        FOREACH t IN ARRAY ARRAY[
            'vw_cctv_detector_precision','vw_cctv_response_performance',
            'vw_cctv_camera_geo_mismatch'
        ] LOOP
            EXECUTE format('GRANT SELECT ON %I TO drishti_readonly;', t);
        END LOOP;
    END IF;
END$$;

-- RLS + FORCE RLS stay DISABLED across every application table (hackathon).
-- No RLS policy is created for the mirror. The access boundary is the
-- Catalyst-authenticated API + the server-side CCTV role middleware.
SELECT fn_disable_rls_all_app();
SELECT fn_assert_rls_disabled();

COMMIT;
