-- DRISHTI migration 026: organizational Wing and Range tiers.
--
-- WHY
-- The application role `senior_command` carries two different scope types:
--   * ADGP -> `wing`  : state-wide geography, narrowed by crime head (functional)
--   * DIG  -> `range` : a set of districts, all crime heads (geographic)
-- Neither tier had any data model. `adgp_igp_range` mapped to scope level
-- "range" and `dysp_acp` to "subdivision", but no Range table existed and
-- Unit held zero Circle Office / Sub-Division rows, so both seats resolved to
-- no geographic narrowing at all (app/org/scope.py derive_scope else-branch).
--
-- SEPARATION OF CONCERNS
-- Rank, assignment, organizational unit, scope and permission stay distinct:
--   Rank        -> "Rank".RankName        via Employee.RankID       (establishment)
--   Assignment  -> "Designation"          via Employee.DesignationID (post held)
--   Org unit    -> Unit / District / Range / Wing                   (where posted)
--   Scope       -> users.scope_type + anchor  (migration 027)       (data breadth)
--   Permission  -> role_permissions                                 (allowed actions)
-- This migration only adds the ORG UNIT tier. It grants nothing and scopes
-- nobody.
--
-- STRUCTURE ONLY — NO ROSTER SEED.
-- The range-to-district mapping and the Commissionerate flags are deliberately
-- NOT seeded here. The official KSP roster (7 ranges / 6 Commissionerates) does
-- not reconcile cleanly with the 32 rows currently in "District": the dataset
-- has a spurious "Bengaluru Urban" police district, is missing KGF, and
-- conflates five city Commissionerates with their rural districts. Seeding a
-- guessed mapping would put a wrong jurisdiction behind every range KPI.
-- The roster seed ships separately once reconciled.

BEGIN;

-- ---------------------------------------------------------------------------
-- 1. Range — the geographic tier between State and District (IGP/DIG command).
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS "Range" (
    "RangeID"      INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "RangeName"    VARCHAR NOT NULL UNIQUE,
    "RangeCode"    VARCHAR NOT NULL UNIQUE,
    "HQDistrictID" INTEGER REFERENCES "District" ("DistrictID"),
    "StateID"      INTEGER REFERENCES "State" ("StateID"),
    "Active"       BOOLEAN NOT NULL DEFAULT TRUE,
    "CreatedAt"    TIMESTAMPTZ NOT NULL DEFAULT now()
);

COMMENT ON TABLE "Range" IS
    'Police Range: the geographic tier between State and District, commanded by an IGP/DIG. Anchor for a senior_command seat with scope_type=range.';
COMMENT ON COLUMN "Range"."HQDistrictID" IS
    'District hosting the range headquarters. Advisory only — never a scope narrowing.';

-- ---------------------------------------------------------------------------
-- 2. Wing — the FUNCTIONAL tier (ADGP command). Not geographic.
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS "Wing" (
    "WingID"      INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "WingName"    VARCHAR NOT NULL UNIQUE,
    "WingCode"    VARCHAR NOT NULL UNIQUE,
    "Description" TEXT,
    "Active"      BOOLEAN NOT NULL DEFAULT TRUE,
    "CreatedAt"   TIMESTAMPTZ NOT NULL DEFAULT now()
);

COMMENT ON TABLE "Wing" IS
    'Functional wing headed by an ADGP (Law & Order, Crime & Technical Services, Intelligence, Internal Security & Cyber, Traffic & Road Safety, CID/Economic Offences). State-wide geography; narrowed by crime head via WingCrimeHead.';

-- ---------------------------------------------------------------------------
-- 3. WingCrimeHead — which crime heads a wing is accountable for.
--    This is the ONLY narrowing a wing seat gets; it has no geographic filter.
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS "WingCrimeHead" (
    "WingID"      INTEGER NOT NULL REFERENCES "Wing" ("WingID") ON DELETE CASCADE,
    "CrimeHeadID" INTEGER NOT NULL REFERENCES "CrimeHead" ("CrimeHeadID"),
    PRIMARY KEY ("WingID", "CrimeHeadID")
);

COMMENT ON TABLE "WingCrimeHead" IS
    'Crime heads in a wing''s remit. A wing with no rows here sees every head (e.g. Crime & Technical Services).';

-- ---------------------------------------------------------------------------
-- 4. District gains its range membership and a Commissionerate marker.
--    Both nullable/defaulted: unseeded means "not yet reconciled", which the
--    scope resolver treats as unresolved rather than as state-wide.
-- ---------------------------------------------------------------------------
ALTER TABLE "District"
    ADD COLUMN IF NOT EXISTS "RangeID" INTEGER REFERENCES "Range" ("RangeID");

ALTER TABLE "District"
    ADD COLUMN IF NOT EXISTS "IsCommissionerate" BOOLEAN NOT NULL DEFAULT FALSE;

ALTER TABLE "District"
    ADD COLUMN IF NOT EXISTS "CommandRank" VARCHAR;

COMMENT ON COLUMN "District"."RangeID" IS
    'Owning Range. NULL means either a Commissionerate (outside the range structure) or a district whose range membership is not yet reconciled — the two are distinguished by IsCommissionerate.';
COMMENT ON COLUMN "District"."IsCommissionerate" IS
    'TRUE for a city Police Commissionerate, commanded by a CP and reporting outside the range hierarchy.';
COMMENT ON COLUMN "District"."CommandRank" IS
    'Rank commanding this district-level unit (SP for a district, ADGP/DIG for a Commissionerate). Display/label only — never a permission.';

CREATE INDEX IF NOT EXISTS "idx_district_range" ON "District" ("RangeID");

-- Range/Wing carry no row-level policy of their own; they are reference tiers.
ALTER TABLE "Range"         DISABLE ROW LEVEL SECURITY;
ALTER TABLE "Wing"          DISABLE ROW LEVEL SECURITY;
ALTER TABLE "WingCrimeHead" DISABLE ROW LEVEL SECURITY;

COMMIT;
