-- DRISHTI migration 029: admin-controlled per-role UI visibility.
--
-- WHY
-- Which destinations, boards, KPI cards and widgets a role sees is currently
-- decided in code and cannot be changed without a deploy: `roleCan()` returns
-- true unconditionally, every RoleDef carries admin: true, and no Destination
-- carries a `roles` allow-list. Admin needs on/off control from the console.
--
-- DESIGN: DEFAULTS IN CODE, OVERRIDES IN THE DATABASE
-- An absent row means "use the registry default". A present row is an explicit
-- override. This matters for a growing product: a newly shipped KPI card is
-- visible per its registry default immediately, rather than being invisible
-- until an admin remembers to enable it for six roles.
--
-- scope_type NULL means the grant applies to every scope_type of that role, so
-- an admin can either hide a card from all of senior_command, or hide it only
-- from the wing seats and leave the range seats alone.
--
-- SCOPE OF CONTROL — VISIBILITY, NOT ACCESS
-- While authentication and RLS are off, these switches govern presentation
-- only. A hidden destination is still reachable by typing its URL and a hidden
-- card's endpoint still answers. The admin console states this; it is recorded
-- here so the table is never mistaken for an authorization boundary.

BEGIN;

CREATE TABLE IF NOT EXISTS "role_ui_grants" (
    "id"           INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "role_name"    VARCHAR NOT NULL REFERENCES "roles" ("role_name") ON DELETE CASCADE,
    "scope_type"   VARCHAR,
    "element_kind" VARCHAR NOT NULL,
    "element_id"   VARCHAR NOT NULL,
    "enabled"      BOOLEAN NOT NULL,
    "reason"       TEXT,
    "updated_by"   VARCHAR,
    "updated_at"   TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT "chk_role_ui_element_kind"
        CHECK ("element_kind" IN ('destination', 'board', 'kpi', 'widget')),
    CONSTRAINT "chk_role_ui_scope_type"
        CHECK ("scope_type" IS NULL OR "scope_type" IN (
            'state', 'wing', 'range', 'district', 'commissionerate',
            'station', 'assigned_case', 'platform'))
);

-- One override per (role, scope_type, element). scope_type is COALESCEd to '*'
-- rather than relying on NULLS NOT DISTINCT, which needs PostgreSQL 15+ and
-- would silently permit duplicate role-wide overrides on older servers — two
-- rows for the same element would make the effective value order-dependent.
CREATE UNIQUE INDEX IF NOT EXISTS "uq_role_ui_grants"
    ON "role_ui_grants" ("role_name", COALESCE("scope_type", '*'),
                         "element_kind", "element_id");

CREATE INDEX IF NOT EXISTS "idx_role_ui_grants_lookup"
    ON "role_ui_grants" ("role_name", "element_kind");

COMMENT ON TABLE "role_ui_grants" IS
    'Admin overrides for per-role UI visibility. An ABSENT row means "use the code registry default"; a present row overrides it. Presentation only — not an access-control boundary while auth and RLS are disabled.';
COMMENT ON COLUMN "role_ui_grants"."scope_type" IS
    'NULL applies the override to every scope_type of the role. A specific value targets only those seats (e.g. hide a card from wing seats but not range seats).';
COMMENT ON COLUMN "role_ui_grants"."element_kind" IS
    'destination = sidebar/route; board = a role dashboard; kpi = a KPI card id; widget = a dashboard widget id.';
COMMENT ON COLUMN "role_ui_grants"."reason" IS
    'Optional admin note recorded with the toggle, surfaced in the audit trail.';

ALTER TABLE "role_ui_grants" DISABLE ROW LEVEL SECURITY;

COMMIT;
