-- DRISHTI migration 034: faithful district-level police unit model.
--
-- WHY
-- The dataset carried 32 District rows that conflated two different kinds of
-- unit. Five of them — Mysuru, Dakshina Kannada, Dharwad, Belagavi, Kalaburagi —
-- were being asked to be simultaneously a city Police Commissionerate under a CP
-- and a rural police district under an SP. Those are distinct commands with
-- distinct station sets and case loads, and a range KPI that sums both is
-- reporting on two jurisdictions at once. KGF, a real Central Range district, was
-- missing entirely.
--
-- AFTER THIS MIGRATION
--   32 existing rows
--  + 5 city Commissionerates (Mysuru City, Mangaluru City, Hubballi-Dharwad,
--    Belagavi City, Kalaburagi City)
--  + 1 Central Range district (KGF)
--  = 38 district-level units: 32 range districts + 6 Commissionerates
--
-- Range membership then matches the official roster exactly (SR 5, WR 4, ER 4,
-- CR 6, NR 5, NER 3, BR 4 = 31), plus Bengaluru Urban as a recorded deviation in
-- Central Range, giving CR 7.
--
-- HOW THE SPLIT IS DRAWN
-- Stations are moved to a Commissionerate by TALUK, read from
-- UnitLocation."Taluk" — the only city/rural signal in the data, and the same
-- field datagen used to place each station. Every station keeps its coordinates;
-- only its parent changes. No station is created, deleted or moved in space.
--
-- WHAT DELIBERATELY DOES NOT CHANGE
-- CaseMaster."CrimeNo" embeds a 4-digit district code and is NOT rewritten. A
-- crime number is a permanent identifier; real jurisdictional reorganisations do
-- not renumber historical FIRs. Current district for a case is derived through
-- PoliceStationID -> Unit.DistrictID, so cases follow their station automatically
-- and the historical number stays truthful about where it was registered.

BEGIN;

-- ---------------------------------------------------------------------------
-- 1. Record provenance so the rollback can reverse the station moves exactly.
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS "DistrictSplitAudit" (
    "id"              INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "UnitID"          INTEGER NOT NULL,
    "FromDistrictID"  INTEGER NOT NULL,
    "ToDistrictID"    INTEGER NOT NULL,
    "Taluk"           VARCHAR,
    "MigrationTag"    VARCHAR NOT NULL DEFAULT '034_district_commissionerates',
    "CreatedAt"       TIMESTAMPTZ NOT NULL DEFAULT now()
);

COMMENT ON TABLE "DistrictSplitAudit" IS
    'Append-only record of station re-parenting performed by migration 034, so the split is auditable and exactly reversible.';

-- ---------------------------------------------------------------------------
-- 1b. Realign identity sequences before inserting.
--
-- datagen loads District and JurisdictionBoundary by COPY with EXPLICIT primary
-- keys. `GENERATED BY DEFAULT AS IDENTITY` permits that but does not advance the
-- underlying sequence, so it still sits at 1 while 32 District rows exist. The
-- first generated insert below would then collide with DistrictID 1 and fail on
-- District_pkey. Advance-only: setval is never allowed to rewind a sequence that
-- is already ahead, and a table with no rows is left untouched.
-- ---------------------------------------------------------------------------
SELECT setval(
    pg_get_serial_sequence('"District"', 'DistrictID'),
    GREATEST(
        (SELECT COALESCE(max("DistrictID"), 1) FROM "District"),
        (SELECT last_value FROM pg_sequences
          WHERE schemaname = 'public' AND sequencename = 'District_DistrictID_seq')),
    TRUE)
 WHERE EXISTS (SELECT 1 FROM "District");

SELECT setval(
    pg_get_serial_sequence('"JurisdictionBoundary"', 'JurisdictionBoundaryID'),
    GREATEST(
        (SELECT COALESCE(max("JurisdictionBoundaryID"), 1) FROM "JurisdictionBoundary"),
        (SELECT last_value FROM pg_sequences
          WHERE schemaname = 'public'
            AND sequencename = 'JurisdictionBoundary_JurisdictionBoundaryID_seq')),
    TRUE)
 WHERE EXISTS (SELECT 1 FROM "JurisdictionBoundary");

-- ---------------------------------------------------------------------------
-- 2. The five city Commissionerates + KGF.
--    Commissionerates sit OUTSIDE the range hierarchy (RangeID NULL,
--    IsCommissionerate TRUE). Per the official page the Bengaluru City CP holds
--    ADGP rank and the other five hold DIG rank.
-- ---------------------------------------------------------------------------
INSERT INTO "District" ("DistrictName", "StateID", "Active", "IsCommissionerate", "CommandRank")
SELECT v.name, 1, TRUE, TRUE, 'DIG'
  FROM (VALUES
        ('Mysuru City'),
        ('Mangaluru City'),
        ('Hubballi-Dharwad City'),
        ('Belagavi City'),
        ('Kalaburagi City')
       ) AS v(name)
 WHERE NOT EXISTS (SELECT 1 FROM "District" d WHERE d."DistrictName" = v.name);

INSERT INTO "District" ("DistrictName", "StateID", "Active", "IsCommissionerate", "CommandRank", "RangeID")
SELECT 'Kolar Gold Field (KGF)', 1, TRUE, FALSE, 'SP', r."RangeID"
  FROM "Range" r
 WHERE r."RangeCode" = 'CR'
   AND NOT EXISTS (SELECT 1 FROM "District" d
                    WHERE d."DistrictName" = 'Kolar Gold Field (KGF)');

-- ---------------------------------------------------------------------------
-- 3. Move city stations to their Commissionerate, by taluk.
--    Recorded first, then applied, so the audit cannot drift from the change.
-- ---------------------------------------------------------------------------
WITH mapping(taluk, parent_district, city_district) AS (
    VALUES
      ('Mysuru',     'Mysuru',           'Mysuru City'),
      ('Mangaluru',  'Dakshina Kannada', 'Mangaluru City'),
      ('Hubballi',   'Dharwad',          'Hubballi-Dharwad City'),
      ('Dharwad',    'Dharwad',          'Hubballi-Dharwad City'),
      ('Belagavi',   'Belagavi',         'Belagavi City'),
      ('Kalaburagi', 'Kalaburagi',       'Kalaburagi City')
),
moved AS (
    SELECT u."UnitID", u."DistrictID" AS from_id, cd."DistrictID" AS to_id, ul."Taluk"
      FROM "Unit" u
      JOIN "UnitLocation" ul ON ul."UnitID" = u."UnitID" AND ul."IsCurrent" = TRUE
      JOIN "District" pd ON pd."DistrictID" = u."DistrictID"
      JOIN mapping m ON m.taluk = ul."Taluk" AND m.parent_district = pd."DistrictName"
      JOIN "District" cd ON cd."DistrictName" = m.city_district
)
INSERT INTO "DistrictSplitAudit" ("UnitID", "FromDistrictID", "ToDistrictID", "Taluk")
SELECT "UnitID", from_id, to_id, "Taluk" FROM moved;

UPDATE "Unit" u
   SET "DistrictID" = a."ToDistrictID"
  FROM "DistrictSplitAudit" a
 WHERE a."UnitID" = u."UnitID"
   AND a."MigrationTag" = '034_district_commissionerates';

-- Officer establishment carries its own district column and must follow.
UPDATE "Employee" e
   SET "DistrictID" = u."DistrictID"
  FROM "Unit" u
 WHERE u."UnitID" = e."UnitID"
   AND e."DistrictID" <> u."DistrictID";

-- Commissionerate HQ units are re-parented to the new district-level row so the
-- Unit hierarchy stays coherent (station -> HQ -> district).
UPDATE "Unit" hq
   SET "DistrictID" = cd."DistrictID"
  FROM "District" cd
 WHERE cd."IsCommissionerate" = TRUE
   AND hq."UnitName" = replace(cd."DistrictName", ' City', '') || ' Commissionerate'
   AND hq."DistrictID" <> cd."DistrictID";

COMMIT;

-- ---------------------------------------------------------------------------
-- 4. Boundary polygons for the new district-level units.
--    Derived from geometry already present: a Commissionerate is the union of the
--    taluk polygons it took, and the rural remainder is its former district minus
--    that union. Separate transaction so a PostGIS failure cannot roll back the
--    structural split above.
-- ---------------------------------------------------------------------------
BEGIN;

-- 4a. Commissionerate polygons = union of their constituent taluks.
INSERT INTO "JurisdictionBoundary"
    ("Level", "Name", "StateID", "DistrictID", geom, "Version", "IsCurrent", "Source", "IsSynthetic")
SELECT 'district', cd."DistrictName", 1, cd."DistrictID",
       ST_Multi(ST_UnaryUnion(ST_Collect(tb.geom))), 1, TRUE,
       'dissolved from Level=taluk (KGIS-simplified)', TRUE
  FROM "District" cd
  JOIN (VALUES
        ('Mysuru City',           'Mysuru'),
        ('Mangaluru City',        'Mangaluru'),
        ('Hubballi-Dharwad City', 'Hubballi'),
        ('Hubballi-Dharwad City', 'Dharwad'),
        ('Belagavi City',         'Belagavi'),
        ('Kalaburagi City',       'Kalaburagi')
       ) AS v(city, taluk) ON v.city = cd."DistrictName"
  JOIN "JurisdictionBoundary" tb
    ON tb."Level" = 'taluk' AND tb."IsCurrent" = TRUE AND tb."Name" = v.taluk
 WHERE NOT EXISTS (
        SELECT 1 FROM "JurisdictionBoundary" x
         WHERE x."Level" = 'district' AND x."IsCurrent" = TRUE
           AND x."DistrictID" = cd."DistrictID")
 GROUP BY cd."DistrictID", cd."DistrictName";

-- 4b. Rural remainder = former district polygon MINUS the city polygon it lost.
--     The old row is superseded rather than updated, preserving boundary history.
WITH pairs(parent, city) AS (
    VALUES ('Mysuru','Mysuru City'), ('Dakshina Kannada','Mangaluru City'),
           ('Dharwad','Hubballi-Dharwad City'), ('Belagavi','Belagavi City'),
           ('Kalaburagi','Kalaburagi City')
),
remainder AS (
    SELECT pd."DistrictID" AS district_id, pd."DistrictName" AS name,
           pb."JurisdictionBoundaryID" AS old_id, pb."Version" AS old_version,
           ST_Multi(ST_CollectionExtract(
               ST_MakeValid(ST_Difference(pb.geom, cb.geom)), 3)) AS geom
      FROM pairs p
      JOIN "District" pd ON pd."DistrictName" = p.parent
      JOIN "District" cd ON cd."DistrictName" = p.city
      JOIN "JurisdictionBoundary" pb
        ON pb."DistrictID" = pd."DistrictID" AND pb."Level" = 'district' AND pb."IsCurrent" = TRUE
      JOIN "JurisdictionBoundary" cb
        ON cb."DistrictID" = cd."DistrictID" AND cb."Level" = 'district' AND cb."IsCurrent" = TRUE
),
superseded AS (
    UPDATE "JurisdictionBoundary" jb
       SET "IsCurrent" = FALSE, "ValidTo" = now()
      FROM remainder rm
     WHERE jb."JurisdictionBoundaryID" = rm.old_id
    RETURNING jb."JurisdictionBoundaryID"
)
INSERT INTO "JurisdictionBoundary"
    ("Level", "Name", "StateID", "DistrictID", geom, "Version", "IsCurrent", "Source", "IsSynthetic")
SELECT 'district', rm.name, 1, rm.district_id, rm.geom, rm.old_version + 1, TRUE,
       'district minus carved Commissionerate (KGIS-simplified)', TRUE
  FROM remainder rm
 WHERE rm.geom IS NOT NULL AND NOT ST_IsEmpty(rm.geom);

COMMIT;

-- ---------------------------------------------------------------------------
-- 5. Range polygons, now that district membership is final.
-- ---------------------------------------------------------------------------
BEGIN;

UPDATE "JurisdictionBoundary"
   SET "IsCurrent" = FALSE, "ValidTo" = now()
 WHERE "Level" = 'range' AND "IsCurrent" = TRUE;

INSERT INTO "JurisdictionBoundary"
    ("Level", "Name", "StateID", "RangeID", geom, "Version", "IsCurrent", "Source", "IsSynthetic")
SELECT 'range', rg."RangeName", rg."StateID", rg."RangeID",
       ST_Multi(ST_UnaryUnion(ST_Collect(jb.geom))), 1, TRUE,
       'dissolved from Level=district (KGIS-simplified)', TRUE
  FROM "Range" rg
  JOIN "District" d ON d."RangeID" = rg."RangeID"
  JOIN "JurisdictionBoundary" jb
    ON jb."DistrictID" = d."DistrictID" AND jb."Level" = 'district' AND jb."IsCurrent" = TRUE
 GROUP BY rg."RangeID", rg."RangeName", rg."StateID";

COMMIT;

-- ---------------------------------------------------------------------------
-- VERIFY
--   SELECT count(*) FROM "District";                        -- 38
--   SELECT count(*) FROM "District" WHERE "IsCommissionerate"; -- 6
--   SELECT r."RangeCode", count(d.*) FROM "Range" r
--     LEFT JOIN "District" d ON d."RangeID"=r."RangeID" GROUP BY 1 ORDER BY 1;
--     -- SR 5, WR 4, ER 4, CR 7, NR 5, NER 3, BR 4
--   SELECT "DistrictName" FROM "District"
--    WHERE "RangeID" IS NULL AND NOT "IsCommissionerate";   -- zero rows
--   SELECT count(*) FROM "Unit" u JOIN "District" d ON d."DistrictID"=u."DistrictID"
--    WHERE d."IsCommissionerate";                           -- stations now under a CP
--   SELECT count(*) FROM "Employee" e JOIN "Unit" u ON u."UnitID"=e."UnitID"
--    WHERE e."DistrictID" <> u."DistrictID";                -- zero rows
-- ---------------------------------------------------------------------------
