-- =============================================================================
-- Police FIR System — Phase 1.5: Schema Extensions & Reconciliation
-- Karnataka Police Department  /  DRISHTI
-- Target: PostgreSQL 15+ / Supabase
-- Depends on: police_fir_schema.sql AND police_fir_intelligence.sql (run FIRST)
-- =============================================================================
--
-- Additive, non-breaking migration that adds the tables the DRISHTI blueprint
-- (docs 00, 01, 04) assumes but the operational + intelligence schemas do not
-- yet contain:
--
--   A. Financial sub-graph      (Phase 11 money-trail, doc 04 §1)
--   B. Conversational / voice   (Phases 2-5, doc 01 §4.7)
--   C. Governance / RBAC        (Phase 14, doc 01 §4.8 / §7)
--   D. Reconciliation columns   (offender-level risk, edge provenance)
--
-- Conventions match the existing schema exactly: quoted PascalCase identifiers
-- for domain tables, GENERATED BY DEFAULT AS IDENTITY surrogate keys, TIMESTAMPTZ
-- timestamps, explicit FK btree indexes, GIN on JSONB, GiST on geometry, a
-- COMMENT ON TABLE for every table, and the shared fn_set_updated_at() trigger.
-- The RBAC tables intentionally use lower_snake_case names/columns because the
-- blueprint and the future RLS policies reference them that way
-- (roles, users, role_permissions, audit_logs).
--
-- SECURITY NOTICE: consistent with the base and intelligence schemas, ROW LEVEL
-- SECURITY IS LEFT DISABLED on every table here. On Supabase these tables are
-- reachable through the auto-generated API with default anon/authenticated
-- grants. Keep this on a private/trusted network, or re-enable RLS + policies
-- and revoke anon grants before any networked deploy (Phase 14). The financial,
-- chat and users tables below are SENSITIVE (PII / case-linked money flows).
-- =============================================================================

BEGIN;

-- -----------------------------------------------------------------------------
-- 1. Enum types (idempotent)
-- -----------------------------------------------------------------------------
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'chat_sender_enum') THEN
        CREATE TYPE chat_sender_enum AS ENUM ('user', 'assistant');
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'permission_action_enum') THEN
        CREATE TYPE permission_action_enum AS ENUM ('read', 'write', 'none');
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'account_type_enum') THEN
        CREATE TYPE account_type_enum AS ENUM
            ('savings', 'current', 'wallet', 'mule', 'business', 'unknown');
    END IF;
END$$;

-- =============================================================================
-- C. GOVERNANCE / RBAC  (created first so chat/audit FKs resolve)
--    Lower_snake_case by design — referenced verbatim by RLS in Phase 14.
-- =============================================================================

CREATE TABLE "roles" (
    "role_id"     INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "role_name"   VARCHAR NOT NULL UNIQUE,
    "description" TEXT,
    "is_system"   BOOLEAN NOT NULL DEFAULT FALSE,
    "created_at"  TIMESTAMPTZ NOT NULL DEFAULT now()
);
COMMENT ON TABLE "roles" IS 'RBAC roles. The 10 built-in command roles (app/roles.py) are seeded with is_system=true.';

CREATE TABLE "users" (
    "user_id"              INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "username"             VARCHAR NOT NULL UNIQUE,
    "display_name"         VARCHAR,
    "role_id"              INTEGER NOT NULL REFERENCES "roles" ("role_id"),
    "unit_id"              INTEGER REFERENCES "Unit" ("UnitID"),
    "is_active"            BOOLEAN NOT NULL DEFAULT TRUE,
    "must_reset_password"  BOOLEAN NOT NULL DEFAULT TRUE,
    "created_at"           TIMESTAMPTZ NOT NULL DEFAULT now(),
    "UpdatedAt"            TIMESTAMPTZ NOT NULL DEFAULT now()
);
COMMENT ON TABLE "users" IS 'Application users mapped to an RBAC role and (optionally) a Unit scope. SENSITIVE.';

CREATE TABLE "role_permissions" (
    "id"         INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "role_id"    INTEGER NOT NULL REFERENCES "roles" ("role_id") ON DELETE CASCADE,
    "resource"   TEXT NOT NULL,
    "action"     permission_action_enum NOT NULL,
    "created_at" TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT "uq_role_permissions" UNIQUE ("role_id", "resource", "action")
);
COMMENT ON TABLE "role_permissions" IS 'Resource/action grants per role. Drives the whitelisted-SELECT executor and Phase 14 RLS.';

CREATE TABLE "audit_logs" (
    "log_id"      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "user_id"     INTEGER REFERENCES "users" ("user_id"),
    "action"      TEXT NOT NULL,
    "resource"    TEXT,
    "resource_id" TEXT,
    "ip_address"  INET,
    "detail"      JSONB NOT NULL DEFAULT '{}'::jsonb,
    "created_at"  TIMESTAMPTZ NOT NULL DEFAULT now()
);
COMMENT ON TABLE "audit_logs" IS 'Append-only audit trail of user/model actions across the platform.';

-- =============================================================================
-- A. FINANCIAL SUB-GRAPH  (doc 04 §1 — Phase 11 money trail)
-- =============================================================================

CREATE TABLE "FinancialAccount" (
    "AccountID"  INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "AccountNo"  VARCHAR NOT NULL,
    "AccountType" account_type_enum NOT NULL DEFAULT 'unknown',
    "HolderName" VARCHAR,
    "EntityID"   BIGINT REFERENCES "EntityGraph" ("EntityID"),   -- link to graph node
    "Bank"       VARCHAR,
    "IFSC"       VARCHAR,
    "geom"       geometry(Point, 4326),                          -- branch / holder location
    "IsFlagged"  BOOLEAN NOT NULL DEFAULT FALSE,
    "Attributes" JSONB NOT NULL DEFAULT '{}'::jsonb,
    "CreatedAt"  TIMESTAMPTZ NOT NULL DEFAULT now(),
    "UpdatedAt"  TIMESTAMPTZ NOT NULL DEFAULT now()
);
COMMENT ON TABLE "FinancialAccount" IS 'Bank / wallet accounts, optionally tied to a graph entity. Mule accounts flagged. SENSITIVE.';

CREATE TABLE "FinancialTransaction" (
    "TransactionID"        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "SourceAccountID"      INTEGER NOT NULL REFERENCES "FinancialAccount" ("AccountID"),
    "DestinationAccountID" INTEGER NOT NULL REFERENCES "FinancialAccount" ("AccountID"),
    "Amount"               NUMERIC(14,2) NOT NULL CHECK ("Amount" >= 0),
    "TxnTimestamp"         TIMESTAMPTZ NOT NULL,
    "Channel"              VARCHAR,                                 -- imps/neft/upi/cash/atm
    "IsFlagged"            BOOLEAN NOT NULL DEFAULT FALSE,
    "FlagReason"           TEXT,                                    -- structuring / mule / rapid-fanout
    "EvidenceCaseID"       INTEGER REFERENCES "CaseMaster" ("CaseMasterID"),
    "Properties"           JSONB NOT NULL DEFAULT '{}'::jsonb,
    "CreatedAt"            TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT "chk_fintxn_no_self" CHECK ("SourceAccountID" <> "DestinationAccountID")
);
COMMENT ON TABLE "FinancialTransaction" IS 'Directed money movements between accounts; flagged rows carry the reason (structuring, mule, fan-out). SENSITIVE.';

CREATE TABLE "TransactionLink" (
    "LinkID"        INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "TransactionID" BIGINT NOT NULL REFERENCES "FinancialTransaction" ("TransactionID") ON DELETE CASCADE,
    "CaseMasterID"  INTEGER NOT NULL REFERENCES "CaseMaster" ("CaseMasterID"),
    "LinkType"      VARCHAR,                                  -- evidence / suspected / proceeds
    "Confidence"    NUMERIC(6,5) CHECK ("Confidence" IS NULL OR "Confidence" BETWEEN 0 AND 1),
    "CreatedAt"     TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT "uq_transactionlink" UNIQUE ("TransactionID", "CaseMasterID")
);
COMMENT ON TABLE "TransactionLink" IS 'Many-to-many links between financial transactions and the cases that evidence them.';

-- =============================================================================
-- B. CONVERSATIONAL / VOICE  (doc 01 §4.7 — Phases 2-5)
-- =============================================================================

CREATE TABLE "ChatSession" (
    "SessionID"   INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "UserID"      INTEGER REFERENCES "users" ("user_id"),
    "OwnerSubject" VARCHAR(160),                            -- catalyst:<id> / hashed local actor
    "Role"        VARCHAR,                                  -- role snapshot at session time
    "Language"  VARCHAR,                                    -- en / kn
    "Title"     VARCHAR,
    "CreatedAt" TIMESTAMPTZ NOT NULL DEFAULT now()
);
COMMENT ON TABLE "ChatSession" IS 'Ask-DRISHTI conversation sessions (one per user thread).';

CREATE TABLE "ChatMessage" (
    "MessageID"      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "SessionID"      INTEGER NOT NULL REFERENCES "ChatSession" ("SessionID") ON DELETE CASCADE,
    "Sender"         chat_sender_enum NOT NULL,
    "ContentText"    TEXT,
    "Language"       VARCHAR,
    "GeneratedSQL"   TEXT,                                   -- NL->SQL proposed query (assistant turns)
    "CitedRecordIds" JSONB NOT NULL DEFAULT '[]'::jsonb,     -- source_record_ids[] for provenance
    "Confidence"     NUMERIC(6,5) CHECK ("Confidence" IS NULL OR "Confidence" BETWEEN 0 AND 1),
    "ModelVersionID" INTEGER REFERENCES "ModelVersion" ("ModelVersionID"),
    "CreatedAt"      TIMESTAMPTZ NOT NULL DEFAULT now()
);
COMMENT ON TABLE "ChatMessage" IS 'Messages in a chat session. Assistant turns honour the answer/confidence/source_record_ids/model_version contract.';

CREATE TABLE "VoiceTranscript" (
    "TranscriptID"    INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "MessageID"       BIGINT REFERENCES "ChatMessage" ("MessageID") ON DELETE SET NULL,
    "RawAudioRef"     VARCHAR,                               -- storage ref to the audio blob
    "TranscriptText"  TEXT,
    "Language"        VARCHAR,
    "Confidence"      NUMERIC(6,5) CHECK ("Confidence" IS NULL OR "Confidence" BETWEEN 0 AND 1),
    "IsLowConfidence" BOOLEAN NOT NULL DEFAULT FALSE,
    "CreatedAt"       TIMESTAMPTZ NOT NULL DEFAULT now()
);
COMMENT ON TABLE "VoiceTranscript" IS 'Speech-to-text transcripts for voice queries; low-confidence rows prompt read-back confirmation.';

CREATE TABLE "SavedQuery" (
    "SavedQueryID" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "UserID"       INTEGER REFERENCES "users" ("user_id"),
    "Name"         VARCHAR NOT NULL,
    "PromptText"   TEXT,
    "Scope"        JSONB NOT NULL DEFAULT '{}'::jsonb,       -- district/unit/time filters
    "CreatedAt"    TIMESTAMPTZ NOT NULL DEFAULT now()
);
COMMENT ON TABLE "SavedQuery" IS 'User-saved natural-language queries / cohorts for reuse.';

-- =============================================================================
-- D. RECONCILIATION — additive nullable columns for the ML phases
-- =============================================================================
ALTER TABLE "CrimeRiskScore"
    ADD COLUMN IF NOT EXISTS "AccusedMasterID" INTEGER
    REFERENCES "Accused" ("AccusedMasterID");                -- offender-level risk (Phase 9)

ALTER TABLE "NetworkEdge"
    ADD COLUMN IF NOT EXISTS "EvidenceCaseID" INTEGER
    REFERENCES "CaseMaster" ("CaseMasterID");                -- edge provenance (Phase 6/11)

-- =============================================================================
-- 2. TRIGGERS (updated_at maintenance — reuse shared fn_set_updated_at())
-- =============================================================================
CREATE TRIGGER "trg_financialaccount_updated" BEFORE UPDATE ON "FinancialAccount"
    FOR EACH ROW EXECUTE FUNCTION fn_set_updated_at();
CREATE TRIGGER "trg_users_updated"            BEFORE UPDATE ON "users"
    FOR EACH ROW EXECUTE FUNCTION fn_set_updated_at();

-- =============================================================================
-- 3. INDEXES
-- =============================================================================

-- ---- FK / lookup btree indexes ----------------------------------------------
CREATE INDEX "idx_users_role"             ON "users" ("role_id");
CREATE INDEX "idx_users_unit"             ON "users" ("unit_id");
CREATE INDEX "idx_rolepermissions_role"   ON "role_permissions" ("role_id");
CREATE INDEX "idx_rolepermissions_res"    ON "role_permissions" ("resource");
CREATE INDEX "idx_auditlogs_created"      ON "audit_logs" ("created_at");
CREATE INDEX "idx_auditlogs_user"         ON "audit_logs" ("user_id");

CREATE INDEX "idx_finaccount_entity"      ON "FinancialAccount" ("EntityID");
CREATE INDEX "idx_finaccount_flagged"     ON "FinancialAccount" ("IsFlagged");
CREATE INDEX "idx_fintxn_source"          ON "FinancialTransaction" ("SourceAccountID");
CREATE INDEX "idx_fintxn_destination"     ON "FinancialTransaction" ("DestinationAccountID");
CREATE INDEX "idx_fintxn_evidencecase"    ON "FinancialTransaction" ("EvidenceCaseID");
CREATE INDEX "idx_fintxn_timestamp"       ON "FinancialTransaction" ("TxnTimestamp");
CREATE INDEX "idx_fintxn_flagged"         ON "FinancialTransaction" ("IsFlagged");
CREATE INDEX "idx_txnlink_case"           ON "TransactionLink" ("CaseMasterID");

CREATE INDEX "idx_chatsession_user"       ON "ChatSession" ("UserID");
CREATE INDEX "idx_chatmessage_session"    ON "ChatMessage" ("SessionID");
CREATE INDEX "idx_chatmessage_model"      ON "ChatMessage" ("ModelVersionID");
CREATE INDEX "idx_voicetranscript_msg"    ON "VoiceTranscript" ("MessageID");
CREATE INDEX "idx_savedquery_user"        ON "SavedQuery" ("UserID");

CREATE INDEX "idx_riskscore_accused"      ON "CrimeRiskScore" ("AccusedMasterID");
CREATE INDEX "idx_networkedge_evidence"   ON "NetworkEdge" ("EvidenceCaseID");

-- ---- GIN indexes on JSONB ---------------------------------------------------
CREATE INDEX "gin_auditlogs_detail"       ON "audit_logs" USING GIN ("detail");
CREATE INDEX "gin_finaccount_attrs"       ON "FinancialAccount" USING GIN ("Attributes");
CREATE INDEX "gin_fintxn_props"           ON "FinancialTransaction" USING GIN ("Properties");
CREATE INDEX "gin_chatmessage_cited"      ON "ChatMessage" USING GIN ("CitedRecordIds");
CREATE INDEX "gin_savedquery_scope"       ON "SavedQuery" USING GIN ("Scope");

-- ---- PostGIS spatial (GiST) index -------------------------------------------
CREATE INDEX "gist_finaccount_geom"       ON "FinancialAccount" USING GIST ("geom");

-- =============================================================================
-- 4. SEED — the 10 command roles + role/permission matrix (doc 01 §7)
--    Mirrors services/ml/app/roles.py and web/src/config/roles.ts.
-- =============================================================================
INSERT INTO "roles" ("role_name", "description", "is_system") VALUES
    ('dgp_state_command',     'State command: state-wide priorities, escalations and outcomes.',      TRUE),
    ('adgp_igp_range',        'Range command: oversight and comparison across the range''s districts.', TRUE),
    ('sp_district_command',   'District command: workload, approvals and station performance.',        TRUE),
    ('dysp_acp',              'Sub-divisional oversight: case review, quality and escalation.',        TRUE),
    ('sho',                   'Station chief: registration, assignment and the station review queue.', TRUE),
    ('investigating_officer', 'Field IO: assigned cases, evidence, statements and leads.',             TRUE),
    ('crime_analyst',         'Crime analysis: patterns, networks, hotspots and forecasting.',         TRUE),
    ('cyber_cell',            'Cyber / financial crime: money trail, devices and accounts.',           TRUE),
    ('traffic_command',       'Traffic command: road-safety hotspots and enforcement load.',           TRUE),
    ('system_admin',          'Platform administration: credentials, model registry and governance.',  TRUE)
ON CONFLICT ("role_name") DO NOTHING;

-- Resource/action matrix. Resources map to the 8 destinations plus sensitive
-- data domains (money_trail, pii). One action per (role, resource).
-- INTERIM ("all roles have access to everything"): every role is granted WRITE
-- on every resource — the cross join below. Replace with explicit per-role rows
-- when the real RBAC matrix lands (see services/ml/app/roles.py).
INSERT INTO "role_permissions" ("role_id", "resource", "action")
SELECT r."role_id", v.resource, 'write'::permission_action_enum
FROM "roles" r
CROSS JOIN (VALUES
    ('command_center'), ('cases'), ('people_entities'), ('network_analysis'),
    ('money_trail'), ('map'), ('analytics'), ('ask_drishti'),
    ('admin_governance'), ('pii')
) AS v(resource)
WHERE r."role_name" IN (
    'dgp_state_command', 'adgp_igp_range', 'sp_district_command', 'dysp_acp',
    'sho', 'investigating_officer', 'crime_analyst', 'cyber_cell',
    'traffic_command', 'system_admin')
ON CONFLICT ("role_id", "resource", "action") DO NOTHING;

-- One demo user per role so conversational data & audit have owners.
-- must_reset_password=TRUE — these are placeholders, not real credentials.
INSERT INTO "users" ("username", "display_name", "role_id", "is_active", "must_reset_password")
SELECT v.username, v.display_name, r."role_id", TRUE, TRUE
FROM "roles" r
JOIN (VALUES
    ('dgp.vikram',    'DGP Vikram Shetty',        'dgp_state_command'),
    ('igp.meenakshi', 'IGP Meenakshi Rao',        'adgp_igp_range'),
    ('sp.anand',      'SP Anand Kumar',           'sp_district_command'),
    ('dysp.kavya',    'Dy.SP Kavya Hegde',        'dysp_acp'),
    ('sho.suresh',    'SHO Suresh Patil',         'sho'),
    ('io.ramesh',     'PSI Ramesh Gowda',         'investigating_officer'),
    ('analyst.divya', 'Analyst Divya Naik',       'crime_analyst'),
    ('cyber.arjun',   'Insp. Arjun Bhat (CEN)',   'cyber_cell'),
    ('traffic.latha', 'Traffic ACP Latha Prasad', 'traffic_command'),
    ('admin',         'Sysadmin Nikhil Jain',     'system_admin')
) AS v(username, display_name, role_name) ON r."role_name" = v.role_name
ON CONFLICT ("username") DO NOTHING;

-- =============================================================================
-- 5. ROW LEVEL SECURITY — explicitly DISABLED on every new table
--    (Phase 14 re-enables and drives it from role_permissions.)
-- =============================================================================
ALTER TABLE "roles"                DISABLE ROW LEVEL SECURITY;
ALTER TABLE "users"                DISABLE ROW LEVEL SECURITY;
ALTER TABLE "role_permissions"     DISABLE ROW LEVEL SECURITY;
ALTER TABLE "audit_logs"           DISABLE ROW LEVEL SECURITY;
ALTER TABLE "FinancialAccount"     DISABLE ROW LEVEL SECURITY;
ALTER TABLE "FinancialTransaction" DISABLE ROW LEVEL SECURITY;
ALTER TABLE "TransactionLink"      DISABLE ROW LEVEL SECURITY;
ALTER TABLE "ChatSession"          DISABLE ROW LEVEL SECURITY;
ALTER TABLE "ChatMessage"          DISABLE ROW LEVEL SECURITY;
ALTER TABLE "VoiceTranscript"      DISABLE ROW LEVEL SECURITY;
ALTER TABLE "SavedQuery"           DISABLE ROW LEVEL SECURITY;

COMMIT;

-- =============================================================================
-- End of extensions migration.
-- =============================================================================
