-- =============================================================================
-- Police FIR System — Production PostgreSQL Schema
-- Karnataka Police Department
-- Generated 1:1 from: Police_FIR_ER_Diagram.pdf
-- Target: PostgreSQL 15+ / Supabase (PostGIS enabled)
-- =============================================================================
--
-- Fidelity notes (nothing invented; every table below appears in the ER diagram):
--   * 26 tables are defined with full column lists in the diagram.
--   * 2 tables (Inv_OccuranceTime, inv_arrestsurrenderaccused) appear ONLY in the
--     "Relationship Matrix" with no column grid. They are created minimally from
--     the exact relationships the matrix documents. See the marked sections.
--   * Identifiers are preserved EXACTLY as written in the diagram using quoted,
--     case-sensitive names (e.g. "CaseMaster", "caste_master_id"). Query them
--     with the same casing from Supabase / PostgREST.
--
-- Type mapping (SQL Server dialect in the diagram -> PostgreSQL):
--   INT           -> INTEGER  (surrogate PKs use GENERATED BY DEFAULT AS IDENTITY)
--   VARCHAR       -> VARCHAR  (no lengths were given in the diagram)
--   Nvarchar(Max) -> TEXT
--   DATE          -> DATE
--   DATETIME      -> TIMESTAMPTZ  (timezone-aware, production best practice)
--   DECIMAL       -> NUMERIC(9,6) for lat/long
--   BIT           -> BOOLEAN
--   CHAR (cstype) -> ENUM
--
-- Reconciled inconsistencies (the diagram itself is inconsistent here; a valid
-- FK requires matching key types, so the child column adopts the parent PK type):
--   * ActSectionAssociation."ActID"    labeled INT but FK -> Act."ActCode" (VARCHAR)
--   * ActSectionAssociation."SectionID" labeled INT but FK -> Section."SectionCode" (VARCHAR)
--
-- SECURITY NOTICE (read before deploying to Supabase):
--   RLS is DISABLED on every table as explicitly requested. On Supabase the
--   public schema is exposed through the auto-generated REST/GraphQL API, and
--   the anon/authenticated roles hold default privileges. With RLS disabled,
--   any client holding the anon key can read/write these tables. Only deploy
--   this as-is on a trusted/private network, or re-enable RLS + policies and
--   revoke anon grants before exposing publicly.
-- =============================================================================

BEGIN;

-- -----------------------------------------------------------------------------
-- 0. Extensions
-- -----------------------------------------------------------------------------
CREATE EXTENSION IF NOT EXISTS postgis;

-- -----------------------------------------------------------------------------
-- 1. Enum types
--    cstype is the only column in the diagram with an explicit, closed value
--    set: A -> Chargesheet, B -> False Case, C -> Undetected.
-- -----------------------------------------------------------------------------
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'cstype_enum') THEN
        CREATE TYPE cstype_enum AS ENUM ('A', 'B', 'C');
    END IF;
END$$;

-- =============================================================================
-- 2. TABLES  (created in dependency order so inline FKs resolve)
-- =============================================================================

-- ---- Geography / administrative reference tables ----------------------------

CREATE TABLE "State" (
    "StateID"       INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "StateName"     VARCHAR NOT NULL,
    "NationalityID" INTEGER,                       -- lookup value; no lookup table in diagram
    "Active"        BOOLEAN NOT NULL DEFAULT TRUE
);
COMMENT ON TABLE "State" IS 'States. Referenced by Court, District, Unit, ArrestSurrender.';

CREATE TABLE "District" (
    "DistrictID"   INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "DistrictName" VARCHAR NOT NULL,
    "StateID"      INTEGER NOT NULL REFERENCES "State" ("StateID"),
    "Active"       BOOLEAN NOT NULL DEFAULT TRUE
);
COMMENT ON TABLE "District" IS 'Districts. Referenced by Court, Unit, Employee, ArrestSurrender.';

CREATE TABLE "UnitType" (
    "UnitTypeID"   INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "UnitTypeName" VARCHAR NOT NULL,
    "CityDistState" VARCHAR,                       -- Operational level: City / District / State
    "Hierarchy"    INTEGER,                        -- lower = higher authority
    "Active"       BOOLEAN NOT NULL DEFAULT TRUE
);
COMMENT ON TABLE "UnitType" IS 'Unit/station type. Referenced by Unit.TypeID.';

CREATE TABLE "Unit" (
    "UnitID"        INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "UnitName"      VARCHAR NOT NULL,
    "TypeID"        INTEGER REFERENCES "UnitType" ("UnitTypeID"),
    "ParentUnit"    INTEGER REFERENCES "Unit" ("UnitID"),   -- self-reference for hierarchy
    "NationalityID" INTEGER,
    "StateID"       INTEGER REFERENCES "State" ("StateID"),
    "DistrictID"    INTEGER REFERENCES "District" ("DistrictID"),
    "Active"        BOOLEAN NOT NULL DEFAULT TRUE
);
COMMENT ON TABLE "Unit" IS 'Police units/stations. Referenced by CaseMaster.PoliceStationID, Employee.UnitID, ArrestSurrender.PoliceStationID.';

CREATE TABLE "Rank" (
    "RankID"    INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "RankName"  VARCHAR NOT NULL,
    "Hierarchy" INTEGER,                           -- lower = higher rank
    "Active"    BOOLEAN NOT NULL DEFAULT TRUE
);
COMMENT ON TABLE "Rank" IS 'Police ranks. Referenced by Employee.RankID.';

CREATE TABLE "Designation" (
    "DesignationID"   INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "DesignationName" VARCHAR NOT NULL,
    "Active"          BOOLEAN NOT NULL DEFAULT TRUE,
    "SortOrder"       INTEGER
);
COMMENT ON TABLE "Designation" IS 'Designations. Referenced by Employee.DesignationID.';

CREATE TABLE "Employee" (
    "EmployeeID"          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "DistrictID"          INTEGER REFERENCES "District" ("DistrictID"),
    "UnitID"              INTEGER REFERENCES "Unit" ("UnitID"),
    "RankID"              INTEGER REFERENCES "Rank" ("RankID"),
    "DesignationID"       INTEGER REFERENCES "Designation" ("DesignationID"),
    "KGID"                VARCHAR UNIQUE,          -- unique government employee number
    "FirstName"           VARCHAR NOT NULL,
    "EmployeeDOB"         DATE,
    "GenderID"            INTEGER,                 -- lookup value
    "BloodGroupID"        INTEGER,                 -- lookup value
    "PhysicallyChallenged" BOOLEAN NOT NULL DEFAULT FALSE,
    "AppointmentDate"     DATE
);
COMMENT ON TABLE "Employee" IS 'Police employees. Referenced by CaseMaster.PolicePersonID, ArrestSurrender.IOID, ChargesheetDetails.PolicePersonID.';

CREATE TABLE "Court" (
    "CourtID"    INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "CourtName"  VARCHAR NOT NULL,
    "DistrictID" INTEGER REFERENCES "District" ("DistrictID"),
    "StateID"    INTEGER REFERENCES "State" ("StateID"),
    "Active"     BOOLEAN NOT NULL DEFAULT TRUE
);
COMMENT ON TABLE "Court" IS 'Courts. Referenced by CaseMaster.CourtID, ArrestSurrender.CourtID.';

-- ---- Case classification lookups --------------------------------------------

CREATE TABLE "CaseCategory" (
    "CaseCategoryID" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "LookupValue"    VARCHAR NOT NULL              -- FIR, UDR, PAR, ...
);
COMMENT ON TABLE "CaseCategory" IS 'Case category (FIR/UDR/PAR/...). Referenced by CaseMaster.CaseCategoryID.';

CREATE TABLE "GravityOffence" (
    "GravityOffenceID" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "LookupValue"      VARCHAR NOT NULL            -- Heinous, Non-Heinous, ...
);
COMMENT ON TABLE "GravityOffence" IS 'Gravity level. Referenced by CaseMaster.GravityOffenceID.';

CREATE TABLE "CrimeHead" (
    "CrimeHeadID"    INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "CrimeGroupName" VARCHAR NOT NULL,             -- e.g. Crimes Against Body
    "Active"         BOOLEAN NOT NULL DEFAULT TRUE
);
COMMENT ON TABLE "CrimeHead" IS 'Major crime head. Referenced by CaseMaster.CrimeMajorHeadID, CrimeSubHead, CrimeHeadActSection.';

CREATE TABLE "CrimeSubHead" (
    "CrimeSubHeadID" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "CrimeHeadID"    INTEGER NOT NULL REFERENCES "CrimeHead" ("CrimeHeadID"),
    "CrimeHeadName"  VARCHAR NOT NULL,             -- e.g. Murder, Robbery
    "SeqID"          INTEGER                       -- display/sort sequence
);
COMMENT ON TABLE "CrimeSubHead" IS 'Crime sub-head. Referenced by CaseMaster.CrimeMinorHeadID.';

CREATE TABLE "CaseStatusMaster" (
    "CaseStatusID"   INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "CaseStatusName" VARCHAR NOT NULL              -- Under Investigation, Charge Sheeted, Closed
);
COMMENT ON TABLE "CaseStatusMaster" IS 'Case status. Referenced by CaseMaster.CaseStatusID.';

-- ---- Person attribute lookups -----------------------------------------------

CREATE TABLE "CasteMaster" (
    "caste_master_id"   INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "caste_master_name" VARCHAR NOT NULL
);
COMMENT ON TABLE "CasteMaster" IS 'Caste. Referenced by ComplainantDetails.CasteID.';

CREATE TABLE "ReligionMaster" (
    "ReligionID"   INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "ReligionName" VARCHAR NOT NULL                -- Hindu, Muslim, Christian, ...
);
COMMENT ON TABLE "ReligionMaster" IS 'Religion. Referenced by ComplainantDetails.ReligionID.';

CREATE TABLE "OccupationMaster" (
    "OccupationID"   INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "OccupationName" VARCHAR NOT NULL              -- Farmer, Government Employee, ...
);
COMMENT ON TABLE "OccupationMaster" IS 'Occupation. Referenced by ComplainantDetails.OccupationID.';

-- ---- Legal acts & sections --------------------------------------------------

CREATE TABLE "Act" (
    "ActCode"        VARCHAR PRIMARY KEY,          -- natural key, e.g. IPC, NDPS
    "ActDescription" VARCHAR,
    "ShortName"      VARCHAR,
    "Active"         BOOLEAN NOT NULL DEFAULT TRUE
);
COMMENT ON TABLE "Act" IS 'Legal acts. Referenced by Section, CrimeHeadActSection, ActSectionAssociation.';

-- Section: the diagram marks no PK but the Relationship Matrix references
-- Section."SectionCode" as an FK target, so SectionCode must be unique -> PK.
CREATE TABLE "Section" (
    "SectionCode"        VARCHAR PRIMARY KEY,      -- e.g. 302, 307
    "ActCode"            VARCHAR NOT NULL REFERENCES "Act" ("ActCode"),
    "SectionDescription" VARCHAR,
    "Active"             BOOLEAN NOT NULL DEFAULT TRUE
);
COMMENT ON TABLE "Section" IS 'Sections of an act. FK target of ActSectionAssociation.SectionID.';

CREATE TABLE "CrimeHeadActSection" (
    "CrimeHeadID" INTEGER NOT NULL REFERENCES "CrimeHead" ("CrimeHeadID"),
    "ActCode"     VARCHAR NOT NULL REFERENCES "Act" ("ActCode"),
    "SectionCode" VARCHAR NOT NULL,                -- plain column: matrix declares no FK here
    PRIMARY KEY ("CrimeHeadID", "ActCode", "SectionCode")
);
COMMENT ON TABLE "CrimeHeadActSection" IS 'Maps a crime head to act/section combinations.';

-- ---- Core case / FIR table --------------------------------------------------

CREATE TABLE "CaseMaster" (
    "CaseMasterID"       INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "CrimeNo"            VARCHAR NOT NULL UNIQUE,  -- 18-digit structured, globally unique
    "CaseNo"             VARCHAR,                  -- YYYY + 5-digit serial (last 9 of CrimeNo)
    "CrimeRegisteredDate" DATE NOT NULL DEFAULT CURRENT_DATE,
    "PolicePersonID"     INTEGER NOT NULL REFERENCES "Employee" ("EmployeeID"),
    "PoliceStationID"    INTEGER NOT NULL REFERENCES "Unit" ("UnitID"),
    "CaseCategoryID"     INTEGER NOT NULL REFERENCES "CaseCategory" ("CaseCategoryID"),
    "GravityOffenceID"   INTEGER REFERENCES "GravityOffence" ("GravityOffenceID"),
    "CrimeMajorHeadID"   INTEGER REFERENCES "CrimeHead" ("CrimeHeadID"),
    "CrimeMinorHeadID"   INTEGER REFERENCES "CrimeSubHead" ("CrimeSubHeadID"),
    "CaseStatusID"       INTEGER REFERENCES "CaseStatusMaster" ("CaseStatusID"),
    "CourtID"            INTEGER REFERENCES "Court" ("CourtID"),
    "IncidentFromDate"   TIMESTAMPTZ,
    "IncidentToDate"     TIMESTAMPTZ,
    "InfoReceivedPSDate" TIMESTAMPTZ,
    "latitude"           NUMERIC(9,6),
    "longitude"          NUMERIC(9,6),
    "BriefFacts"         TEXT,
    -- PostGIS: point derived from lat/long (WGS84 / SRID 4326), auto-maintained.
    "geom" geometry(Point, 4326) GENERATED ALWAYS AS (
        CASE
            WHEN "longitude" IS NOT NULL AND "latitude" IS NOT NULL
            THEN ST_SetSRID(ST_MakePoint("longitude", "latitude"), 4326)
        END
    ) STORED,
    CONSTRAINT "chk_casemaster_latitude"  CHECK ("latitude"  IS NULL OR "latitude"  BETWEEN -90  AND 90),
    CONSTRAINT "chk_casemaster_longitude" CHECK ("longitude" IS NULL OR "longitude" BETWEEN -180 AND 180),
    CONSTRAINT "chk_casemaster_incident_range" CHECK (
        "IncidentFromDate" IS NULL OR "IncidentToDate" IS NULL
        OR "IncidentToDate" >= "IncidentFromDate"
    )
);
COMMENT ON TABLE "CaseMaster" IS 'FIR / case master. Parent of Victim, Accused, ArrestSurrender, ComplainantDetails, ActSectionAssociation, ChargesheetDetails, Inv_OccuranceTime.';
COMMENT ON COLUMN "CaseMaster"."CrimeNo" IS '1 digit Case Category + 4 digit District + 4 digit Unit + 4 digit Year + 5 digit serial (18 digits).';

-- ---- Case child tables ------------------------------------------------------

CREATE TABLE "ComplainantDetails" (
    "ComplainantID"   INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "CaseMasterID"    INTEGER NOT NULL REFERENCES "CaseMaster" ("CaseMasterID"),
    "ComplainantName" VARCHAR NOT NULL,
    "AgeYear"         INTEGER CHECK ("AgeYear" IS NULL OR "AgeYear" >= 0),
    "OccupationID"    INTEGER REFERENCES "OccupationMaster" ("OccupationID"),
    "ReligionID"      INTEGER REFERENCES "ReligionMaster" ("ReligionID"),
    "CasteID"         INTEGER REFERENCES "CasteMaster" ("caste_master_id"),
    "GenderID"        INTEGER                      -- lookup value; no lookup table in diagram
);
COMMENT ON TABLE "ComplainantDetails" IS 'Complainants for a case (one FIR -> many complainants).';

-- ActSectionAssociation: junction (no PK in diagram). ActID/SectionID are labeled
-- INT in the grid but the matrix maps them to VARCHAR keys; types reconciled.
CREATE TABLE "ActSectionAssociation" (
    "CaseMasterID"   INTEGER NOT NULL REFERENCES "CaseMaster" ("CaseMasterID"),
    "ActID"          VARCHAR NOT NULL REFERENCES "Act" ("ActCode"),
    "SectionID"      VARCHAR NOT NULL REFERENCES "Section" ("SectionCode"),
    "ActOrderID"     INTEGER,                      -- print order of act
    "SectionOrderID" INTEGER,                      -- print order of section
    PRIMARY KEY ("CaseMasterID", "ActID", "SectionID")
);
COMMENT ON TABLE "ActSectionAssociation" IS 'Act/section charges applied to a case (one FIR -> many act-sections).';

CREATE TABLE "Victim" (
    "VictimMasterID" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "CaseMasterID"   INTEGER NOT NULL REFERENCES "CaseMaster" ("CaseMasterID"),
    "VictimName"     VARCHAR NOT NULL,
    "AgeYear"        INTEGER CHECK ("AgeYear" IS NULL OR "AgeYear" >= 0),
    "GenderID"       INTEGER,                      -- lookup value (m/f/t)
    "VictimPolice"   VARCHAR CHECK ("VictimPolice" IS NULL OR "VictimPolice" IN ('0','1'))  -- 1 if victim is police else 0
);
COMMENT ON TABLE "Victim" IS 'Victims of a case (one FIR -> many victims).';

CREATE TABLE "Accused" (
    "AccusedMasterID" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "CaseMasterID"    INTEGER NOT NULL REFERENCES "CaseMaster" ("CaseMasterID"),
    "AccusedName"     VARCHAR NOT NULL,
    "AgeYear"         INTEGER CHECK ("AgeYear" IS NULL OR "AgeYear" >= 0),
    "GenderID"        INTEGER,                     -- M/F/T
    "PersonID"        VARCHAR                      -- accused sort key A1, A2, A3...
);
COMMENT ON TABLE "Accused" IS 'Accused persons of a case (one FIR -> many accused).';

CREATE TABLE "ArrestSurrender" (
    "ArrestSurrenderID"        INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "CaseMasterID"             INTEGER NOT NULL REFERENCES "CaseMaster" ("CaseMasterID"),
    "ArrestSurrenderTypeID"    INTEGER,            -- arrest vs surrender (lookup value)
    "ArrestSurrenderDate"      DATE,
    "ArrestSurrenderStateId"   INTEGER REFERENCES "State" ("StateID"),
    "ArrestSurrenderDistrictId" INTEGER REFERENCES "District" ("DistrictID"),
    "PoliceStationID"          INTEGER REFERENCES "Unit" ("UnitID"),
    "IOID"                     INTEGER REFERENCES "Employee" ("EmployeeID"),
    "CourtID"                  INTEGER REFERENCES "Court" ("CourtID"),
    "AccusedMasterID"          INTEGER REFERENCES "Accused" ("AccusedMasterID"),
    "IsAccused"                BOOLEAN NOT NULL DEFAULT FALSE,
    "IsComplainantAccused"     BOOLEAN NOT NULL DEFAULT FALSE
);
COMMENT ON TABLE "ArrestSurrender" IS 'Arrest / surrender events for a case (one FIR -> many events).';

CREATE TABLE "ChargesheetDetails" (
    "CSID"           INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "CaseMasterID"   INTEGER NOT NULL REFERENCES "CaseMaster" ("CaseMasterID"),
    "csdate"         TIMESTAMPTZ,                  -- chargesheeted date
    "cstype"         cstype_enum,                  -- A=Chargesheet, B=False Case, C=Undetected
    "PolicePersonID" INTEGER REFERENCES "Employee" ("EmployeeID")
);
COMMENT ON TABLE "ChargesheetDetails" IS 'Chargesheet / final report details for a case.';

-- ---- Matrix-only tables (no column grid in the diagram) ---------------------
-- Inv_OccuranceTime: matrix says "CaseMaster 1:1 Inv_OccuranceTime (CaseMasterID)".
-- No columns were documented, so only the documented key/relationship is created.
-- The UNIQUE (via PK on the FK) enforces the one-to-one cardinality.
CREATE TABLE "Inv_OccuranceTime" (
    "CaseMasterID" INTEGER PRIMARY KEY REFERENCES "CaseMaster" ("CaseMasterID")
);
COMMENT ON TABLE "Inv_OccuranceTime" IS 'One-to-one occurrence time/location record per FIR. NOTE: ER diagram defined no columns beyond the CaseMasterID relationship.';

-- inv_arrestsurrenderaccused: matrix documents it as the junction linking one
-- ArrestSurrender event to many Accused. ArrestSurrenderID FK is explicit in the
-- matrix; AccusedMasterID is inferred from the junction name and stated purpose.
CREATE TABLE "inv_arrestsurrenderaccused" (
    "ArrestSurrenderID" INTEGER NOT NULL REFERENCES "ArrestSurrender" ("ArrestSurrenderID"),
    "AccusedMasterID"   INTEGER NOT NULL REFERENCES "Accused" ("AccusedMasterID"),
    PRIMARY KEY ("ArrestSurrenderID", "AccusedMasterID")
);
COMMENT ON TABLE "inv_arrestsurrenderaccused" IS 'Junction: links one arrest/surrender event to multiple accused. AccusedMasterID inferred from matrix (no column grid in diagram).';

-- =============================================================================
-- 3. INDEXES  (PostgreSQL does not auto-index foreign keys)
-- =============================================================================

-- District / Unit / Court
CREATE INDEX "idx_district_stateid"        ON "District" ("StateID");
CREATE INDEX "idx_unit_typeid"             ON "Unit" ("TypeID");
CREATE INDEX "idx_unit_parentunit"         ON "Unit" ("ParentUnit");
CREATE INDEX "idx_unit_stateid"            ON "Unit" ("StateID");
CREATE INDEX "idx_unit_districtid"         ON "Unit" ("DistrictID");
CREATE INDEX "idx_court_districtid"        ON "Court" ("DistrictID");
CREATE INDEX "idx_court_stateid"           ON "Court" ("StateID");

-- Employee
CREATE INDEX "idx_employee_districtid"     ON "Employee" ("DistrictID");
CREATE INDEX "idx_employee_unitid"         ON "Employee" ("UnitID");
CREATE INDEX "idx_employee_rankid"         ON "Employee" ("RankID");
CREATE INDEX "idx_employee_designationid"  ON "Employee" ("DesignationID");

-- Crime classification
CREATE INDEX "idx_crimesubhead_crimeheadid" ON "CrimeSubHead" ("CrimeHeadID");
CREATE INDEX "idx_section_actcode"          ON "Section" ("ActCode");
CREATE INDEX "idx_crimeheadactsection_actcode"     ON "CrimeHeadActSection" ("ActCode");
CREATE INDEX "idx_crimeheadactsection_sectioncode" ON "CrimeHeadActSection" ("SectionCode");

-- CaseMaster FKs
CREATE INDEX "idx_casemaster_policepersonid"   ON "CaseMaster" ("PolicePersonID");
CREATE INDEX "idx_casemaster_policestationid"  ON "CaseMaster" ("PoliceStationID");
CREATE INDEX "idx_casemaster_casecategoryid"   ON "CaseMaster" ("CaseCategoryID");
CREATE INDEX "idx_casemaster_gravityoffenceid" ON "CaseMaster" ("GravityOffenceID");
CREATE INDEX "idx_casemaster_crimemajorheadid" ON "CaseMaster" ("CrimeMajorHeadID");
CREATE INDEX "idx_casemaster_crimeminorheadid" ON "CaseMaster" ("CrimeMinorHeadID");
CREATE INDEX "idx_casemaster_casestatusid"     ON "CaseMaster" ("CaseStatusID");
CREATE INDEX "idx_casemaster_courtid"          ON "CaseMaster" ("CourtID");
CREATE INDEX "idx_casemaster_registereddate"   ON "CaseMaster" ("CrimeRegisteredDate");
-- PostGIS spatial index
CREATE INDEX "idx_casemaster_geom"             ON "CaseMaster" USING GIST ("geom");

-- ComplainantDetails
CREATE INDEX "idx_complainant_casemasterid" ON "ComplainantDetails" ("CaseMasterID");
CREATE INDEX "idx_complainant_occupationid" ON "ComplainantDetails" ("OccupationID");
CREATE INDEX "idx_complainant_religionid"   ON "ComplainantDetails" ("ReligionID");
CREATE INDEX "idx_complainant_casteid"      ON "ComplainantDetails" ("CasteID");

-- ActSectionAssociation (leftmost PK col covers CaseMasterID)
CREATE INDEX "idx_actsection_actid"      ON "ActSectionAssociation" ("ActID");
CREATE INDEX "idx_actsection_sectionid"  ON "ActSectionAssociation" ("SectionID");

-- Victim / Accused
CREATE INDEX "idx_victim_casemasterid"  ON "Victim" ("CaseMasterID");
CREATE INDEX "idx_accused_casemasterid" ON "Accused" ("CaseMasterID");

-- ArrestSurrender
CREATE INDEX "idx_arrest_casemasterid"     ON "ArrestSurrender" ("CaseMasterID");
CREATE INDEX "idx_arrest_stateid"          ON "ArrestSurrender" ("ArrestSurrenderStateId");
CREATE INDEX "idx_arrest_districtid"       ON "ArrestSurrender" ("ArrestSurrenderDistrictId");
CREATE INDEX "idx_arrest_policestationid"  ON "ArrestSurrender" ("PoliceStationID");
CREATE INDEX "idx_arrest_ioid"             ON "ArrestSurrender" ("IOID");
CREATE INDEX "idx_arrest_courtid"          ON "ArrestSurrender" ("CourtID");
CREATE INDEX "idx_arrest_accusedmasterid"  ON "ArrestSurrender" ("AccusedMasterID");

-- ChargesheetDetails
CREATE INDEX "idx_chargesheet_casemasterid"   ON "ChargesheetDetails" ("CaseMasterID");
CREATE INDEX "idx_chargesheet_policepersonid" ON "ChargesheetDetails" ("PolicePersonID");

-- Junction (leftmost PK col covers ArrestSurrenderID)
CREATE INDEX "idx_asaccused_accusedmasterid" ON "inv_arrestsurrenderaccused" ("AccusedMasterID");

-- =============================================================================
-- 4. TRIGGER FUNCTIONS  (derived directly from documented CrimeNo/CaseNo rules)
-- =============================================================================

-- Validates the 18-digit CrimeNo format and auto-derives CaseNo as the last 9
-- digits of CrimeNo when CaseNo is not supplied (per the diagram description).
CREATE OR REPLACE FUNCTION fn_casemaster_biu()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
BEGIN
    IF NEW."CrimeNo" IS NOT NULL AND NEW."CrimeNo" !~ '^[0-9]{18}$' THEN
        RAISE EXCEPTION 'CrimeNo must be exactly 18 digits (got: %)', NEW."CrimeNo";
    END IF;

    IF NEW."CaseNo" IS NULL AND NEW."CrimeNo" IS NOT NULL THEN
        NEW."CaseNo" := RIGHT(NEW."CrimeNo", 9);
    END IF;

    RETURN NEW;
END;
$$;

CREATE TRIGGER "trg_casemaster_biu"
    BEFORE INSERT OR UPDATE ON "CaseMaster"
    FOR EACH ROW
    EXECUTE FUNCTION fn_casemaster_biu();

-- =============================================================================
-- 5. VIEWS
-- =============================================================================

-- Fully resolved FIR listing with human-readable lookup values.
CREATE OR REPLACE VIEW "vw_fir_full" AS
SELECT
    cm."CaseMasterID",
    cm."CrimeNo",
    cm."CaseNo",
    cm."CrimeRegisteredDate",
    cat."LookupValue"        AS "CaseCategory",
    grv."LookupValue"        AS "GravityOffence",
    ch."CrimeGroupName"      AS "CrimeMajorHead",
    csh."CrimeHeadName"      AS "CrimeMinorHead",
    st."CaseStatusName"      AS "CaseStatus",
    ct."CourtName"           AS "Court",
    u."UnitName"             AS "PoliceStation",
    d."DistrictName"         AS "District",
    s."StateName"            AS "State",
    (e."FirstName")          AS "RegisteredByOfficer",
    cm."IncidentFromDate",
    cm."IncidentToDate",
    cm."InfoReceivedPSDate",
    cm."latitude",
    cm."longitude",
    cm."geom",
    cm."BriefFacts"
FROM "CaseMaster" cm
LEFT JOIN "CaseCategory"     cat ON cat."CaseCategoryID"   = cm."CaseCategoryID"
LEFT JOIN "GravityOffence"   grv ON grv."GravityOffenceID" = cm."GravityOffenceID"
LEFT JOIN "CrimeHead"        ch  ON ch."CrimeHeadID"       = cm."CrimeMajorHeadID"
LEFT JOIN "CrimeSubHead"     csh ON csh."CrimeSubHeadID"   = cm."CrimeMinorHeadID"
LEFT JOIN "CaseStatusMaster" st  ON st."CaseStatusID"      = cm."CaseStatusID"
LEFT JOIN "Court"            ct  ON ct."CourtID"           = cm."CourtID"
LEFT JOIN "Unit"             u   ON u."UnitID"             = cm."PoliceStationID"
LEFT JOIN "District"         d   ON d."DistrictID"         = u."DistrictID"
LEFT JOIN "State"            s   ON s."StateID"            = u."StateID"
LEFT JOIN "Employee"         e   ON e."EmployeeID"         = cm."PolicePersonID";

-- Arrest / surrender events with resolved accused, case, location and officer.
CREATE OR REPLACE VIEW "vw_arrest_details" AS
SELECT
    a."ArrestSurrenderID",
    a."CaseMasterID",
    cm."CrimeNo",
    a."ArrestSurrenderTypeID",
    a."ArrestSurrenderDate",
    acc."AccusedName",
    acc."PersonID"        AS "AccusedSortKey",
    s."StateName"         AS "ArrestState",
    d."DistrictName"      AS "ArrestDistrict",
    u."UnitName"          AS "PoliceStation",
    io."FirstName"        AS "InvestigatingOfficer",
    ct."CourtName"        AS "ProducedBeforeCourt",
    a."IsAccused",
    a."IsComplainantAccused"
FROM "ArrestSurrender" a
LEFT JOIN "CaseMaster" cm ON cm."CaseMasterID" = a."CaseMasterID"
LEFT JOIN "Accused"    acc ON acc."AccusedMasterID" = a."AccusedMasterID"
LEFT JOIN "State"      s  ON s."StateID"      = a."ArrestSurrenderStateId"
LEFT JOIN "District"   d  ON d."DistrictID"   = a."ArrestSurrenderDistrictId"
LEFT JOIN "Unit"       u  ON u."UnitID"       = a."PoliceStationID"
LEFT JOIN "Employee"   io ON io."EmployeeID"  = a."IOID"
LEFT JOIN "Court"      ct ON ct."CourtID"     = a."CourtID";

-- =============================================================================
-- 6. MATERIALIZED VIEWS
-- =============================================================================

-- Crime statistics aggregated by district, category and status.
-- Refresh with:  REFRESH MATERIALIZED VIEW CONCURRENTLY "mv_crime_stats";
CREATE MATERIALIZED VIEW "mv_crime_stats" AS
SELECT
    u."DistrictID",
    d."DistrictName",
    cm."CaseCategoryID",
    cat."LookupValue"     AS "CaseCategory",
    cm."CaseStatusID",
    st."CaseStatusName",
    COUNT(*)              AS "CaseCount"
FROM "CaseMaster" cm
LEFT JOIN "Unit"             u   ON u."UnitID"           = cm."PoliceStationID"
LEFT JOIN "District"         d   ON d."DistrictID"       = u."DistrictID"
LEFT JOIN "CaseCategory"     cat ON cat."CaseCategoryID" = cm."CaseCategoryID"
LEFT JOIN "CaseStatusMaster" st  ON st."CaseStatusID"    = cm."CaseStatusID"
GROUP BY u."DistrictID", d."DistrictName", cm."CaseCategoryID",
         cat."LookupValue", cm."CaseStatusID", st."CaseStatusName"
WITH NO DATA;

-- Unique index required for REFRESH ... CONCURRENTLY.
CREATE UNIQUE INDEX "idx_mv_crime_stats_key"
    ON "mv_crime_stats" ("DistrictID", "CaseCategoryID", "CaseStatusID");

-- =============================================================================
-- 7. ROW LEVEL SECURITY — explicitly DISABLED on every base table
--    (RLS is off by default; these statements make the intent explicit.)
-- =============================================================================
ALTER TABLE "State"                     DISABLE ROW LEVEL SECURITY;
ALTER TABLE "District"                  DISABLE ROW LEVEL SECURITY;
ALTER TABLE "UnitType"                  DISABLE ROW LEVEL SECURITY;
ALTER TABLE "Unit"                      DISABLE ROW LEVEL SECURITY;
ALTER TABLE "Rank"                      DISABLE ROW LEVEL SECURITY;
ALTER TABLE "Designation"               DISABLE ROW LEVEL SECURITY;
ALTER TABLE "Employee"                  DISABLE ROW LEVEL SECURITY;
ALTER TABLE "Court"                     DISABLE ROW LEVEL SECURITY;
ALTER TABLE "CaseCategory"              DISABLE ROW LEVEL SECURITY;
ALTER TABLE "GravityOffence"            DISABLE ROW LEVEL SECURITY;
ALTER TABLE "CrimeHead"                 DISABLE ROW LEVEL SECURITY;
ALTER TABLE "CrimeSubHead"              DISABLE ROW LEVEL SECURITY;
ALTER TABLE "CaseStatusMaster"          DISABLE ROW LEVEL SECURITY;
ALTER TABLE "CasteMaster"               DISABLE ROW LEVEL SECURITY;
ALTER TABLE "ReligionMaster"            DISABLE ROW LEVEL SECURITY;
ALTER TABLE "OccupationMaster"          DISABLE ROW LEVEL SECURITY;
ALTER TABLE "Act"                       DISABLE ROW LEVEL SECURITY;
ALTER TABLE "Section"                   DISABLE ROW LEVEL SECURITY;
ALTER TABLE "CrimeHeadActSection"       DISABLE ROW LEVEL SECURITY;
ALTER TABLE "CaseMaster"                DISABLE ROW LEVEL SECURITY;
ALTER TABLE "ComplainantDetails"        DISABLE ROW LEVEL SECURITY;
ALTER TABLE "ActSectionAssociation"     DISABLE ROW LEVEL SECURITY;
ALTER TABLE "Victim"                    DISABLE ROW LEVEL SECURITY;
ALTER TABLE "Accused"                   DISABLE ROW LEVEL SECURITY;
ALTER TABLE "ArrestSurrender"           DISABLE ROW LEVEL SECURITY;
ALTER TABLE "ChargesheetDetails"        DISABLE ROW LEVEL SECURITY;
ALTER TABLE "Inv_OccuranceTime"         DISABLE ROW LEVEL SECURITY;
ALTER TABLE "inv_arrestsurrenderaccused" DISABLE ROW LEVEL SECURITY;

COMMIT;

-- =============================================================================
-- End of schema.
-- =============================================================================
