"""Extract a minimal, faithful fixture from the full schema dump.

Lets migrations 026-032 be validated in a throwaway Postgres without the
pgrouting / pgvector extensions the full dump requires (the standard
postgis/postgis image ships neither). Emits only the enum types, tables,
identity clauses and PK/UNIQUE constraints that those migrations touch, in
dependency order.

    python scripts/migrations/extract_fixture.py

Writes fixture.generated.sql beside this file. See README.md for the full
validation loop.
"""
from __future__ import annotations

import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
DUMP = ROOT / "_migration" / "drishti_schema.sql"
OUT = Path(__file__).resolve().parent / "fixture.generated.sql"

# Dependency-ordered: parents before children.
TABLES = [
    "State", "District", "UnitType", "Unit", "UnitLocation",
    "Rank", "Designation", "Employee",
    "CrimeHead", "CaseCategory", "GravityOffence", "CaseStatusMaster", "Court",
    "CaseMaster", "CaseVersion", "JurisdictionBoundary",
    "roles", "users", "role_permissions",
]
TYPES = ["permission_action_enum"]


def read_dump() -> str:
    return DUMP.read_text(encoding="utf-8", errors="replace")


def grab_type(sql: str, name: str) -> str:
    m = re.search(
        rf'CREATE TYPE public\.{re.escape(name)} AS ENUM \((.*?)\);',
        sql, re.S)
    if not m:
        raise SystemExit(f"type not found: {name}")
    return f"CREATE TYPE public.{name} AS ENUM ({m.group(1)});"


def grab_table(sql: str, name: str) -> str:
    """CREATE TABLE public."Name" ( ... ); — balanced to the terminating ');'."""
    quoted = f'public."{name}"' if name[0].isupper() else f"public.{name}"
    start = sql.find(f"CREATE TABLE {quoted} (")
    if start == -1:
        raise SystemExit(f"table not found: {name}")
    i = sql.index("(", start)
    depth, j = 0, i
    while j < len(sql):
        if sql[j] == "(":
            depth += 1
        elif sql[j] == ")":
            depth -= 1
            if depth == 0:
                break
        j += 1
    return sql[start:j + 1] + ";"


def grab_identity(sql: str, name: str) -> list[str]:
    """Identity clauses, so DEFAULT-generated PKs behave as in production."""
    quoted = f'public."{name}"' if name[0].isupper() else f"public.{name}"
    out = []
    for m in re.finditer(
            rf'ALTER TABLE {re.escape(quoted)} ALTER COLUMN "?(\w+)"? '
            r'ADD GENERATED BY DEFAULT AS IDENTITY \(', sql):
        col = m.group(1)
        q = f'"{col}"' if col[0].isupper() else col
        out.append(
            f"ALTER TABLE {quoted} ALTER COLUMN {q} "
            f"ADD GENERATED BY DEFAULT AS IDENTITY;")
    return out


def primary_keys(sql: str, name: str) -> list[str]:
    """PK/UNIQUE constraints only. FKs are skipped: the fixture is a subset, so
    foreign keys to omitted tables cannot resolve. The migrations under test add
    their own FKs, and those ARE exercised."""
    quoted = f'public."{name}"' if name[0].isupper() else f"public.{name}"
    out = []
    pat = (rf'ALTER TABLE ONLY {re.escape(quoted)}\s+'
           r'ADD CONSTRAINT ([^\s]+) (PRIMARY KEY|UNIQUE) \(([^)]*)\)')
    for m in re.finditer(pat, sql):
        out.append(f"ALTER TABLE ONLY {quoted} ADD CONSTRAINT {m.group(1)} "
                   f"{m.group(2)} ({m.group(3)});")
    return out


def main() -> int:
    sql = read_dump()
    parts: list[str] = [
        "-- Auto-extracted fixture. Subset of _migration/drishti_schema.sql",
        "-- covering only what migrations 026-032 touch. Not a deployment artifact.",
        "CREATE EXTENSION IF NOT EXISTS postgis;",
        "CREATE EXTENSION IF NOT EXISTS pg_trgm;",
        "",
    ]
    for t in TYPES:
        parts.append(grab_type(sql, t))
    parts.append("")
    for t in TABLES:
        parts.append(grab_table(sql, t))
        parts.extend(grab_identity(sql, t))
        parts.extend(primary_keys(sql, t))
        parts.append("")

    OUT.write_text("\n".join(parts), encoding="utf-8")
    print(f"wrote {OUT} ({len(parts)} statements, "
          f"{len(OUT.read_text(encoding='utf-8').splitlines())} lines)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
