// Recreate the Catalyst Slate SPA config inside the build output.
//
// A clean `vite build` wipes dist/, so dist/.catalyst/slate-config.toml (which
// Slate reads for SPA deep-link fallback) must be regenerated after every build.
// This mirrors the committed reference at infra/catalyst/client/slate-config.toml
// and the `_redirects` file Vite copies from public/ (belt-and-braces).

import { mkdirSync, writeFileSync, existsSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const distDir = join(here, "..", "dist");

if (!existsSync(distDir)) {
  console.error("[postbuild-slate] dist/ not found — run `vite build` first.");
  process.exit(1);
}

const catalystDir = join(distDir, ".catalyst");
const config = `# Generated by scripts/postbuild-slate.mjs after each build (see
# infra/catalyst/client/slate-config.toml for the committed reference).
framework = "react-vite"
deployment_name = "default"

# Legacy Catalyst embedded-auth /app/ redirect target → root.
[[redirects]]
from = "/app/*"
to = "/index.html"
status = 200

# SPA catch-all: every client-side route serves index.html with HTTP 200.
[[redirects]]
from = "/*"
to = "/index.html"
status = 200
`;

mkdirSync(catalystDir, { recursive: true });
writeFileSync(join(catalystDir, "slate-config.toml"), config, "utf8");
console.log("[postbuild-slate] wrote dist/.catalyst/slate-config.toml");
