#!/usr/bin/env python3
"""Generate + verify the route-to-data-boundary inventory (Prompt 21 §A).

Enumerates every deployed FastAPI route, classifies each into its deployment
data boundary (via app.deployment_boundary), statically detects direct
PostgreSQL-connector usage per domain, and writes:

  * docs/deployment/ROUTE_DATA_BOUNDARY.md   (human-readable inventory)
  * docs/deployment/route-data-boundary.json (machine-checkable inventory)

Usage (run from services/ml so ``import app`` resolves):
    python tools/route_data_boundary.py            # write docs + json
    python tools/route_data_boundary.py --check    # exit 1 on any violation

The app imports with NO DATABASE_URL (Data Store / offline). The generator sets
DRISHTI_DISABLE_DB_TESTS so importing never attempts an analytics DB connect.
"""
from __future__ import annotations

import argparse
import json
import os
import sys
from datetime import datetime, timezone
from pathlib import Path

os.environ.setdefault("DRISHTI_DISABLE_DB_TESTS", "1")

_ML_ROOT = Path(__file__).resolve().parents[1]
if str(_ML_ROOT) not in sys.path:
    sys.path.insert(0, str(_ML_ROOT))
_REPO_ROOT = _ML_ROOT.parents[1]

from app import deployment_boundary as db  # noqa: E402

DOCS_DIR = _REPO_ROOT / "docs" / "deployment"
MD_PATH = DOCS_DIR / "ROUTE_DATA_BOUNDARY.md"
JSON_PATH = DOCS_DIR / "route-data-boundary.json"

_CLASS_ORDER = (
    db.CATALYST_OPERATIONAL, db.AWS_ANALYTICS, db.DISABLED_OUT_OF_SCOPE,
    db.LOCAL_TOOLING_ONLY, db.INFRASTRUCTURE, "UNCLASSIFIED",
)
_CLASS_TITLE = {
    db.CATALYST_OPERATIONAL: "CATALYST_OPERATIONAL — Catalyst Data Store / Stratus",
    db.AWS_ANALYTICS: "AWS_ANALYTICS — protected server-to-server adapter only",
    db.DISABLED_OUT_OF_SCOPE: "DISABLED_OUT_OF_SCOPE — hidden from the submitted UI",
    db.LOCAL_TOOLING_ONLY: "LOCAL_TOOLING_ONLY — batch/admin tooling",
    db.INFRASTRUCTURE: "INFRASTRUCTURE — health/docs (no application data)",
    "UNCLASSIFIED": "UNCLASSIFIED — MUST be classified",
}


def _load_app():
    from app.main import app
    return app


def _render_md(report: dict, violations: list[str]) -> str:
    now = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")
    lines: list[str] = []
    lines.append("# DRISHTI Route-to-Data-Boundary Inventory")
    lines.append("")
    lines.append("> Generated by `services/ml/tools/route_data_boundary.py` "
                 "from the live FastAPI route table and "
                 "`app/deployment_boundary.py`. Do not edit by hand.")
    lines.append("")
    lines.append(f"- Generated: {now}")
    lines.append(f"- Total deployed routes: **{report['total_routes']}**")
    lines.append(f"- Domains: **{report['domain_count']}**")
    lines.append(f"- Boundary check: **{'PASS' if not violations else 'FAIL'}**")
    lines.append("")
    lines.append("## Route counts by data boundary")
    lines.append("")
    lines.append("| Data boundary | Routes |")
    lines.append("| --- | ---: |")
    for cls in _CLASS_ORDER:
        cnt = report["route_count_by_class"].get(cls, 0)
        if cnt or cls != "UNCLASSIFIED":
            lines.append(f"| {cls} | {cnt} |")
    lines.append("")

    if violations:
        lines.append("## Boundary violations")
        lines.append("")
        for v in violations:
            lines.append(f"- FAIL: {v}")
        lines.append("")

    # Group domains by class.
    by_class: dict[str, list[str]] = {c: [] for c in _CLASS_ORDER}
    for domain, info in report["domains"].items():
        by_class.setdefault(info["boundary"], []).append(domain)

    for cls in _CLASS_ORDER:
        domains = sorted(by_class.get(cls, []))
        if not domains:
            continue
        lines.append(f"## {_CLASS_TITLE.get(cls, cls)}")
        lines.append("")
        for domain in domains:
            info = report["domains"][domain]
            mig = info.get("migration", db.MIG_NA)
            mig_txt = "" if mig in (db.MIG_NA, None) else f" · migration: `{mig}`"
            vis = "" if info.get("demo_visible", True) else " · not in submitted UI"
            lines.append(f"### `{domain}` ({info['route_count']} routes){vis}")
            lines.append("")
            lines.append(f"- Backend: {info.get('backend','')}{mig_txt}")
            if info.get("rationale"):
                lines.append(f"- Rationale: {info['rationale']}")
            offenders = info.get("direct_db_modules") or []
            if offenders:
                tag = ("expected (RDS-backed, migration pending)"
                       if mig == db.MIG_PENDING or cls == db.AWS_ANALYTICS
                       else "VIOLATION (native domain must not import the connector)")
                lines.append(f"- Direct PostgreSQL-connector imports [{tag}]: "
                             f"{', '.join(m.split('.',1)[1] for m in offenders)}")
            lines.append("")
    return "\n".join(lines).rstrip() + "\n"


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true",
                    help="exit non-zero if any boundary violation is found")
    args = ap.parse_args()

    app = _load_app()
    report = db.analyze(app)
    violations = db.check(app)

    if args.check:
        if violations:
            print("ROUTE DATA BOUNDARY CHECK: FAIL")
            for v in violations:
                print(f"  - {v}")
            return 1
        print(f"ROUTE DATA BOUNDARY CHECK: PASS "
              f"({report['total_routes']} routes, {report['domain_count']} domains)")
        return 0

    DOCS_DIR.mkdir(parents=True, exist_ok=True)
    JSON_PATH.write_text(json.dumps(report, indent=2) + "\n", encoding="utf-8")
    MD_PATH.write_text(_render_md(report, violations), encoding="utf-8")
    print(f"wrote {MD_PATH.relative_to(_REPO_ROOT)}")
    print(f"wrote {JSON_PATH.relative_to(_REPO_ROOT)}")
    print(f"routes={report['total_routes']} domains={report['domain_count']} "
          f"violations={len(violations)}")
    for v in violations:
        print(f"  VIOLATION: {v}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
